'use strict'
const test=require('node:test');const assert=require('node:assert/strict')
const {createAuthorizationFreshnessService}=require('../authorization/runtime')
const {createDelegationContextService,createInMemoryDelegationContextRepository}=require('../authorization/delegation')
const {AUTHORIZATION_EVENT_TYPES}=require('../authorization/runtime/authorizationEvents')
test('membership, role, ceiling, activation and Data Scope events bump snapshots and invalidate tenant caches',async()=>{let version=1;const events=[],invalidations=[];const service=createAuthorizationFreshnessService({versionService:{async increment(){return{policyVersion:String(++version)}},async getVersion(){return{policyVersion:String(version)}}},cachePort:{async invalidateOrganization(e){invalidations.push(e)}},eventPort:{async publish(e){events.push(e)}}});for(const eventType of [AUTHORIZATION_EVENT_TYPES.MEMBERSHIP_CHANGED,AUTHORIZATION_EVENT_TYPES.ROLE_REVOKED,AUTHORIZATION_EVENT_TYPES.CEILING_CHANGED,AUTHORIZATION_EVENT_TYPES.ACTIVATION_CHANGED,AUTHORIZATION_EVENT_TYPES.DATA_SCOPE_ASSIGNMENT_CREATED])await service.invalidate({organizationId:'org',eventType,aggregateId:'x'});assert.equal(invalidations.length,5);assert.equal(events.every(e=>e.requiresReauthorization),true);await assert.rejects(()=>service.assertCurrent({organizationId:'org',snapshotVersion:1}),{code:'authorization_snapshot_stale'});assert.equal(await service.assertCurrent({organizationId:'org',snapshotVersion:version}),true)})
test('delegation context is short-lived, read-only by default, revocable, actor-preserving and audited',async()=>{let now=new Date('2026-07-29T00:00:00Z');const audits=[];const service=createDelegationContextService({repository:createInMemoryDelegationContextRepository(),auditPort:{async record(e){audits.push(e)}},now:()=>now});const context=await service.issue({actorSubject:'support_1',actorSurface:'owner',clientId:'core',targetOrganizationId:'org',reason:'ticket-7',expiresAt:'2026-07-29T00:10:00Z',allowedCapabilities:['lms.groups']});assert.ok(context.deniedEffects.includes('write'));await service.authorize({decisionId:context.decisionId,actorSubject:'support_1',targetOrganizationId:'org',capability:'lms.groups',effect:'read'});await assert.rejects(()=>service.authorize({decisionId:context.decisionId,actorSubject:'support_1',targetOrganizationId:'org',capability:'lms.groups',effect:'write'}),{code:'delegation_effect_denied'});await service.revoke({decisionId:context.decisionId,actorSubject:'support_1',reason:'done'});await assert.rejects(()=>service.authorize({decisionId:context.decisionId,actorSubject:'support_1',targetOrganizationId:'org',capability:'lms.groups',effect:'read'}),{code:'delegation_invalid'});assert.equal(audits.every(e=>e.actorSubject==='support_1'),true)})

test('real mutation seams and snapshot policy adapter invoke freshness service',async()=>{const calls=[];const freshness={async invalidate(event){calls.push(event);return{policyVersion:'9'}},async assertCurrent(input){calls.push(input);if(input.snapshotVersion!=='9')throw Object.assign(new Error('stale'),{code:'authorization_snapshot_stale'})}};const {createEntitlementService}=require('../authorization/entitlements/entitlementService');const repository={async getPolicyVersion(){return 8},async transaction(fn){return fn()},async getLimit(){return null},async upsertLimit(row){return{id:'limit',...row}},async disableActivation(){}};const audit=[];const entitlement=createEntitlementService({repository,authorizationFreshnessService:freshness,runtimeConsistencyPort:{async audit(e){audit.push(e)}} ,roleIdToName:{role_admin:'organization_admin'}});await entitlement.upsertOwnerLimits({organizationId:'org',changes:[{logtoRoleId:'role_admin',permission:'org.documents.read',allowed:true}],actorLogtoUserId:'actor',reason:'test'});assert.equal(calls[0].eventType,AUTHORIZATION_EVENT_TYPES.CEILING_CHANGED);const {createEntitlementPolicyProvider}=require('../authorization/entitlements/entitlementPolicyAdapter');const provider=createEntitlementPolicyProvider({repository,authorizationFreshnessService:freshness});assert.equal((await provider.evaluateSnapshot({organizationId:'org',policyVersion:'9'})).status,'current');assert.equal((await provider.evaluateSnapshot({organizationId:'org',policyVersion:'8'})).status,'stale')})

test('delegation exports durable PostgreSQL repository and middleware integration',()=>{const delegation=require('../authorization/delegation');assert.equal(typeof delegation.createPostgresDelegationContextRepository,'function');assert.equal(typeof delegation.requireDelegationContext,'function');const sql=require('node:fs').readFileSync(require('node:path').join(__dirname,'../db/migrations/0027_authorization_delegation_contexts.sql'),'utf8');assert.match(sql,/expires_at.*15 minutes/s);assert.match(sql,/target_organization_id/)})
