const test = require("node:test");
const assert = require("node:assert/strict");
const { createDocumentService, createInMemoryDocumentRepository } = require("../documents/documentService");

function fixture() {
  let now = new Date("2026-07-01T00:00:00Z"), puts = 0, deletes = 0, grants = 0;
  const repository = createInMemoryDocumentRepository();
  const storage = { async put() { puts++; return { fileReference: `file_${String(puts).padStart(16, "0")}` }; }, async signDownload() { grants++; return { url: `https://download.invalid/grant/${grants}`, expiresAt: new Date(now.getTime() + 60000).toISOString() }; }, async delete() { deletes++; } };
  const service = createDocumentService({ repository, storage, clock: () => now, authorize: async ({ action, principal, organizationId }) => principal?.organizationId === organizationId && (action === "documents.download" ? principal?.canDownload : principal?.canGenerate) });
  return { service, repository, storage, setNow: (value) => { now = new Date(value); }, stats: () => ({ puts, deletes, grants }) };
}
const request = (service, overrides = {}) => service.requestGeneration({ organizationId: "tenant-a", idempotencyKey: "idem-1", templateId: "invoice", planVersion: "plan-7", profileVersion: "profile-3", templateVersion: "template-11", parameters: { invoiceId: "inv-1" }, principal: { subject: "user-1", organizationId: "tenant-a", canGenerate: true }, ...overrides });

test("duplicate requests and worker retries are idempotent", async () => { const f = fixture(); const first = await request(f.service); const duplicate = await request(f.service); assert.equal(duplicate.operationId, first.operationId); assert.equal(duplicate.duplicate, true); await f.service.runGeneration({ organizationId: "tenant-a", operationId: first.operationId, render: async () => Buffer.from("pdf") }); await f.service.runGeneration({ organizationId: "tenant-a", operationId: first.operationId, render: async () => { throw new Error("must not render twice"); } }); assert.equal(f.stats().puts, 1); assert.equal(f.repository.outbox.filter((e) => e.type === "documents.generation.requested").length, 1); });
test("retry after a transient failure recovers the same operation", async () => { const f = fixture(); const op = await request(f.service); const error = new Error("temporary"); error.retryable = true; await assert.rejects(f.service.runGeneration({ organizationId: "tenant-a", operationId: op.operationId, render: async () => { throw error; } })); const result = await f.service.runGeneration({ organizationId: "tenant-a", operationId: op.operationId, render: async () => Buffer.from("recovered") }); assert.equal(result.state, "succeeded"); assert.equal(result.operationId, op.operationId); });
test("queued generation can be cancelled", async () => { const f = fixture(); const op = await request(f.service); assert.equal((await f.service.cancel({ organizationId: "tenant-a", operationId: op.operationId, principal: { organizationId: "tenant-a", canGenerate: true } })).state, "cancelled"); await f.service.runGeneration({ organizationId: "tenant-a", operationId: op.operationId, render: async () => { throw new Error("not called"); } }); });
test("request authorization and immutable versions are mandatory", async () => { const f = fixture(); await assert.rejects(f.service.requestGeneration({ organizationId: "tenant-a", idempotencyKey: "x" }), { code: "document_generation_invalid" }); await assert.rejects(request(f.service, { principal: { organizationId: "tenant-b", canGenerate: true } }), { code: "document_generation_forbidden" }); const op = await request(f.service); const persisted = f.repository.operations.get(`tenant-a:${op.operationId}`); assert.deepEqual([persisted.planVersion,persisted.profileVersion,persisted.templateVersion], ["plan-7","profile-3","template-11"]); });
test("documents are tenant isolated and downloads are freshly authorized", async () => { const f = fixture(); const op = await request(f.service); const done = await f.service.runGeneration({ organizationId: "tenant-a", operationId: op.operationId, render: async () => Buffer.from("private") }); await assert.rejects(f.service.getDocument({ organizationId: "tenant-b", documentId: done.documentId }), { code: "document_not_found" }); await assert.rejects(f.service.authorizeDownload({ organizationId: "tenant-a", documentId: done.documentId, principal: { organizationId: "tenant-a" } }), { code: "document_download_forbidden" }); const one = await f.service.authorizeDownload({ organizationId: "tenant-a", documentId: done.documentId, principal: { organizationId: "tenant-a", canDownload: true } }); const two = await f.service.authorizeDownload({ organizationId: "tenant-a", documentId: done.documentId, principal: { organizationId: "tenant-a", canDownload: true } }); assert.notEqual(one.url, two.url); assert.equal(new URL(one.url).origin, "https://download.invalid"); });
test("retention deletes expired objects but legal hold blocks deletion", async () => { const f = fixture(); const one = await request(f.service); const done = await f.service.runGeneration({ organizationId: "tenant-a", operationId: one.operationId, render: async () => Buffer.from("one") }); const held = f.repository.documents.get(`tenant-a:${done.documentId}`); held.legalHold = true; f.setNow("2026-08-15T00:00:00Z"); assert.equal(await f.service.enforceRetention(), 0); held.legalHold = false; assert.equal(await f.service.enforceRetention(), 1); assert.equal(f.stats().deletes, 1); });
test("events and logs expose no content, URL, secrets, parameters or file references", async () => { const f = fixture(); const op = await request(f.service, { parameters: { confidentialName: "Ada" } }); await f.service.runGeneration({ organizationId: "tenant-a", operationId: op.operationId, render: async () => Buffer.from("sensitive body") }); const serialized = JSON.stringify(f.repository.outbox); assert.doesNotMatch(serialized, /Ada|sensitive body|file_|https?:|secret|token|parameters/i); });
