"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { RoleLabelService, canonicalRoles, resolveEffectiveRoleLabel, normalizeRoleLabel } = require("../governance/role-labels");
class Repo{constructor(){this.globals=new Map();this.aliases=new Map();this.gv=0;this.ov=new Map();this.auditEvents=[];this.queryCount=0;} async transaction(fn){return fn(this)} async getGlobalOverrides(){this.queryCount++;return [...this.globals.values()]} async getGlobalOverride(k){return this.globals.get(k)||null} async listOrganizationAliases(o){this.queryCount++;return [...(this.aliases.get(o)||new Map()).values()]} async getOrganizationAlias(o,k){return this.aliases.get(o)?.get(k)||null} async getGlobalVersion(){return String(this.gv)} async getOrganizationVersion(o){return String(this.ov.get(o)||0)} async incrementGlobalVersion(){this.gv++;return String(this.gv)} async incrementOrganizationVersion(o){this.ov.set(o,(this.ov.get(o)||0)+1);return String(this.ov.get(o))} async upsertGlobalOverride(x){this.globals.set(x.canonicalRoleKey,{...x});return x} async deleteGlobalOverride(k){this.globals.delete(k)} async upsertOrganizationAlias(x){if(!this.aliases.has(x.organizationId))this.aliases.set(x.organizationId,new Map());this.aliases.get(x.organizationId).set(x.canonicalRoleKey,{...x});return x} async deleteOrganizationAlias(o,k){this.aliases.get(o)?.delete(k)} async audit(e){this.auditEvents.push(e);return {id:String(this.auditEvents.length),createdAt:new Date().toISOString()}}}
const roles = canonicalRoles().map((r,i)=>({id:`logto-${i}`,name:r.canonicalRoleKey}));
test("all canonical roles expose baseline presentation labels",()=>{assert.equal(canonicalRoles().length,13); for(const role of canonicalRoles()) assert.match(role.canonicalBaselineLabel,/Organization /);});
test("resolver order is organization alias, Civitas default, baseline, key",()=>{assert.equal(resolveEffectiveRoleLabel({canonicalRoleKey:"organization_teacher",canonicalBaselineLabel:"Teacher",globalOverrides:[{canonicalRoleKey:"organization_teacher",displayName:"Instructor"}],organizationAliases:[{canonicalRoleKey:"organization_teacher",displayName:"Coach"}]}).effectiveLabel,"Coach");assert.equal(resolveEffectiveRoleLabel({canonicalRoleKey:"organization_teacher",canonicalBaselineLabel:"Teacher",globalOverrides:[{canonicalRoleKey:"organization_teacher",displayName:"Instructor"}],organizationAliases:[]}).source,"civitas_default");assert.equal(resolveEffectiveRoleLabel({canonicalRoleKey:"organization_teacher",canonicalBaselineLabel:"Teacher",globalOverrides:[],organizationAliases:[]}).effectiveLabel,"Teacher");assert.equal(resolveEffectiveRoleLabel({canonicalRoleKey:"organization_teacher",canonicalBaselineLabel:"",globalOverrides:[],organizationAliases:[]}).effectiveLabel,"organization_teacher");});
test("global defaults persist in repository and aliases override without changing Logto identity",async()=>{const repo=new Repo();const svc=new RoleLabelService({repository:repo});let model=await svc.buildReadModel({organizationId:"org-a",roles,surface:"owner"});await svc.updateGlobalLabel({canonicalRoleKey:"organization_teacher",displayName:"Instructor",expectedVersion:model.globalVersion,actorLogtoUserId:"owner",reason:"test"});model=await svc.buildReadModel({organizationId:"org-a",roles,surface:"tenant"});let row=model.rows.find(r=>r.canonicalRoleKey==="organization_teacher");assert.equal(row.effectiveLabel,"Instructor");assert.equal(row.logtoRoleId,"logto-5");assert.equal(row.logtoRoleName,"organization_teacher");await svc.updateOrganizationAlias({organizationId:"org-a",canonicalRoleKey:"organization_teacher",logtoRoleIdSnapshot:"logto-5",displayName:"Academic Coach",expectedVersion:model.organizationVersion,actorLogtoUserId:"admin",reason:"test"});const a=await svc.buildReadModel({organizationId:"org-a",roles,surface:"tenant"});const b=await svc.buildReadModel({organizationId:"org-b",roles,surface:"tenant"});assert.equal(a.rows.find(r=>r.canonicalRoleKey==="organization_teacher").effectiveLabel,"Academic Coach");assert.equal(b.rows.find(r=>r.canonicalRoleKey==="organization_teacher").effectiveLabel,"Instructor");assert.equal(repo.auditEvents.length,2);assert.ok(repo.queryCount<=20);});
test("stale versions and duplicate labels are rejected",async()=>{const repo=new Repo();const svc=new RoleLabelService({repository:repo});await svc.updateGlobalLabel({canonicalRoleKey:"organization_teacher",displayName:"Instructor",expectedVersion:"0"});await assert.rejects(()=>svc.updateGlobalLabel({canonicalRoleKey:"organization_student",displayName:"Learner",expectedVersion:"0"}),/changed by another administrator/);await svc.updateGlobalLabel({canonicalRoleKey:"organization_student",displayName:"Learner",expectedVersion:"1"});await assert.rejects(()=>svc.updateGlobalLabel({canonicalRoleKey:"organization_parent",displayName:"learner",expectedVersion:"2"}),/already uses/);});
test("control and bidi characters are rejected",()=>{assert.throws(()=>normalizeRoleLabel("Bad\u202ename"),/control/);assert.throws(()=>normalizeRoleLabel("!!!"),/letters or numbers/);});
test("role label service does not call Logto role rename/update APIs",()=>{const files=["roleLabelService.js","postgresRoleLabelRepository.js","effectiveRoleLabelResolver.js"].map(f=>fs.readFileSync(path.join(__dirname,"../governance/role-labels",f),"utf8")).join("\n");assert.doesNotMatch(files,/updateOrganizationRole|updateRole|rename|patchOrganizationRole|Logto Management API/i);});
