const test=require('node:test'); const assert=require('node:assert/strict');
const { initialState,applyReviewEvent,rehydrateReviewWorkflow,workflow,snapshotHash }=require('../planning/domain');
const base={organizationId:'o1',planId:'p1',actorId:'author',authorId:'author',planVersion:1,policyVersion:1,occurredAt:'2026-01-01T00:00:00Z'};
function policy(state){return applyReviewEvent(state,workflow.versionPolicy(state,{...base,policy:{version:1,minimumApprovals:1,separationOfDuties:true}}));}
function assigned(role='approver',assigneeId='checker'){let s=policy(initialState('o1','p1'));s=applyReviewEvent(s,workflow.addCollaborator(s,{...base,collaboratorId:'editor'}));s=applyReviewEvent(s,workflow.assign(s,{...base,assignmentId:'a1',role,assigneeId}));return s;}
test('persists collaborators and distinct reviewer/approver assignments',()=>{let s=assigned();assert.equal(s.collaborators.get('editor').active,true);assert.equal(s.assignments.get('a1').role,'approver');assert.throws(()=>workflow.requestChanges(applyReviewEvent(s,workflow.submit(s,base)),{...base,actorId:'checker',assignmentId:'a1'}),/assignment_not_active/);});
test('denies self approval and stale policy/assignment versions',()=>{let s=assigned('approver','author');s=applyReviewEvent(s,workflow.submit(s,base));assert.throws(()=>workflow.approve(s,{...base,assignmentId:'a1',approvedSnapshot:{title:'x'}}),/self_approval_denied/);assert.throws(()=>workflow.approve(s,{...base,actorId:'author',policyVersion:2,assignmentId:'a1',approvedSnapshot:{title:'x'}}),/stale_policy_version/);});
test('tenant boundary rejects cross-tenant events',()=>assert.throws(()=>applyReviewEvent(initialState('o1','p1'),{...base,organizationId:'o2',type:'planning.review_submitted.v1',aggregateVersion:1}),/tenant_or_aggregate_mismatch/));
test('approved snapshots are immutable, hashed with provenance, and seed an independent new draft',()=>{let s=assigned();s=applyReviewEvent(s,workflow.submit(s,base));const source={title:'approved',nested:{value:1}};const approved=workflow.approve(s,{...base,actorId:'checker',assignmentId:'a1',approvedSnapshot:source,provenance:{sourceRevision:'r1'}});source.nested.value=9;assert.equal(approved.snapshotHash,snapshotHash({title:'approved',nested:{value:1}}));assert.equal(approved.approvedSnapshot.nested.value,1);assert.equal(approved.provenance.sourceRevision,'r1');s=applyReviewEvent(s,approved);const draft=workflow.draftFromApproved(s,{...base});draft.baseSnapshot.nested.value=2;assert.equal(s.approvedSnapshot.nested.value,1);const rebuilt=rehydrateReviewWorkflow([...[]],base);assert.equal(rebuilt.status,'draft');});
test('review requests bind active assignments and policy version',()=>{let s=assigned('reviewer','reviewer');const request=workflow.requestReview(s,{...base,reviewRequestId:'rr1',assignmentIds:['a1']});s=applyReviewEvent(s,request);assert.equal(s.reviewRequests.get('rr1').policyVersion,1);assert.throws(()=>workflow.requestReview(s,{...base,policyVersion:2,reviewRequestId:'rr2',assignmentIds:['a1']}),/stale_policy_version/);});
