'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {createPlanningAuthoringService,PlanningAuthoringError}=require('../planning/application/authoringService');
const {validationRun}=require('../planning/domain/authoring');
function repository(){const tenants=new Map();const state=o=>{if(!tenants.has(o))tenants.set(o,{roadmaps:new Map(),units:new Map(),idem:new Map(),audit:[],outbox:[],input:new Map(),runs:new Map()});return tenants.get(o)};return {tenants,async transaction(org,work){const s=state(org),snapshot=structuredClone(s);const tx={getIdempotency:async k=>s.idem.get(k),putIdempotency:async(k,requestHash,response)=>s.idem.set(k,{requestHash,response}),lockRoadmap:async id=>s.roadmaps.get(id),listUnitIds:async id=>[...(s.units.get(id)||[])].sort((a,b)=>a.rank-b.rank).map(x=>x.id),setUnitRanks:async(id,ranks)=>s.units.set(id,ranks.map(x=>({...x,rank:Number(x.rank)}))),setRoadmapVersion:async(id,v)=>s.roadmaps.get(id).version=v,audit:async e=>s.audit.push(e),outbox:async e=>s.outbox.push(e),loadValidationInput:async id=>s.input.get(id)||{blueprint:null,components:[],calibration:null},upsertValidationRun:async run=>{const key=run.inputHash;s.runs.set(key,s.runs.get(key)||run);return s.runs.get(key)}};try{return await work(tx)}catch(e){tenants.set(org,snapshot);throw e;}}};}
const ctx=(org='a')=>({organizationId:org,actorId:'user',permissions:['planning.roadmaps.write','planning.assessments.validate']});
test('two tenants cannot observe or reorder each other resources',async()=>{const r=repository();r.tenants.set('a',{roadmaps:new Map([['r',{id:'r',version:1}]]),units:new Map([['r',[{id:'u1',rank:1},{id:'u2',rank:2}]]]),idem:new Map(),audit:[],outbox:[],input:new Map(),runs:new Map()});const s=createPlanningAuthoringService(r);await assert.rejects(s.reorderUnits({roadmapId:'r',orderedIds:['u2','u1'],ifMatch:'"1"',idempotencyKey:'x'},ctx('b')),e=>e.status===404);assert.equal(r.tenants.get('a').roadmaps.get('r').version,1);});
test('reorder is stable, idempotent and rejects a concurrent stale ETag',async()=>{const r=repository();r.tenants.set('a',{roadmaps:new Map([['r',{id:'r',version:1}]]),units:new Map([['r',[{id:'u1',rank:1},{id:'u2',rank:2}]]]),idem:new Map(),audit:[],outbox:[],input:new Map(),runs:new Map()});const s=createPlanningAuthoringService(r);const first=await s.reorderUnits({roadmapId:'r',orderedIds:['u2','u1'],ifMatch:'"1"',idempotencyKey:'x'},ctx());assert.deepEqual(first.units.map(x=>x.rank),['1024','2048']);assert.deepEqual(await s.reorderUnits({roadmapId:'r',orderedIds:['u2','u1'],ifMatch:'"1"',idempotencyKey:'x'},ctx()),first);await assert.rejects(s.reorderUnits({roadmapId:'r',orderedIds:['u1','u2'],ifMatch:'"1"',idempotencyKey:'y'},ctx()),e=>e.status===412);assert.equal(r.tenants.get('a').audit.length,1);assert.equal(r.tenants.get('a').outbox.length,1);});
test('validation is deterministic regardless of object and component order',()=>{const input={organizationId:'a',blueprint:{id:'b',name:'B'},calibration:{id:'c',rules:{z:1,a:2}},components:[{id:'2',weight:.5},{id:'1',weight:.5}]};const a=validationRun(input),b=validationRun({...input,components:[...input.components].reverse()});assert.equal(a.inputHash,b.inputHash);assert.deepEqual(a.findings,b.findings);assert.equal(a.status,'valid');});
test('audit/outbox failure rolls back aggregate, ledger and side effects',async()=>{const r=repository();r.tenants.set('a',{roadmaps:new Map([['r',{id:'r',version:1}]]),units:new Map([['r',[{id:'u1',rank:1}]]]),idem:new Map(),audit:[],outbox:[],input:new Map(),runs:new Map()});const original=r.transaction;r.transaction=async(org,work)=>original.call(r,org,async tx=>{tx.outbox=async()=>{throw new Error('outbox down')};return work(tx)});await assert.rejects(createPlanningAuthoringService(r).reorderUnits({roadmapId:'r',orderedIds:['u1'],ifMatch:'1',idempotencyKey:'x'},ctx()));assert.equal(r.tenants.get('a').roadmaps.get('r').version,1);assert.equal(r.tenants.get('a').audit.length,0);});
