'use strict';
const { randomUUID } = require('node:crypto');

function createPostgresReviewRepository({ pool }) {
  if (!pool?.connect) throw new TypeError('PostgreSQL pool is required');
  function bind(db) {
    const reviewRepository = {
      async loadEvents({ organizationId, planId }) { const result=await db.query('select payload from planning_review_events where logto_organization_id=$1 and plan_id=$2 order by aggregate_version',[organizationId,planId]); return result.rows.map((row)=>row.payload); },
      async append({ organizationId, planId, expectedVersion, event }) {
        await db.query('insert into planning_review_streams(logto_organization_id,plan_id,current_version) values($1,$2,0) on conflict do nothing',[organizationId,planId]);
        const advanced=await db.query('update planning_review_streams set current_version=$3 where logto_organization_id=$1 and plan_id=$2 and current_version=$4',[organizationId,planId,event.aggregateVersion,expectedVersion]);
        if(!advanced.rowCount) throw Object.assign(new Error('review_stream_version_conflict'),{code:'review_stream_version_conflict'});
        await db.query('insert into planning_review_events(event_id,logto_organization_id,plan_id,aggregate_version,event_type,payload,occurred_at) values($1,$2,$3,$4,$5,$6,$7)',[event.eventId,organizationId,planId,event.aggregateVersion,event.type,event,event.occurredAt]);
        await project(event, db);
      },
      async listAssignments({ organizationId, planId, assignmentType, assigneeId, lifecycle }) { const result=await db.query(`select * from planning_review_assignments where logto_organization_id=$1 and plan_id=$2 and ($3::text is null or assignment_type=$3) and ($4::text is null or assignee_id=$4) and ($5::text is null or lifecycle=$5) order by created_at`,[organizationId,planId,assignmentType||null,assigneeId||null,lifecycle||null]); return result.rows; },
      async getReviewRequest({ organizationId, planId, planVersion }) { const result=await db.query('select * from planning_review_requests where logto_organization_id=$1 and plan_id=$2 and ($3::integer is null or plan_version=$3) order by submitted_at desc limit 1',[organizationId,planId,planVersion||null]); return result.rows[0]||null; },
      async listHistory({ organizationId, planId }) { const result=await db.query('select payload from planning_review_events where logto_organization_id=$1 and plan_id=$2 order by aggregate_version',[organizationId,planId]); return result.rows.map((row)=>row.payload); },
      async upsertCollaborator(input) { const result=await db.query(`insert into planning_collaborators(logto_organization_id,plan_id,collaborator_id,access_level,lifecycle,assigned_by,expires_at) values($1,$2,$3,$4,$5,$6,$7) on conflict(logto_organization_id,plan_id,collaborator_id,access_level) do update set lifecycle=excluded.lifecycle,expires_at=excluded.expires_at,updated_at=now() returning *`,[input.organizationId,input.planId,input.collaboratorId,input.accessLevel,input.lifecycle||'active',input.assignedBy,input.expiresAt||null]); return result.rows[0]; },
      async getActivePolicy({ organizationId }) { const result=await db.query('select * from planning_maker_checker_policies where logto_organization_id=$1 and superseded_at is null and effective_at<=now() order by policy_version desc limit 1',[organizationId]); return result.rows[0]||null; },
      async configurePolicy(input) { await db.query('update planning_maker_checker_policies set superseded_at=now() where logto_organization_id=$1 and superseded_at is null',[input.organizationId]); const result=await db.query(`insert into planning_maker_checker_policies(logto_organization_id,policy_version,require_separate_approver,minimum_approvals,configured_by,effective_at,configuration) values($1,$2,$3,$4,$5,$6,$7) returning *`,[input.organizationId,input.policyVersion,input.requireSeparateApprover!==false,input.minimumApprovals||1,input.configuredBy,input.effectiveAt||new Date(),input.configuration||{}]);return result.rows[0]; },
    };
    const idempotencyLedger={ async lookup({organizationId,operation,key}){const r=await db.query('select request_fingerprint,result_json from planning_review_idempotency where logto_organization_id=$1 and operation=$2 and idempotency_key=$3',[organizationId,operation,key]);return r.rows[0]?{fingerprint:r.rows[0].request_fingerprint,result:r.rows[0].result_json}:null;}, async recordSuccess({organizationId,operation,key,fingerprint,result}){await db.query('insert into planning_review_idempotency values($1,$2,$3,$4,$5)',[organizationId,operation,key,fingerprint,result]);} };
    const audit={record:async(e)=>db.query('insert into planning_audit(organization_id,id,plan_id,action,actor_id,details,correlation_id) values($1,$2,$3,$4,$5,$6,$7)',[e.organizationId,randomUUID(),e.targetId,e.action,e.actorId,{decisionId:e.decisionId,eventId:e.eventId},e.correlationId])};
    const outbox={enqueue:async(e)=>db.query(`insert into integration_outbox_events(event_id,event_type,schema_version,logto_organization_id,aggregate_type,aggregate_id,aggregate_version,actor_json,correlation_id,source_json,sensitivity,payload) values($1,$2,'1',$3,'planning.review',$4,$5,$6,$7,$8,'internal',$9)`,[e.eventId,e.type,e.organizationId,e.aggregateId,String(e.aggregateVersion),{type:'user'},e.correlationId,{moduleId:'planning',component:'review-workflow'},e.payload])};
    return { reviewRepository,idempotencyLedger,audit,outbox };
  }
  async function transaction(work){const client=await pool.connect();try{await client.query('begin');const result=await work(bind(client));await client.query('commit');return result;}catch(error){await client.query('rollback');throw error;}finally{client.release();}}
  const root=bind(pool); return {...root,unitOfWork:{transaction}};
}

async function project(event,db){
  if(event.type==='planning.reviewer_assigned.v1'||event.type==='planning.approver_assigned.v1') await db.query(`insert into planning_review_assignments(logto_organization_id,assignment_id,plan_id,assignment_type,assignee_id,plan_version,assigned_by,expires_at) values($1,$2,$3,$4,$5,$6,$7,$8)`,[event.organizationId,event.assignmentId,event.planId,event.assignmentType,event.assigneeId||event.reviewerId,event.planVersion,event.actorId,event.expiresAt||null]);
  if(event.type==='planning.review_submitted.v1') await db.query(`insert into planning_review_requests(logto_organization_id,review_request_id,plan_id,plan_version,author_id,status,stream_version,submitted_at) values($1,$2,$3,$4,$5,'in_review',$6,$7)`,[event.organizationId,event.reviewRequestId,event.planId,event.planVersion,event.authorId,event.aggregateVersion,event.occurredAt]);
  if(event.type==='planning.review_approved.v1'||event.type==='planning.review_rejected.v1'){const status=event.type.endsWith('approved.v1')?'approved':'changes_requested';await db.query('update planning_review_requests set status=$4,stream_version=$5,updated_at=$6 where logto_organization_id=$1 and plan_id=$2 and plan_version=$3',[event.organizationId,event.planId,event.planVersion,status,event.aggregateVersion,event.occurredAt]);await db.query('update planning_review_assignments set lifecycle=\'completed\',updated_at=$3 where logto_organization_id=$1 and assignment_id=$2',[event.organizationId,event.assignmentId,event.occurredAt]);await db.query(`insert into planning_review_decisions(decision_id,logto_organization_id,plan_id,assignment_id,actor_id,decision,plan_version,rationale) values($1,$2,$3,$4,$5,$6,$7,$8)`,[event.decisionId,event.organizationId,event.planId,event.assignmentId,event.actorId,event.decision,event.planVersion,event.rationale||null]);}
  if(event.type==='planning.review_approved.v1') await db.query(`insert into planning_approved_snapshots(logto_organization_id,plan_id,plan_version,snapshot,snapshot_hash,provenance,approved_by,approved_at,policy_version) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[event.organizationId,event.planId,event.planVersion,event.approvedSnapshot,event.snapshotHash,event.provenance,event.actorId,event.occurredAt,event.policyVersion]);
}
module.exports={createPostgresReviewRepository};
