"use strict";
const { explainAuthorization, hashSubject, redact } = require("../authorization/diagnostics");
const GOVERNANCE_OPERATIONS_CONTRACT_VERSION = "2026-07-civitas10-governance-operations-v1";
const REGISTERED_SCREENS = Object.freeze({
  "owner-governance": Object.freeze({ screenId:"owner-governance", canonicalLabel:"Owner Governance Studio", surface:"owner", locked:true, hideable:false, routeId:"owner.organizations.governance" }),
  "tenant-governance": Object.freeze({ screenId:"tenant-governance", canonicalLabel:"Tenant Governance Studio", surface:"tenant", locked:true, hideable:false, routeId:"tenant.settings.governance" }),
  "tenant-documents": Object.freeze({ screenId:"tenant-documents", canonicalLabel:"Documents", surface:"tenant", locked:false, hideable:true, routeId:"tenant.documents" }),
});
const REGISTERED_ACTIONS = Object.freeze(["governance.access.preview","documents.read","documents.create","owner.organizations.read"]);
const nowIso=()=>new Date().toISOString();
const actorId=(req)=>req?.user?.sub||req?.user?.id||"system";
function defaultPolicy(organizationId){return {organizationId,aliasesTenantEditable:false,navigationTenantEditable:true,aliases:[{roleId:"organization_admin",canonicalKey:"organization_admin",displayName:"Organization admin",editableBy:"owner"},{roleId:"organization_member",canonicalKey:"organization_member",displayName:"Organization member",editableBy:"owner"}],visualPreferences:Object.values(REGISTERED_SCREENS).map((s,i)=>({...s,hidden:false,order:(i+1)*10,authorizationEffect:"presentation_only"})),version:"1",updatedAt:nowIso()}}
function createGovernanceOperationsReadModel({ policyPort, auditPort, rateLimitPort }={}){
  if(!policyPort?.get||!policyPort?.save||!auditPort?.write||!auditPort?.list||!rateLimitPort?.consume) throw new Error("governance_operations_ports_required");
  async function getPolicy(org){return await policyPort.get(org)||defaultPolicy(org)}
  async function audit(event){return auditPort.write({...event,before:redact(event.before),after:redact(event.after),contractVersion:GOVERNANCE_OPERATIONS_CONTRACT_VERSION})}
  async function buildAliasesNavigationPolicy(org){return getPolicy(org)}
  function registeredPreference(p){const s=REGISTERED_SCREENS[String(p?.screenId||"")];if(!s)throw Object.assign(new Error("navigation_screen_unknown"),{status:400,code:"navigation_screen_unknown"});if(s.locked&&p.hidden===true)throw Object.assign(new Error("navigation_locked_item_cannot_be_hidden"),{status:400,code:"navigation_locked_item_cannot_be_hidden"});return s}
  async function updateNavigationPreferences({organizationId,preferences=[],actorLogtoUserId,surface="tenant",expectedVersion}={}){const current=await getPolicy(organizationId);if(surface==="tenant"&&!current.navigationTenantEditable)throw Object.assign(new Error("navigation_preferences_owner_managed"),{status:403,code:"navigation_preferences_owner_managed"});const existing=Object.fromEntries(current.visualPreferences.map(p=>[p.screenId,p]));for(const p of preferences){const s=registeredPreference(p),old=existing[s.screenId]||{};existing[s.screenId]={...old,...s,hidden:Boolean(p.hidden),order:Number.isFinite(Number(p.order))?Number(p.order):old.order,authorizationEffect:"presentation_only"}}const saved=await policyPort.save({...current,organizationId,visualPreferences:Object.values(existing).sort((a,b)=>Number(a.order||0)-Number(b.order||0))},{expectedVersion:expectedVersion||current.version});await audit({organizationId,actorLogtoUserId,action:"governance.navigation_preferences.updated",targetType:"navigation_preferences",targetId:organizationId,reason:"presentation_only_no_authorization_change",before:current.visualPreferences,after:saved.visualPreferences});return {contractVersion:GOVERNANCE_OPERATIONS_CONTRACT_VERSION,policy:saved}}
  async function previewAccess({organizationId,surface,body={},actorLogtoUserId,principal={}}){await rateLimitPort.consume({organizationId,actorLogtoUserId,limit:30,windowMs:60000});if(body.previewOnly!==true)throw Object.assign(new Error("access_preview_requires_preview_only"),{status:400});const subjectId=String(body.subjectId||""),actionId=body.actionId?String(body.actionId):undefined,screenId=body.screenId?String(body.screenId):undefined;if(!subjectId||(!actionId&&!screenId))throw Object.assign(new Error("access_preview_subject_and_target_required"),{status:400});if(actionId&&!REGISTERED_ACTIONS.includes(actionId))throw Object.assign(new Error("access_preview_action_unknown"),{status:400});const screen=screenId?REGISTERED_SCREENS[screenId]:null;if(screenId&&!screen)throw Object.assign(new Error("access_preview_screen_unknown"),{status:400});const policy=await getPolicy(organizationId),preference=screenId?policy.visualPreferences.find(i=>i.screenId===screenId):null,allowed=Boolean(subjectId)&&(!screen||screen.surface===surface||surface==="owner"),reason=allowed?(preference?.hidden?"visual_preference_hidden_not_authorization":"allowed"):"surface_mismatch";const diagnostics=await explainAuthorization({surface:surface==="tenant"?"organization":"owner",organizationId,principal:{subject:subjectId,organizationId:surface==="tenant"?organizationId:principal.organizationId,scopes:[actionId||"governance.preview.read"],tokenType:surface==="tenant"?"organization":"global"},permission:actionId||"governance.preview.read",decision:{allowed,reasonCode:reason,policyVersion:policy.version,evaluatedRolePaths:allowed?["preview"]:[]},diagnosticPermissionGranted:true,visual:{screen,action:actionId?{actionId}:null,visualPreference:preference},runtime:{policyVersion:policy.version,visualVersion:policy.version,readModelVersion:GOVERNANCE_OPERATIONS_CONTRACT_VERSION},provenance:{entitlement:{permission:actionId||screenId,ownerCeiling:"preview",tenantActivation:"preview",reasonCodes:[reason]},governance:{readModelVersion:GOVERNANCE_OPERATIONS_CONTRACT_VERSION,policyConfigVersion:policy.version}}});const response={contractVersion:GOVERNANCE_OPERATIONS_CONTRACT_VERSION,generatedAt:nowIso(),organizationId,surface,subjectId:hashSubject(subjectId),actionId,screenId,decision:{allowed,reason,sourceVersions:{policyVersion:policy.version,visualVersion:policy.version,readModelVersion:GOVERNANCE_OPERATIONS_CONTRACT_VERSION}},provenance:diagnostics.provenance,diagnostics,mutated:false};await audit({organizationId,actorLogtoUserId,action:"governance.access_preview.simulated",targetType:actionId?"action":"screen",targetId:actionId||screenId,result:allowed?"allowed":"denied",reason,after:response});return response}
  async function listGovernanceAuditEvents({organizationId,limit=50}={}){const events=await auditPort.list({organizationId,limit});return events.map(e=>({...e,actorId:e.actorLogtoUserId?hashSubject(e.actorLogtoUserId):"system",actorLogtoUserId:undefined}))}
  return {buildAliasesNavigationPolicy,updateNavigationPreferences,previewAccess,listGovernanceAuditEvents,audit};
}
module.exports={GOVERNANCE_OPERATIONS_CONTRACT_VERSION,createGovernanceOperationsReadModel,actorId};
