"use strict";
const crypto = require("node:crypto");
const { permissionsByName, rolePermissionAssignments } = require("../../core/authz");
const { createEntitlementService } = require("../authorization/entitlements/entitlementService");
function hashSubject(value) { return value ? `sub_${crypto.createHash("sha256").update(String(value)).digest("hex").slice(0, 12)}` : null; }
function roleId(role = {}) { return role.id || role.organizationRoleId || role.roleId || null; }
function roleName(role = {}) { return role.name || role.nameCache || role.key || null; }
function canonicalRoleKey(name = "") { const raw = String(name || "").trim(); if (raw.startsWith("organization_") || raw === "owner_global") return raw; return `organization_${raw.replace(/-org$/i, "").replace(/[^a-z0-9]+/gi, "_").replace(/^_+|_+$/g, "").toLowerCase()}`; }
function displayName(name = "") { return String(name || "").replace(/-org$/i, "").replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function canonicalOrganizationPermissions() { return Object.values(permissionsByName).filter((permission) => permission.surface === "organization" && permission.identityProvisioning === "provisionable" && permission.presentation).sort((a,b) => a.presentation.groupOrder-b.presentation.groupOrder || a.presentation.order-b.presentation.order); }
function createGovernanceRolesService({ entitlementRepository } = {}) {
  if (!entitlementRepository || entitlementRepository.kind !== "postgres") throw new Error("postgres_entitlement_repository_required");
  async function listRoleView({ roles, organizationId }) { const limits = await entitlementRepository.listLimits({ organizationId }); return roles.flatMap((role) => { const id=roleId(role); const key=canonicalRoleKey(roleName(role)); if(!id || !key.startsWith("organization_")) return []; const potential=rolePermissionAssignments[key] || []; return [{ id, canonicalKey:key, displayName: displayName(roleName(role)), assignedMemberCount: 0, permissionCount: potential.length, enabledPermissionCount: limits.filter((limit)=>limit.logtoRoleId===id&&limit.allowed).length }]; }); }
  async function buildPermissionRows({ organizationId, roles, surface }) { const [limits, activations, policyVersion] = await Promise.all([entitlementRepository.listLimits({organizationId}), entitlementRepository.listActivations({organizationId}), entitlementRepository.getPolicyVersion(organizationId)]); const limitKey=(role,permission)=>limits.find((row)=>row.logtoRoleId===role&&row.permissionKey===permission); const activationKey=(role,permission)=>activations.find((row)=>row.logtoRoleId===role&&row.permissionKey===permission); return roles.flatMap((role)=>{ const id=roleId(role); const key=canonicalRoleKey(roleName(role)); if(!id || !key.startsWith("organization_")) return []; const potential=new Set(rolePermissionAssignments[key] || []); return canonicalOrganizationPermissions().filter((permission)=>potential.has(permission.name)).map((permission)=>{ const limit=limitKey(id,permission.name); const activation=activationKey(id,permission.name); const rolePotential=potential.has(permission.name); const identityProvisioned=permission.identityProvisioning==="provisionable"; const runtimeAvailable=permission.status==="active"&&permission.observedImplementation==="active"; const organizationAvailable=runtimeAvailable; const ownerAllowed=limit?.allowed===true; const tenantEnabled=activation?.enabled===true; const locked=limit?.locked===true; const canChange=surface==="owner" ? rolePotential&&identityProvisioned : rolePotential&&identityProvisioned&&ownerAllowed&&!locked; const controlState=canChange?"editable":!rolePotential?"blocked_by_role":locked?"locked":!ownerAllowed?"blocked_by_ceiling":"operation_unavailable"; return { permissionId:permission.name, roleId:id, ...permission.presentation, rolePotential, identityProvisioned, runtimeAvailable, organizationAvailable, enabled:surface==="owner"?ownerAllowed:tenantEnabled, canChange, controlState, reasonCode:canChange?null:controlState, ownerAllowed, tenantEnabled, effective:runtimeAvailable&&organizationAvailable&&ownerAllowed&&tenantEnabled, policyVersion:String(policyVersion) }; }); }); }
  async function buildSlice({ organizationId, roles=[], members=[], memberRolesByUserId=new Map(), surface="owner" }) { return { contractVersion:"2026-08-civitas10-permission-policy-v1", policyVersion:String(await entitlementRepository.getPolicyVersion(organizationId)), roles:await listRoleView({roles,organizationId}), members:members.map((user)=>({id:user.id||user.userId,display:hashSubject(user.id||user.userId),roleIds:(memberRolesByUserId.get(user.id||user.userId)||[]).map(roleId).filter(Boolean)})), permissionMatrix:await buildPermissionRows({organizationId,roles,surface}) }; }
  const mutations=(roleIdToName)=>createEntitlementService({repository:entitlementRepository,roleIdToName});
  return { buildRolesGovernanceSlice:buildSlice, updateOwnerCeilings:(input)=>mutations(input.roleIdToName).upsertOwnerLimits(input), updateTenantActivations:(input)=>mutations(input.roleIdToName).upsertTenantActivations(input) };
}
function roleMapFromRoles(roles=[]) { return Object.fromEntries(roles.map((role)=>[roleId(role),canonicalRoleKey(roleName(role))]).filter(([id])=>id)); }
module.exports={createGovernanceRolesService,roleMapFromRoles,canonicalRoleKey};
