import { useEffect, useMemo, useState } from "react";
import { EmptyState, FilterBar, PendingChangesBar, PermissionGroupAccordion, RoleSelector, SectionCard, type PendingChangesState } from "../../../../shared/ui";
import { ApiRequestError } from "../../../../api/base";
import type { GovernancePermissionMatrixRow, GovernanceRoleSummary, GovernanceVersionSummary } from "../../contracts";
import { buildPermissionPolicyView } from "./permission-policy-view-model";
type PendingChange={permission:string;enabled:boolean}; type PermissionMutationInput={roleId:string;expectedPolicyVersion?:string;changes:PendingChange[];reason:string};
export const PermissionMatrixModule=({organizationId,rows,roles=[],versions,onSaveOwnerCeilings,onSaveTenantActivations,surface,onReload}:{organizationId:string;rows:readonly GovernancePermissionMatrixRow[];roles?:readonly GovernanceRoleSummary[];versions?:GovernanceVersionSummary;surface:"owner"|"tenant";onSaveOwnerCeilings?:(input:PermissionMutationInput)=>Promise<unknown>;onSaveTenantActivations?:(input:PermissionMutationInput)=>Promise<unknown>;onReload?:()=>Promise<void>})=>{
  void organizationId; const queryRole=()=>new URLSearchParams(globalThis.location?.search||"").get("role")||""; const options=useMemo(()=>roles.map((role)=>({canonicalRoleId:role.id,alias:role.displayName})),[roles]); const [roleId,setRoleId]=useState(()=>queryRole()||options[0]?.canonicalRoleId||""); const [search,setSearch]=useState(""); const [expanded,setExpanded]=useState<Record<string,boolean>>({}); const [pending,setPending]=useState<Record<string,boolean>>({}); const [state,setState]=useState<PendingChangesState>("clean"); const [message,setMessage]=useState(""); const effectiveRole=roleId||options[0]?.canonicalRoleId||""; const roleRows=rows.filter((row)=>row.roleId===effectiveRole); const groups=buildPermissionPolicyView(rows,effectiveRole,pending,search,surface); const changes=Object.entries(pending).flatMap(([permission,enabled])=>{const row=roleRows.find((item)=>item.permissionId===permission);return row&&(surface==="owner"?row.ownerAllowed:row.tenantEnabled)!==enabled?[{permission,enabled}]:[]}); const roleLabel=options.find((role)=>role.canonicalRoleId===effectiveRole)?.alias||"Organization role"; const enabled=roleRows.filter((row)=>pending[row.permissionId]??(surface==="owner"?row.ownerAllowed:row.tenantEnabled)).length;
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(changes.length){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[changes.length]);
  const selectRole=(next:string)=>{if(changes.length&&!globalThis.confirm("Discard pending permission changes and switch roles?"))return;setPending({});setState("clean");setRoleId(next);const params=new URLSearchParams(globalThis.location?.search||"");params.set("role",next);globalThis.history?.replaceState(null,"",`${globalThis.location?.pathname}?${params}`);};
  const setOne=(permission:string,value:boolean)=>setPending((current)=>({...current,[permission]:value})); const setGroup=(items:(typeof groups)[number]["rows"],value:boolean)=>setPending((current)=>{const next={...current};for(const row of items)if(row.canChange)next[row.permissionId]=value;return next;});
  const save=async()=>{const writer=surface==="owner"?onSaveOwnerCeilings:onSaveTenantActivations;if(!writer||!changes.length)return;setState("saving");setMessage("Saving changes…");try{await writer({roleId:effectiveRole,expectedPolicyVersion:versions?.policyVersion,changes,reason:surface==="owner"?"owner_ceiling_update":"tenant_activation_update"});setPending({});setState("saved");setMessage("Permissions saved.");}catch(error){if(error instanceof ApiRequestError&&error.status===409){setState("conflict");setMessage("This configuration changed in another session. Reload before saving again.");}else{setState("error");setMessage("Changes could not be saved. Please try again.");}}};
  if(!options.length)return <SectionCard title="Roles & Permissions" description="Manage the permissions available to each role."><EmptyState message="No roles are available for this organization."/></SectionCard>;
  return <SectionCard title="Roles & Permissions" description="Manage the permissions available to each role."><div className="civitas-workspace-stack"><RoleSelector id="governance-role-selector" label="Role" value={effectiveRole} roles={options} onChange={selectRole}/><p className="text-sm font-semibold">{enabled} of {roleRows.length} permissions enabled</p><FilterBar searchLabel="Search permissions" searchValue={search} onSearchChange={setSearch} onReset={()=>setSearch("")}/>{!roleRows.length?<EmptyState message="No target-potential permissions are available for this role."/>:!groups.length?<EmptyState message="No permissions match your search."/>:groups.map((group)=>{const all=buildPermissionPolicyView(rows,effectiveRole,pending,"",surface).find((item)=>item.key===group.key)?.rows||group.rows;return <PermissionGroupAccordion key={group.key} domain={group.label} rows={group.rows} expanded={expanded[group.key]??false} activeCount={all.filter((row)=>row.checked).length} totalCount={all.length} roleLabel={roleLabel} onExpandedChange={(value)=>setExpanded((current)=>({...current,[group.key]:value}))} onTogglePermission={setOne} onToggleGroup={(value)=>setGroup(all,value)}/>;})}<PendingChangesBar count={changes.length} state={changes.length?state:"clean"} message={message} onDiscard={()=>{setPending({});setState("clean");setMessage("");}} onSave={()=>void save()} onReload={onReload?()=>void onReload().then(()=>{setState("pending");setMessage("");}):undefined}/></div></SectionCard>;
};
