'use strict'
const crypto=require('crypto')
const EFFECTS=new Set(['read','write','export','bulk','delete','impersonate'])
function createInMemoryDelegationContextRepository(){const rows=new Map();return{async insert(row){rows.set(row.decisionId,{...row});return{...row}},async get(id){const row=rows.get(id);return row&&{...row}},async revoke(id,revokedAt){const row=rows.get(id);if(!row)return null;rows.set(id,{...row,revokedAt,status:'revoked'});return{...rows.get(id)}}}}
function createDelegationContextService({repository,auditPort,invalidationPort,now=()=>new Date(),maxTtlMs=15*60*1000}={}){if(!repository||!auditPort?.record)throw new Error('delegation context repository and audit are required');if(repository.durable&&!invalidationPort?.publish)throw new Error('durable delegation requires distributed invalidation');return Object.freeze({
 async issue(input){const issuedAt=now();const expiresAt=new Date(input.expiresAt);if(!input.actorSubject||!input.actorSurface||!input.clientId||!input.targetOrganizationId||!input.reason||!Number.isFinite(expiresAt.getTime())||expiresAt<=issuedAt||expiresAt-issuedAt>maxTtlMs)throw Object.assign(new Error('delegation_invalid'),{code:'delegation_invalid'});const allowed=[...new Set(input.allowedCapabilities||[])];const denied=[...new Set(input.deniedEffects||['write','export','bulk','delete'])];if(denied.some(effect=>!EFFECTS.has(effect)))throw Object.assign(new Error('delegation_invalid'),{code:'delegation_invalid'});const row={actorSubject:input.actorSubject,actorSurface:input.actorSurface,clientId:input.clientId,targetOrganizationId:input.targetOrganizationId,reason:input.reason,issuedAt:issuedAt.toISOString(),expiresAt:expiresAt.toISOString(),allowedCapabilities:allowed,deniedEffects:denied,confirmationPolicy:input.confirmationPolicy||'confirm-sensitive',decisionId:input.decisionId||`delegation_${crypto.randomUUID()}`,status:'active',revokedAt:null};await repository.insert(row);if(invalidationPort?.publish)await invalidationPort.publish({eventType:'authorization.delegation.issued',organizationId:row.targetOrganizationId,decisionId:row.decisionId});await auditPort.record({action:'authorization.delegation.issued',actorSubject:row.actorSubject,targetOrganizationId:row.targetOrganizationId,decisionId:row.decisionId,reason:row.reason});return row},
 async authorize({decisionId,actorSubject,targetOrganizationId,capability,effect,confirmed=false}){const row=await repository.get(decisionId);if(!row||row.status!=='active'||row.actorSubject!==actorSubject||row.targetOrganizationId!==targetOrganizationId)throw Object.assign(new Error('delegation_invalid'),{code:'delegation_invalid'});if(new Date(row.expiresAt)<=now())throw Object.assign(new Error('delegation_expired'),{code:'delegation_expired'});if(!row.allowedCapabilities.includes(capability)||row.deniedEffects.includes(effect)||(['write','export','bulk','delete'].includes(effect)&&row.confirmationPolicy==='confirm-sensitive'&&!confirmed))throw Object.assign(new Error('delegation_effect_denied'),{code:'delegation_effect_denied'});await auditPort.record({action:'authorization.delegation.used',actorSubject,targetOrganizationId,decisionId,capability,effect});return row},
 async revoke({decisionId,actorSubject,reason}){const row=await repository.revoke(decisionId,now().toISOString());if(!row)throw Object.assign(new Error('delegation_invalid'),{code:'delegation_invalid'});if(invalidationPort?.publish)await invalidationPort.publish({eventType:'authorization.delegation.revoked',organizationId:row.targetOrganizationId,decisionId});await auditPort.record({action:'authorization.delegation.revoked',actorSubject,targetOrganizationId:row.targetOrganizationId,decisionId,reason});return row},
})}
module.exports={createDelegationContextService,createInMemoryDelegationContextRepository}
