"use strict";
const { getPool } = require("../../lib/db");
function mapLimit(row) { return row && { id: row.id, logtoOrganizationId: row.logto_organization_id, logtoRoleId: row.logto_role_id, roleNameCache: row.role_name_cache, permissionKey: row.permission_key, allowed: row.allowed, locked: row.locked, policyVersion: Number(row.policy_version), setByLogtoUserId: row.set_by_logto_user_id, reason: row.reason, createdAt: row.created_at, updatedAt: row.updated_at }; }
function mapActivation(row) { return row && { id: row.id, logtoOrganizationId: row.logto_organization_id, logtoRoleId: row.logto_role_id, roleNameCache: row.role_name_cache, permissionKey: row.permission_key, entitlementLimitId: row.entitlement_limit_id, enabled: row.enabled, policyVersion: Number(row.policy_version), setByLogtoUserId: row.set_by_logto_user_id, reason: row.reason, createdAt: row.created_at, updatedAt: row.updated_at }; }
function createPostgresEntitlementRepository({ pool = getPool(), client = pool } = {}) {
  const query = (text, values) => client.query(text, values);
  return {
    kind: "postgres",
    async getPolicyVersion(organizationId, { lock = false } = {}) { const result = await query(`insert into authorization_policy_versions(logto_organization_id,version) values($1,1) on conflict(logto_organization_id) do update set logto_organization_id=excluded.logto_organization_id returning version`, [organizationId]); if (lock) { const locked = await query(`select version from authorization_policy_versions where logto_organization_id=$1 for update`, [organizationId]); return Number(locked.rows[0].version); } return Number(result.rows[0].version); },
    async setPolicyVersion(organizationId, version) { const result = await query(`insert into authorization_policy_versions(logto_organization_id,version,updated_at) values($1,$2,now()) on conflict(logto_organization_id) do update set version=excluded.version,updated_at=now() returning version`, [organizationId, version]); return Number(result.rows[0].version); },
    async incrementPolicyVersion(organizationId, actorLogtoUserId, reason) { const result = await query(`insert into authorization_policy_versions(logto_organization_id,version,updated_by_logto_user_id,reason) values($1,2,$2,$3) on conflict(logto_organization_id) do update set version=authorization_policy_versions.version+1,updated_at=now(),updated_by_logto_user_id=$2,reason=$3 returning version`, [organizationId, actorLogtoUserId || null, reason || "permission_policy_update"]); return Number(result.rows[0].version); },
    async getLimit({ organizationId, logtoRoleId, permission }) { return mapLimit((await query(`select * from org_role_entitlement_limits where logto_organization_id=$1 and logto_role_id=$2 and permission_key=$3`, [organizationId, logtoRoleId, permission])).rows[0]); },
    async getActivation({ organizationId, logtoRoleId, permission }) { return mapActivation((await query(`select * from org_role_permission_activations where logto_organization_id=$1 and logto_role_id=$2 and permission_key=$3`, [organizationId, logtoRoleId, permission])).rows[0]); },
    async listLimits({ organizationId }) { return (await query(`select * from org_role_entitlement_limits where logto_organization_id=$1`, [organizationId])).rows.map(mapLimit); },
    async listActivations({ organizationId }) { return (await query(`select * from org_role_permission_activations where logto_organization_id=$1`, [organizationId])).rows.map(mapActivation); },
    async upsertLimit(row) { return mapLimit((await query(`insert into org_role_entitlement_limits(logto_organization_id,logto_role_id,role_name_cache,permission_key,allowed,locked,policy_version,set_by_logto_user_id,reason) values($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(logto_organization_id,logto_role_id,permission_key) do update set allowed=excluded.allowed,locked=excluded.locked,policy_version=excluded.policy_version,set_by_logto_user_id=excluded.set_by_logto_user_id,reason=excluded.reason,updated_at=now() returning *`, [row.logtoOrganizationId,row.logtoRoleId,row.roleNameCache||null,row.permissionKey,!!row.allowed,!!row.locked,row.policyVersion,row.setByLogtoUserId,row.reason||"permission_policy_update"])).rows[0]); },
    async upsertActivation(row) { return mapActivation((await query(`insert into org_role_permission_activations(logto_organization_id,logto_role_id,role_name_cache,permission_key,entitlement_limit_id,enabled,policy_version,set_by_logto_user_id,reason) values($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(logto_organization_id,logto_role_id,permission_key) do update set entitlement_limit_id=excluded.entitlement_limit_id,enabled=excluded.enabled,policy_version=excluded.policy_version,set_by_logto_user_id=excluded.set_by_logto_user_id,reason=excluded.reason,updated_at=now() returning *`, [row.logtoOrganizationId,row.logtoRoleId,row.roleNameCache||null,row.permissionKey,row.entitlementLimitId,!!row.enabled,row.policyVersion,row.setByLogtoUserId,row.reason||null])).rows[0]); },
    async disableActivation({ organizationId, logtoRoleId, permission, policyVersion }) { return mapActivation((await query(`update org_role_permission_activations set enabled=false,policy_version=$4,updated_at=now() where logto_organization_id=$1 and logto_role_id=$2 and permission_key=$3 returning *`, [organizationId,logtoRoleId,permission,policyVersion])).rows[0]); },
    async enqueueOutbox(event) { return (await query(`insert into authorization_outbox_events(event_type,aggregate_type,aggregate_id,event_version,logto_organization_id,subject_logto_user_id,payload) values($1,'permission_policy',$2,$3,$2,$4,$5::jsonb) returning *`, [event.eventType,event.organizationId,String(event.policyVersion),event.actorLogtoUserId||null,JSON.stringify(event)])).rows[0]; },
    async audit(event) { return (await query(`insert into audit_logs(logto_organization_id,actor_logto_user_id,actor_type,action,target_type,target_id,result,metadata) values($1,$2,'user',$3,'permission',$4,'success',$5::jsonb) returning *`, [event.organizationId,event.actorLogtoUserId||null,event.action,event.permission||event.roleId||null,JSON.stringify(event)])).rows[0]; },
    async transaction(work) { if (client !== pool) return work(this); const tx = await pool.connect(); try { await tx.query("begin"); const result = await work(createPostgresEntitlementRepository({ pool, client: tx })); await tx.query("commit"); return result; } catch (error) { await tx.query("rollback"); throw error; } finally { tx.release(); } },
  };
}
module.exports = { createPostgresEntitlementRepository };
