"use strict";
const crypto=require("node:crypto");
const { CANONICAL_DIMENSION_IDS } = require("../../backend/taxonomy/taxonomyDimensionRegistry");
const { getSelector, selectorRegistry } = require("./selector-registry.cjs");
const { operatorRegistry, outcomeRegistry, authorityRegistry } = require("./registries.cjs");
const { MAPPING_REASON_CODES } = require("./reason-codes.cjs");
const TRUTH=Object.freeze({MATCH:"MATCH",NO_MATCH:"NO_MATCH",UNRESOLVED:"UNRESOLVED",EXCLUDED:"EXCLUDED"});
const OUTCOMES=Object.freeze({MATCHED:"MATCH",NOT_MATCHED:"NO_MATCH",AMBIGUOUS:"UNRESOLVED",INCOMPATIBLE:"EVALUATION_ERROR"});
function canonicalize(v){if(Array.isArray(v))return v.map(canonicalize); if(v&&typeof v==="object")return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonicalize(v[k])])); return v;}
function hash(v){return crypto.createHash("sha256").update(JSON.stringify(canonicalize(v))).digest("hex");}
function readPath(object,path){return String(path||"").split(".").filter(Boolean).reduce((value,key)=>value==null?undefined:value[key],object)}
function actualFor(selector, condition, facts){ if(condition.valuePath)return readPath(facts,condition.valuePath); if(selector.key.includes("claim"))return readPath(facts,`claims.${condition.claim||condition.attribute||condition.key}`); if(selector.key.includes("group"))return facts.externalGroupIds||facts.groups; if(selector.key==="source.connection")return facts.sourceConnectionId; if(selector.key==="canonical.mapping_state")return facts.mappingState; return readPath(facts,condition.attribute||selector.key.replace(/\./g,"_"));}
function operandMalformed(operator, condition){ if(["in","not_in","contains_any","contains_all","between"].includes(operator)&&!Array.isArray(condition.values))return true; if(!["exists","not_exists"].includes(operator)&&condition.value===undefined&&condition.values===undefined)return true; return false;}
function compare(operator, actual, condition){const arr=Array.isArray(actual)?actual.map(String):[String(actual)]; const val=condition.value==null?condition.value:String(condition.value); const vals=(condition.values||[]).map(String); if(operator==="exists")return actual!==undefined&&actual!==null&&!(Array.isArray(actual)&&actual.length===0); if(operator==="not_exists")return actual===undefined||actual===null||(Array.isArray(actual)&&actual.length===0); if(actual===undefined||actual===null||(Array.isArray(actual)&&actual.length===0))return null; if(operator==="equals")return arr.includes(val); if(operator==="not_equals")return !arr.includes(val); if(operator==="in")return arr.some(x=>vals.includes(x)); if(operator==="not_in")return !arr.some(x=>vals.includes(x)); if(operator==="contains")return arr.includes(val); if(operator==="contains_any")return vals.some(v=>arr.includes(v)); if(operator==="contains_all")return vals.every(v=>arr.includes(v)); if(operator==="starts_with")return arr.some(x=>x.startsWith(val)); if(operator==="ends_with")return arr.some(x=>x.endsWith(val)); if(operator==="before")return new Date(arr[0])<new Date(val); if(operator==="after")return new Date(arr[0])>new Date(val); if(operator==="between"){const d=new Date(arr[0]); return d>=new Date(vals[0])&&d<=new Date(vals[1]);} if(operator==="is_descendant_of")return arr.includes(val); return null;}
function evaluateCondition(condition,facts,ctx={}){const selectorKey=condition.selectorKey||condition.selectorId; const operatorKey=condition.operatorKey||condition.operator; const selector=getSelector(selectorKey); const evaluatedAt=ctx.evaluatedAt||"1970-01-01T00:00:00.000Z"; const base={conditionId:condition.conditionId||condition.id||selectorKey,selectorKey,operatorKey,sourceConnectionId:ctx.sourceConnectionId||facts.sourceConnectionId||null,sourceSnapshotId:ctx.sourceSnapshotId||facts.sourceSnapshotId||null,sourceSnapshotVersion:ctx.sourceSnapshotVersion||facts.sourceSnapshotVersion||null,retryable:false,safeEvidenceRefs:[],evaluatedAt,resolverState:"resolved"}; if(!selector)return {...base,result:TRUTH.UNRESOLVED,reasonCode:MAPPING_REASON_CODES.SELECTOR_UNKNOWN,retryable:false,resolverState:"selector_unknown"}; if(!operatorRegistry.get(operatorKey)||!selector.allowedOperators.includes(operatorKey))return {...base,result:TRUTH.UNRESOLVED,reasonCode:MAPPING_REASON_CODES.UNSUPPORTED_OPERATOR,resolverState:"operator_incompatible"}; if(operandMalformed(operatorKey,condition))return {...base,result:TRUTH.UNRESOLVED,reasonCode:"mapping_operand_malformed",resolverState:"operand_malformed"}; const actual=actualFor(selector,condition,facts); const matched=compare(operatorKey,actual,condition); if(matched===null)return {...base,result:TRUTH.UNRESOLVED,reasonCode:MAPPING_REASON_CODES.INCOMPLETE_FACTS,retryable:true,resolverState:"missing"}; return {...base,result:matched?TRUTH.MATCH:TRUTH.NO_MATCH,reasonCode:matched?MAPPING_REASON_CODES.MATCHED:MAPPING_REASON_CODES.NOT_MATCHED};}
function evalInclude(conditions,facts,ctx){if(!conditions.length)return {result:"INVALID",reasonCode:"mapping_include_empty",conditions:[]}; const results=conditions.map(c=>evaluateCondition(c,facts,ctx)); if(results.some(r=>r.result===TRUTH.MATCH))return {result:TRUTH.MATCH,conditions:results}; if(results.some(r=>r.result===TRUTH.UNRESOLVED))return {result:TRUTH.UNRESOLVED,conditions:results}; return {result:TRUTH.NO_MATCH,conditions:results};}
function evalRequire(conditions,facts,ctx){const results=conditions.map(c=>evaluateCondition(c,facts,ctx)); if(results.some(r=>r.result===TRUTH.NO_MATCH))return {result:TRUTH.NO_MATCH,conditions:results}; if(results.some(r=>r.result===TRUTH.UNRESOLVED))return {result:TRUTH.UNRESOLVED,conditions:results}; return {result:TRUTH.MATCH,conditions:results};}
function evalExclude(conditions,facts,ctx){const results=conditions.map(c=>evaluateCondition(c,facts,ctx)); if(results.some(r=>r.result===TRUTH.MATCH))return {result:TRUTH.EXCLUDED,conditions:results}; if(results.some(r=>r.result===TRUTH.UNRESOLVED))return {result:TRUTH.UNRESOLVED,conditions:results}; return {result:TRUTH.NO_MATCH,conditions:results};}
function validateOutcome(outcome){ if(Object.keys(outcome||{}).some(k=>/role|permission|membership|ceiling|activation|authorization_scope_assignment|organizationWide|token/i.test(k)))return {ok:false,reasonCode:MAPPING_REASON_CODES.UNSAFE_GRANT_FIELD}; if(!outcomeRegistry.get(outcome?.type))return {ok:false,reasonCode:"mapping_outcome_invalid"}; if(outcome.dimensionId&&!CANONICAL_DIMENSION_IDS.includes(outcome.dimensionId))return {ok:false,reasonCode:MAPPING_REASON_CODES.DIMENSION_UNKNOWN}; return {ok:true};}
function evaluateRule(rule,context={}){const facts=context.facts||{}; const ctx={...context,evaluatedAt:context.evaluatedAt||"1970-01-01T00:00:00.000Z"}; const exclude=evalExclude(rule.exclude||[],facts,ctx); const require=evalRequire(rule.require||[],facts,ctx); const include=evalInclude(rule.include||rule.conditions||[],facts,ctx); const groups={exclude,require,include}; if(exclude.result===TRUTH.EXCLUDED)return {ruleId:rule.ruleId,result:TRUTH.NO_MATCH,reasonCode:"mapping_excluded",groups}; if([exclude.result,require.result,include.result].includes(TRUTH.UNRESOLVED))return {ruleId:rule.ruleId,result:TRUTH.UNRESOLVED,reasonCode:MAPPING_REASON_CODES.INCOMPLETE_FACTS,groups}; if(include.result==="INVALID")return {ruleId:rule.ruleId,result:TRUTH.UNRESOLVED,reasonCode:include.reasonCode,groups}; if(require.result===TRUTH.MATCH&&include.result===TRUTH.MATCH){const outcome=rule.outcome||{type:"map_to_existing_canonical_value",...(rule.target||{})}; const valid=validateOutcome(outcome); if(!valid.ok)return {ruleId:rule.ruleId,result:TRUTH.UNRESOLVED,reasonCode:valid.reasonCode,groups}; return {ruleId:rule.ruleId,result:TRUTH.MATCH,reasonCode:MAPPING_REASON_CODES.MATCHED,outcome,authorityKey:rule.authorityKey||rule.authority||"organization_mapping_policy",specificity:(rule.include||rule.conditions||[]).length+(rule.require||[]).length,groups};} return {ruleId:rule.ruleId,result:TRUTH.NO_MATCH,reasonCode:MAPPING_REASON_CODES.NOT_MATCHED,groups};}
function authorityRank(r){return authorityRegistry.get(r.authorityKey)?.rank??-1;}
function selectWinner(matches){const sorted=[...matches].sort((a,b)=>authorityRank(b)-authorityRank(a)||b.specificity-a.specificity); const [winner,runnerUp]=sorted; if(runnerUp&&authorityRank(winner)===authorityRank(runnerUp)&&winner.specificity===runnerUp.specificity&&JSON.stringify(winner.outcome)!==JSON.stringify(runnerUp.outcome))return {finalResult:TRUTH.UNRESOLVED,reasonCode:"mapping_outcome_conflict",conflicts:[winner.ruleId,runnerUp.ruleId]}; return {finalResult:TRUTH.MATCH,reasonCode:MAPPING_REASON_CODES.MATCHED,candidate:winner};}
function evaluateMappingPolicy(policy,context={}){if(context.facts?.tenantId&&context.organizationId&&context.facts.tenantId!==context.organizationId)return Object.freeze({outcome:TRUTH.UNRESOLVED,finalResult:TRUTH.UNRESOLVED,reasonCode:MAPPING_REASON_CODES.TENANT_MISMATCH,candidates:Object.freeze([]),trace:Object.freeze({finalResult:TRUTH.UNRESOLVED,terminalReasonCode:MAPPING_REASON_CODES.TENANT_MISMATCH,evaluationHash:"unresolved_tenant_mismatch"}),evaluationHash:"unresolved_tenant_mismatch"}); if(context.facts&&context.facts.claimsComplete===false)return Object.freeze({outcome:TRUTH.UNRESOLVED,finalResult:TRUTH.UNRESOLVED,reasonCode:MAPPING_REASON_CODES.INCOMPLETE_FACTS,candidates:Object.freeze([]),trace:Object.freeze({finalResult:TRUTH.UNRESOLVED,terminalReasonCode:MAPPING_REASON_CODES.INCOMPLETE_FACTS,evaluationHash:"unresolved_incomplete"}),evaluationHash:"unresolved_incomplete"}); const evaluationId=context.evaluationId||"eval_deterministic"; const ruleResults=(policy.rules||[]).map(r=>evaluateRule(r,context)); const matches=ruleResults.filter(r=>r.result===TRUTH.MATCH); let final=ruleResults.some(r=>r.reasonCode==="mapping_excluded")?{finalResult:TRUTH.NO_MATCH,reasonCode:"mapping_excluded"}:ruleResults.some(r=>r.result===TRUTH.UNRESOLVED)?{finalResult:TRUTH.UNRESOLVED,reasonCode:ruleResults.find(r=>r.result===TRUTH.UNRESOLVED).reasonCode}:matches.length?selectWinner(matches):{finalResult:TRUTH.NO_MATCH,reasonCode:MAPPING_REASON_CODES.NOT_MATCHED}; const trace={evaluationId,organizationId:context.organizationId,registryVersions:{selector:selectorRegistry.version},registryHashes:{selector:selectorRegistry.hash},ruleResults,finalResult:final.finalResult,terminalReasonCode:final.reasonCode}; const evaluationHash=hash(trace); return Object.freeze({...final,outcome:final.finalResult,reasonCode:final.reasonCode,candidates:Object.freeze(matches),trace:Object.freeze({...trace,evaluationHash}),evaluationHash});}
module.exports={TRUTH,OUTCOMES,evaluateCondition,evaluateRule,evaluateMappingPolicy,selectWinner,MAPPING_REASON_CODES,evalInclude,evalRequire,evalExclude};
