"use strict";
const { defineRegistry } = require("./registry-utils.cjs");
const operatorRegistry=defineRegistry({version:"2026-08-org-mapping-operators-v1",entries:["equals","not_equals","in","not_in","contains","contains_any","contains_all","starts_with","ends_with","exists","not_exists","before","after","between","is_descendant_of"].map(key=>({key,status:"active"}))});
const evidenceClassificationRegistry=defineRegistry({version:"2026-08-org-mapping-evidence-v1",entries:["public_organization_fact","internal_canonical_identifier","source_object_display_name","stable_external_object_identifier","sensitive_user_attribute","user_identifier","restricted_group_name","restricted_group_count","correlatable_hash","connector_diagnostics","secret_token_assertion_material"].map(key=>({key,status:"active",audiences:key.includes("sensitive")||key.includes("secret")?["org.orgmodel_evidence.read"]:["org.orgmodel.read"],ui:key.includes("secret")?"never":"redacted",audit:"safe_reference",log:"safe_reference",export:"redacted",redaction:key.includes("secret")?"omit":"classify",retention:"bounded"}))});
const outcomeRegistry=defineRegistry({version:"2026-08-org-mapping-outcomes-v1",entries:["map_to_existing_canonical_value","propose_organization_owned_value","propose_hierarchy_relationship","propose_applicability_relationship","attach_reusable_facet","attach_temporal_context","attach_cross_cutting_overlay","ignore_source_fact_with_reason","mark_unresolved","require_manual_review"].map(key=>({key,status:"active",grantsAccess:false}))});
const authorityRegistry=defineRegistry({version:"2026-08-org-mapping-authority-v1",entries:["platform_connector_contract","connection_mapping_policy","organization_mapping_policy","explicit_reviewed_mapping"].map((key,rank)=>({key,status:"active",rank}))});
const relationshipRegistry=defineRegistry({version:"2026-08-org-mapping-relationships-v1",entries:["parent_of","reports_to","applies_to","coordinates","supports","operates_in","classified_by"].map(key=>({key,status:"active",hierarchy:key==="parent_of"}))});
const structureBehaviorRegistry=defineRegistry({version:"2026-08-org-mapping-structure-behaviors-v1",entries:["hierarchy_axis","cross_cutting_overlay","reusable_facet","operating_context","applicability"].map(key=>({key,status:"active"}))});
const reconciliationImpactRegistry=defineRegistry({version:"2026-08-org-mapping-reconciliation-impact-v1",entries:["no_effect","revalidation_required","narrowing_possible","broadening_possible","assignment_invalid","source_relationship_stale","manual_review_required"].map(key=>({key,status:"active"}))});
function registryState(){return Object.freeze(Object.fromEntries(Object.entries({operatorRegistry,evidenceClassificationRegistry,outcomeRegistry,authorityRegistry,relationshipRegistry,structureBehaviorRegistry,reconciliationImpactRegistry}).map(([key,registry])=>[key,{version:registry.version,hash:registry.hash}])));}
module.exports={operatorRegistry,evidenceClassificationRegistry,outcomeRegistry,authorityRegistry,relationshipRegistry,structureBehaviorRegistry,reconciliationImpactRegistry,registryState};
