"use strict";
const { createInMemoryIdentityFederationRepository } = require("./identityFederationRepository");
const CONTRACT_VERSION = "2026-07-civitas10-identity-federation-v1";
const REASON = Object.freeze({ VERSION_REQUIRED: "identity_version_required", VERSION_CONFLICT: "identity_version_conflict", NOT_FOUND: "identity_resource_not_found", CROSS_TENANT: "identity_cross_tenant_reference", VALIDATION: "identity_validation_failed" });
const defaultRepository = createInMemoryIdentityFederationRepository();
function actor(req) { return req.user?.sub || req.user?.id || req.auth?.subject || "system"; }
function expected(req) { return req.body?.expectedVersion ?? req.get?.("if-match"); }
function assertMutation(req, current) { const exp = expected(req); if (!exp && exp !== 0) throw Object.assign(new Error(REASON.VERSION_REQUIRED), { status: 428, code: REASON.VERSION_REQUIRED }); if (current && String(exp).replace(/^W\//, "").replaceAll('"', "") !== String(current.version)) throw Object.assign(new Error(REASON.VERSION_CONFLICT), { status: 412, code: REASON.VERSION_CONFLICT }); }
function safeBody(body = {}) { const { clientSecret, secret, password, privateKey, ...safe } = body; return safe; }
function sendError(res, e) { return res.status(e.status || 400).json({ error: "IdentityFederationError", reasonCode: e.code || REASON.VALIDATION, message: e.status >= 500 ? "Identity federation operation failed" : e.message }); }
function registerIdentityFederationRoutes({ secureRoute, requireSafeOrganizationIdParam, ownerMiddleware = [], tenantMiddleware = [], repository = defaultRepository }) {
  const mutate = (eventType, targetType, fn) => async (req, res) => { try { const idem = req.get?.("idempotency-key"); const replay = await repository.replayIdempotency(idem); if (replay) return res.status(replay.status || 200).json(replay.body); const body = await fn(req); await repository.audit({ action: eventType, logtoOrganizationId: req.params.organizationId, actorLogtoUserId: actor(req), targetType, targetId: body.result?.id, metadata: { reason: req.body?.reason || eventType } }); await repository.enqueueOutbox({ eventType, aggregateType: targetType, aggregateId: body.result?.id || req.params.organizationId, logtoOrganizationId: req.params.organizationId, payload: safeBody(req.body || {}) }); const response = { status: body.status || 200, body: { contractVersion: CONTRACT_VERSION, ...body } }; await repository.rememberIdempotency(idem, response); return res.status(response.status).json(response.body); } catch (e) { return sendError(res, e); } };
  const o = ownerMiddleware, t = tenantMiddleware, org = requireSafeOrganizationIdParam;
  secureRoute.get("/owner/organizations/:organizationId/identity/connections", "ownerRead", org, ...o, async (req,res)=>res.json({ contractVersion: CONTRACT_VERSION, connections: await repository.listConnections(req.params.organizationId) }));
  secureRoute.post("/owner/organizations/:organizationId/identity/connections", "ownerSensitiveWrite", org, ...o, mutate("identity.connection.created", "identity_connection", async (req)=>{ assertMutation(req); return { status: 201, result: await repository.saveConnection({ ...safeBody(req.body), logtoOrganizationId: req.params.organizationId, createdByLogtoUserId: actor(req), updatedByLogtoUserId: actor(req), issuerOrEntityId: req.body?.issuerOrEntityId || req.body?.issuer, configurationFingerprint: req.body?.configurationFingerprint || "pending" }) }; }));
  secureRoute.get("/owner/organizations/:organizationId/identity/connections/:connectionId", "ownerRead", org, ...o, async (req,res)=>{ const result = await repository.getConnection(req.params.organizationId, req.params.connectionId); return result ? res.json({ contractVersion: CONTRACT_VERSION, result }) : res.status(404).json({ reasonCode: REASON.NOT_FOUND }); });
  secureRoute.put("/owner/organizations/:organizationId/identity/connections/:connectionId", "ownerSensitiveWrite", org, ...o, mutate("identity.connection.changed", "identity_connection", async (req)=>{ const cur = await repository.getConnection(req.params.organizationId, req.params.connectionId); assertMutation(req, cur); return { result: await repository.saveConnection({ ...safeBody(req.body), id: req.params.connectionId, logtoOrganizationId: req.params.organizationId, updatedByLogtoUserId: actor(req) }) }; }));
  for (const [suffix, status, event] of [["validate","validated","identity.connection.validated"],["activate","active","identity.connection.activated"],["suspend","suspended","identity.connection.suspended"],["support-reconcile","reconciling","identity.reconciliation.started"]]) secureRoute.post(`/owner/organizations/:organizationId/identity/connections/:connectionId/${suffix}`, "ownerSensitiveWrite", org, ...o, mutate(event, "identity_connection", async (req)=>{ const cur = await repository.getConnection(req.params.organizationId, req.params.connectionId); assertMutation(req, cur); return { status: suffix === "support-reconcile" ? 202 : 200, result: await repository.saveConnection({ id: req.params.connectionId, logtoOrganizationId: req.params.organizationId, status, updatedByLogtoUserId: actor(req), ...(suffix === "validate" ? { lastValidatedAt: new Date().toISOString() } : {}) }) }; }));
  secureRoute.get("/o/:organizationId/identity/connection", "organizationMemberRead", org, ...t, async (req,res)=>res.json({ contractVersion: CONTRACT_VERSION, connection: (await repository.listConnections(req.params.organizationId))[0] || null }));
  secureRoute.get("/o/:organizationId/identity/claims", "organizationMemberRead", org, ...t, async (req,res)=>res.json({ contractVersion: CONTRACT_VERSION, claims: [] }));
  secureRoute.put("/o/:organizationId/identity/claim-contract", "organizationAdminWrite", org, ...t, mutate("identity.claim_contract.changed", "identity_claim_contract", async (req)=>{ assertMutation(req); return { result: { logtoOrganizationId: req.params.organizationId, version: Number(req.body?.expectedVersion || 0) + 1 } }; }));
  secureRoute.get("/o/:organizationId/identity/role-mappings", "organizationMemberRead", org, ...t, async (req,res)=>res.json({ contractVersion: CONTRACT_VERSION, mappings: await repository.listRoleMappings(req.params.organizationId) }));
  secureRoute.post("/o/:organizationId/identity/role-mappings", "organizationAdminWrite", org, ...t, mutate("identity.mapping.created", "identity_role_mapping", async (req)=>{ assertMutation(req); return { status: 201, result: await repository.saveRoleMapping({ ...req.body, logtoOrganizationId: req.params.organizationId, createdByLogtoUserId: actor(req), updatedByLogtoUserId: actor(req) }) }; }));
  secureRoute.put("/o/:organizationId/identity/role-mappings/:mappingId", "organizationAdminWrite", org, ...t, mutate("identity.mapping.changed", "identity_role_mapping", async (req)=>{ const cur = await repository.getRoleMapping(req.params.organizationId, req.params.mappingId); assertMutation(req, cur); return { result: await repository.saveRoleMapping({ ...req.body, id: req.params.mappingId, logtoOrganizationId: req.params.organizationId, updatedByLogtoUserId: actor(req) }) }; }));
  secureRoute.delete("/o/:organizationId/identity/role-mappings/:mappingId", "organizationAdminWrite", org, ...t, mutate("identity.mapping.deleted", "identity_role_mapping", async (req)=>{ const cur = await repository.getRoleMapping(req.params.organizationId, req.params.mappingId); assertMutation(req, cur); return { result: await repository.deleteRoleMapping(req.params.organizationId, req.params.mappingId) }; }));
  secureRoute.get("/o/:organizationId/identity/scope-mappings", "organizationMemberRead", org, ...t, async (req,res)=>res.json({ contractVersion: CONTRACT_VERSION, mappings: await repository.listScopeMappings(req.params.organizationId) }));
  secureRoute.post("/o/:organizationId/identity/scope-mappings", "organizationAdminWrite", org, ...t, mutate("identity.mapping.created", "identity_scope_mapping", async (req)=>{ assertMutation(req); return { status: 201, result: await repository.saveScopeMapping({ ...req.body, logtoOrganizationId: req.params.organizationId }) }; }));
  secureRoute.put("/o/:organizationId/identity/provisioning-policy", "organizationAdminWrite", org, ...t, mutate("identity.provisioning.policy_changed", "identity_provisioning_policy", async (req)=>{ const cur = await repository.getPolicy(req.params.organizationId); assertMutation(req, cur); return { result: await repository.savePolicy({ ...req.body, logtoOrganizationId: req.params.organizationId, updatedByLogtoUserId: actor(req) }) }; }));
  secureRoute.post("/o/:organizationId/identity/test-login-session", "organizationAdminWrite", org, ...t, mutate("identity.test_login.completed", "identity_test_login", async (req)=>{ assertMutation(req); return { result: { status: "accepted", reasonCode: "identity_test_login_queued" } }; }));
  secureRoute.post("/o/:organizationId/identity/dry-run", "organizationAdminWrite", org, ...t, mutate("identity.dry_run.completed", "identity_dry_run", async (req)=>{ assertMutation(req); return { result: { subjects: Array.isArray(req.body?.subjects) ? req.body.subjects.length : 0, reasonCode: "identity_dry_run_completed" } }; }));
  secureRoute.post("/o/:organizationId/identity/reconciliation-runs", "organizationAdminWrite", org, ...t, mutate("identity.reconciliation.started", "identity_reconciliation_run", async (req)=>{ assertMutation(req); return { status: 202, result: await repository.createRun({ ...req.body, logtoOrganizationId: req.params.organizationId, triggerSource: req.body?.triggerSource || "tenant_api", correlationId: req.body?.correlationId || req.get?.("idempotency-key") || `${Date.now()}` }) }; }));
  secureRoute.get("/o/:organizationId/identity/reconciliation-runs", "organizationMemberRead", org, ...t, async (req,res)=>res.json({ contractVersion: CONTRACT_VERSION, runs: await repository.listRuns(req.params.organizationId) }));
  secureRoute.get("/o/:organizationId/identity/reconciliation-runs/:runId", "organizationMemberRead", org, ...t, async (req,res)=>{ const run = await repository.getRun(req.params.organizationId, req.params.runId); return run ? res.json({ contractVersion: CONTRACT_VERSION, run }) : res.status(404).json({ reasonCode: REASON.NOT_FOUND }); });
}
module.exports = { CONTRACT_VERSION, REASON, defaultRepository, registerIdentityFederationRoutes };
