"use strict";
const { sql } = require("drizzle-orm");
const { pgTable, uuid, varchar, text, bigint, integer, numeric, timestamp, jsonb, boolean, uniqueIndex, index, foreignKey } = require("drizzle-orm/pg-core");

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
};

const organizationScimConnections = pgTable("organization_scim_connections", {
  id: uuid("id").primaryKey().defaultRandom(),
  logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(),
  displayName: varchar("display_name", { length: 255 }).notNull(),
  baseUrl: text("base_url"),
  status: varchar("status", { length: 40 }).notNull().default("draft"),
  scimVersion: varchar("scim_version", { length: 16 }).notNull().default("2.0"),
  authMode: varchar("auth_mode", { length: 40 }).notNull().default("bearer_token"),
  provisioningMode: varchar("provisioning_mode", { length: 40 }).notNull().default("authoritative"),
  userMatchStrategy: varchar("user_match_strategy", { length: 80 }).notNull().default("external_id_then_user_name"),
  groupMatchStrategy: varchar("group_match_strategy", { length: 80 }).notNull().default("external_id_then_display_name"),
  configurationFingerprint: varchar("configuration_fingerprint", { length: 128 }).notNull(),
  version: bigint("version", { mode: "number" }).notNull().default(1),
  createdByLogtoUserId: varchar("created_by_logto_user_id", { length: 128 }).notNull(),
  updatedByLogtoUserId: varchar("updated_by_logto_user_id", { length: 128 }).notNull(),
  ...timestamps,
}, (t) => ({
  orgIdUidx: uniqueIndex("organization_scim_connections_org_id_uidx").on(t.logtoOrganizationId, t.id),
  orgStatusIdx: index("organization_scim_connections_org_status_idx").on(t.logtoOrganizationId, t.status),
}));

const connectionTenantFk = (name, t) => foreignKey({ name, columns: [t.logtoOrganizationId, t.connectionId], foreignColumns: [organizationScimConnections.logtoOrganizationId, organizationScimConnections.id] }).onDelete("cascade");

const organizationScimCredentials = pgTable("organization_scim_credentials", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), connectionId: uuid("connection_id").notNull(), credentialKind: varchar("credential_kind", { length: 40 }).notNull(), secretReference: varchar("secret_reference", { length: 255 }).notNull(), status: varchar("status", { length: 40 }).notNull().default("active"), validFrom: timestamp("valid_from", { withTimezone: true }).notNull().defaultNow(), validUntil: timestamp("valid_until", { withTimezone: true }), rotatedFromCredentialId: uuid("rotated_from_credential_id"), createdByLogtoUserId: varchar("created_by_logto_user_id", { length: 128 }).notNull(), ...timestamps,
}, (t) => ({ orgIdUidx: uniqueIndex("organization_scim_credentials_org_id_uidx").on(t.logtoOrganizationId, t.id), activeUidx: uniqueIndex("organization_scim_credentials_active_uidx").on(t.connectionId, t.credentialKind).where(sql`${t.status} in ('active','pending_rotation')`), connectionFk: connectionTenantFk("organization_scim_credentials_connection_fk", t), rotatedFk: foreignKey({ name: "organization_scim_credentials_rotated_fk", columns: [t.logtoOrganizationId, t.rotatedFromCredentialId], foreignColumns: [t.logtoOrganizationId, t.id] }).onDelete("restrict") }));

const organizationScimUsers = pgTable("organization_scim_users", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), connectionId: uuid("connection_id").notNull(), externalId: varchar("external_id", { length: 255 }).notNull(), userName: varchar("user_name", { length: 255 }).notNull(), logtoUserId: varchar("logto_user_id", { length: 128 }), active: boolean("active").notNull().default(true), displayName: varchar("display_name", { length: 255 }), email: varchar("email", { length: 255 }), rawFingerprint: varchar("raw_fingerprint", { length: 128 }).notNull(), syncState: varchar("sync_state", { length: 40 }).notNull().default("observed"), lastObservedAt: timestamp("last_observed_at", { withTimezone: true }).notNull().defaultNow(), version: bigint("version", { mode: "number" }).notNull().default(1), ...timestamps,
}, (t) => ({ orgIdUidx: uniqueIndex("organization_scim_users_org_id_uidx").on(t.logtoOrganizationId, t.id), connectionIdUidx: uniqueIndex("organization_scim_users_connection_id_uidx").on(t.connectionId, t.id), externalUidx: uniqueIndex("organization_scim_users_external_uidx").on(t.connectionId, t.externalId), usernameUidx: uniqueIndex("organization_scim_users_username_uidx").on(t.connectionId, t.userName), logtoIdx: index("organization_scim_users_logto_idx").on(t.logtoOrganizationId, t.logtoUserId), connectionFk: connectionTenantFk("organization_scim_users_connection_fk", t) }));

const organizationScimGroups = pgTable("organization_scim_groups", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), connectionId: uuid("connection_id").notNull(), externalId: varchar("external_id", { length: 255 }).notNull(), displayName: varchar("display_name", { length: 255 }).notNull(), logtoGroupId: varchar("logto_group_id", { length: 128 }), rawFingerprint: varchar("raw_fingerprint", { length: 128 }).notNull(), syncState: varchar("sync_state", { length: 40 }).notNull().default("observed"), lastObservedAt: timestamp("last_observed_at", { withTimezone: true }).notNull().defaultNow(), version: bigint("version", { mode: "number" }).notNull().default(1), ...timestamps,
}, (t) => ({ orgIdUidx: uniqueIndex("organization_scim_groups_org_id_uidx").on(t.logtoOrganizationId, t.id), connectionIdUidx: uniqueIndex("organization_scim_groups_connection_id_uidx").on(t.connectionId, t.id), externalUidx: uniqueIndex("organization_scim_groups_external_uidx").on(t.connectionId, t.externalId), displayUidx: uniqueIndex("organization_scim_groups_display_uidx").on(t.connectionId, t.displayName), connectionFk: connectionTenantFk("organization_scim_groups_connection_fk", t) }));

const organizationScimGroupMemberships = pgTable("organization_scim_group_memberships", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), connectionId: uuid("connection_id").notNull(), groupId: uuid("group_id").notNull(), userId: uuid("user_id").notNull(), membershipState: varchar("membership_state", { length: 40 }).notNull().default("active"), sourceOperationId: uuid("source_operation_id"), observedAt: timestamp("observed_at", { withTimezone: true }).notNull().defaultNow(), ...timestamps,
}, (t) => ({ membershipUidx: uniqueIndex("organization_scim_group_memberships_uidx").on(t.connectionId, t.groupId, t.userId), userIdx: index("organization_scim_group_memberships_user_idx").on(t.connectionId, t.userId, t.membershipState), connectionFk: connectionTenantFk("organization_scim_group_memberships_connection_fk", t), groupFk: foreignKey({ name: "organization_scim_group_memberships_group_fk", columns: [t.connectionId, t.groupId], foreignColumns: [organizationScimGroups.connectionId, organizationScimGroups.id] }).onDelete("cascade"), userFk: foreignKey({ name: "organization_scim_group_memberships_user_fk", columns: [t.connectionId, t.userId], foreignColumns: [organizationScimUsers.connectionId, organizationScimUsers.id] }).onDelete("cascade") }));

const organizationScimOperationLedger = pgTable("organization_scim_operation_ledger", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), connectionId: uuid("connection_id").notNull(), operationKind: varchar("operation_kind", { length: 80 }).notNull(), targetType: varchar("target_type", { length: 40 }).notNull(), targetScimUserId: uuid("target_scim_user_id"), targetScimGroupId: uuid("target_scim_group_id"), requestId: varchar("request_id", { length: 160 }).notNull(), idempotencyKey: varchar("idempotency_key", { length: 220 }).notNull(), status: varchar("status", { length: 40 }).notNull().default("accepted"), correlationId: varchar("correlation_id", { length: 160 }).notNull(), actorJson: jsonb("actor_json").notNull().default(sql`'{}'::jsonb`), requestSummary: jsonb("request_summary").notNull().default(sql`'{}'::jsonb`), resultSummary: jsonb("result_summary").notNull().default(sql`'{}'::jsonb`), errorJson: jsonb("error_json"), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), ...timestamps,
}, (t) => ({ connectionIdUidx: uniqueIndex("organization_scim_operation_ledger_connection_id_uidx").on(t.connectionId, t.id), idemUidx: uniqueIndex("organization_scim_operation_ledger_idem_uidx").on(t.connectionId, t.idempotencyKey), requestUidx: uniqueIndex("organization_scim_operation_ledger_request_uidx").on(t.connectionId, t.requestId), workIdx: index("organization_scim_operation_ledger_work_idx").on(t.connectionId, t.status, t.createdAt), connectionFk: connectionTenantFk("organization_scim_operation_ledger_connection_fk", t), userFk: foreignKey({ name: "organization_scim_operation_ledger_user_fk", columns: [t.connectionId, t.targetScimUserId], foreignColumns: [organizationScimUsers.connectionId, organizationScimUsers.id] }).onDelete("restrict"), groupFk: foreignKey({ name: "organization_scim_operation_ledger_group_fk", columns: [t.connectionId, t.targetScimGroupId], foreignColumns: [organizationScimGroups.connectionId, organizationScimGroups.id] }).onDelete("restrict") }));

const organizationScimSourceProvenanceRecords = pgTable("organization_scim_source_provenance_records", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), connectionId: uuid("connection_id").notNull(), sourceKind: varchar("source_kind", { length: 60 }).notNull(), sourceResourceType: varchar("source_resource_type", { length: 40 }).notNull(), sourceResourceId: varchar("source_resource_id", { length: 255 }).notNull(), scimUserId: uuid("scim_user_id"), scimGroupId: uuid("scim_group_id"), operationId: uuid("operation_id"), externalVersion: varchar("external_version", { length: 160 }), resourceFingerprint: varchar("resource_fingerprint", { length: 128 }).notNull(), observedAt: timestamp("observed_at", { withTimezone: true }).notNull().defaultNow(), expiresAt: timestamp("expires_at", { withTimezone: true }), metadata: jsonb("metadata").notNull().default(sql`'{}'::jsonb`), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ sourceUidx: uniqueIndex("organization_scim_source_provenance_uidx").on(t.connectionId, t.sourceKind, t.sourceResourceType, t.sourceResourceId, t.resourceFingerprint), connectionFk: connectionTenantFk("organization_scim_source_provenance_connection_fk", t), userFk: foreignKey({ name: "organization_scim_source_provenance_user_fk", columns: [t.connectionId, t.scimUserId], foreignColumns: [organizationScimUsers.connectionId, organizationScimUsers.id] }).onDelete("restrict"), groupFk: foreignKey({ name: "organization_scim_source_provenance_group_fk", columns: [t.connectionId, t.scimGroupId], foreignColumns: [organizationScimGroups.connectionId, organizationScimGroups.id] }).onDelete("restrict"), operationFk: foreignKey({ name: "organization_scim_source_provenance_operation_fk", columns: [t.connectionId, t.operationId], foreignColumns: [organizationScimOperationLedger.connectionId, organizationScimOperationLedger.id] }).onDelete("restrict") }));

const organizationScimReconciliationPlans = pgTable("organization_scim_reconciliation_plans", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), connectionId: uuid("connection_id").notNull(), planKind: varchar("plan_kind", { length: 60 }).notNull().default("scheduled_full"), status: varchar("status", { length: 40 }).notNull().default("draft"), baselineCursor: varchar("baseline_cursor", { length: 255 }), plannedCounts: jsonb("planned_counts").notNull().default(sql`'{}'::jsonb`), riskSummary: jsonb("risk_summary").notNull().default(sql`'{}'::jsonb`), createdByLogtoUserId: varchar("created_by_logto_user_id", { length: 128 }).notNull(), approvedByLogtoUserId: varchar("approved_by_logto_user_id", { length: 128 }), approvedAt: timestamp("approved_at", { withTimezone: true }), ...timestamps,
}, (t) => ({ orgIdUidx: uniqueIndex("organization_scim_reconciliation_plans_org_id_uidx").on(t.logtoOrganizationId, t.id), connectionIdUidx: uniqueIndex("organization_scim_reconciliation_plans_connection_id_uidx").on(t.connectionId, t.id), connectionFk: connectionTenantFk("organization_scim_reconciliation_plans_connection_fk", t) }));

const organizationScimReconciliationRuns = pgTable("organization_scim_reconciliation_runs", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), connectionId: uuid("connection_id").notNull(), planId: uuid("plan_id").notNull(), status: varchar("status", { length: 40 }).notNull().default("queued"), cursorIn: varchar("cursor_in", { length: 255 }), cursorOut: varchar("cursor_out", { length: 255 }), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), observedCounts: jsonb("observed_counts").notNull().default(sql`'{}'::jsonb`), appliedCounts: jsonb("applied_counts").notNull().default(sql`'{}'::jsonb`), errorJson: jsonb("error_json"), ...timestamps,
}, (t) => ({ connectionIdUidx: uniqueIndex("organization_scim_reconciliation_runs_connection_id_uidx").on(t.connectionId, t.id), statusIdx: index("organization_scim_reconciliation_runs_status_idx").on(t.connectionId, t.status, t.createdAt), connectionFk: connectionTenantFk("organization_scim_reconciliation_runs_connection_fk", t), planFk: foreignKey({ name: "organization_scim_reconciliation_runs_plan_fk", columns: [t.connectionId, t.planId], foreignColumns: [organizationScimReconciliationPlans.connectionId, organizationScimReconciliationPlans.id] }).onDelete("cascade") }));

const organizationScimMassDeprovisionSafeguardSettings = pgTable("organization_scim_mass_deprovision_safeguard_settings", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), connectionId: uuid("connection_id").notNull(), isEnabled: boolean("is_enabled").notNull().default(true), maxUserDeprovisionPercent: numeric("max_user_deprovision_percent", { precision: 5, scale: 2 }).notNull().default("10.00"), maxGroupDeprovisionPercent: numeric("max_group_deprovision_percent", { precision: 5, scale: 2 }).notNull().default("10.00"), maxAbsoluteUserDeprovisions: integer("max_absolute_user_deprovisions").notNull().default(25), maxAbsoluteGroupDeprovisions: integer("max_absolute_group_deprovisions").notNull().default(10), requireManualApproval: boolean("require_manual_approval").notNull().default(true), bypassUntil: timestamp("bypass_until", { withTimezone: true }), bypassReason: text("bypass_reason"), updatedByLogtoUserId: varchar("updated_by_logto_user_id", { length: 128 }).notNull(), ...timestamps,
}, (t) => ({ connectionUidx: uniqueIndex("organization_scim_mass_deprovision_settings_connection_uidx").on(t.connectionId), connectionFk: connectionTenantFk("organization_scim_mass_deprovision_settings_connection_fk", t) }));

const organizationScimDeprovisionHistory = pgTable("organization_scim_deprovision_history", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), connectionId: uuid("connection_id").notNull(), runId: uuid("run_id"), operationId: uuid("operation_id"), targetType: varchar("target_type", { length: 40 }).notNull(), scimUserId: uuid("scim_user_id"), scimGroupId: uuid("scim_group_id"), logtoUserId: varchar("logto_user_id", { length: 128 }), logtoGroupId: varchar("logto_group_id", { length: 128 }), decision: varchar("decision", { length: 40 }).notNull(), reasonCode: varchar("reason_code", { length: 120 }).notNull(), safeguardSnapshot: jsonb("safeguard_snapshot").notNull().default(sql`'{}'::jsonb`), actorLogtoUserId: varchar("actor_logto_user_id", { length: 128 }), decidedAt: timestamp("decided_at", { withTimezone: true }).notNull().defaultNow(), executedAt: timestamp("executed_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({ targetIdx: index("organization_scim_deprovision_history_target_idx").on(t.connectionId, t.targetType, t.decidedAt), connectionFk: connectionTenantFk("organization_scim_deprovision_history_connection_fk", t), runFk: foreignKey({ name: "organization_scim_deprovision_history_run_fk", columns: [t.connectionId, t.runId], foreignColumns: [organizationScimReconciliationRuns.connectionId, organizationScimReconciliationRuns.id] }).onDelete("restrict"), operationFk: foreignKey({ name: "organization_scim_deprovision_history_operation_fk", columns: [t.connectionId, t.operationId], foreignColumns: [organizationScimOperationLedger.connectionId, organizationScimOperationLedger.id] }).onDelete("restrict"), userFk: foreignKey({ name: "organization_scim_deprovision_history_user_fk", columns: [t.connectionId, t.scimUserId], foreignColumns: [organizationScimUsers.connectionId, organizationScimUsers.id] }).onDelete("restrict"), groupFk: foreignKey({ name: "organization_scim_deprovision_history_group_fk", columns: [t.connectionId, t.scimGroupId], foreignColumns: [organizationScimGroups.connectionId, organizationScimGroups.id] }).onDelete("restrict") }));

module.exports = { organizationScimConnections, organizationScimCredentials, organizationScimUsers, organizationScimGroups, organizationScimGroupMemberships, organizationScimOperationLedger, organizationScimSourceProvenanceRecords, organizationScimReconciliationPlans, organizationScimReconciliationRuns, organizationScimMassDeprovisionSafeguardSettings, organizationScimDeprovisionHistory };
