import { useEffect, useRef, useState, type FormEvent } from "react";
import { EmptyState, PageHeader, SectionCard, StateRegion, StatusPill } from "../../shared/ui";
import { PlanningApiError, type PlanningPlan, type PlanningPlanInput, type PlanningProfile, usePlanningApi } from "./planningApi";

type Screen = "home" | "list" | "create" | "detail" | "edit" | "profile";
type Props = { organizationId: string; screen: Screen; planId?: string; readOnly?: boolean; access?: "allowed" | "denied"; availability?: "available" | "unavailable" | "degraded" | "incompatible" };
const copy: Record<string, string> = { denied: "You do not have access to Planning in this organization.", unavailable: "Planning is temporarily unavailable.", incompatible: "This Planning UI is incompatible with the active host contract.", conflict: "Someone else updated this plan. Reload before saving again.", validation: "Check the highlighted fields and try again.", archived: "Archived plans are read-only." };

const usePlanningData = (organizationId: string, screen: Screen, planId?: string) => { const api = usePlanningApi(); const [plans, setPlans] = useState<PlanningPlan[]>([]); const [plan, setPlan] = useState<PlanningPlan | null>(null); const [profile, setProfile] = useState<PlanningProfile | null>(null); const [error, setError] = useState<PlanningApiError | null>(null); const [loading, setLoading] = useState(true); const orgRef = useRef(organizationId);
  useEffect(() => { const controller = new AbortController(); if (orgRef.current !== organizationId) { setPlans([]); setPlan(null); setProfile(null); orgRef.current = organizationId; } setLoading(true); setError(null); const run = async () => { try { if (screen === "detail" || screen === "edit") setPlan((await api.getPlan(organizationId, planId || "", controller.signal)) ?? null); else if (screen === "profile") setProfile((await api.getProfile(organizationId, controller.signal)) ?? null); else setPlans(((await api.listPlans(organizationId, controller.signal))?.items) ?? []); } catch (e) { if (!controller.signal.aborted) setError(e instanceof PlanningApiError ? e : new PlanningApiError(String(e))); } finally { if (!controller.signal.aborted) setLoading(false); } }; run(); return () => controller.abort(); }, [api, organizationId, planId, screen]); return { plans, plan, setPlan, profile, setProfile, error, setError, loading }; };

function Banner({ state, error, readOnly }: { state?: Props["availability"]; error?: PlanningApiError | null; readOnly?: boolean }) { const message = state === "degraded" || readOnly ? "Planning is in degraded read-only mode. Write actions are disabled." : state ? copy[state] : error?.status === 412 || error?.code === "precondition_failed" || error?.code === "stale" ? copy.conflict : error?.status === 422 || error?.code === "validation" ? copy.validation : error?.code === "archived" ? copy.archived : error?.message; return message ? <StateRegion><p role="status">{message}</p></StateRegion> : null; }
function PlanForm({ initial, readOnly, onSubmit }: { initial?: PlanningPlan | null; readOnly?: boolean; onSubmit: (input: PlanningPlanInput) => Promise<void> }) { const [title, setTitle] = useState(initial?.title || ""); const [description, setDescription] = useState(initial?.description || ""); const [saving, setSaving] = useState(false); const invalid = title.trim().length < 3; const ref = useRef<HTMLInputElement>(null); useEffect(() => { ref.current?.focus(); }, []); const submit = async (event: FormEvent) => { event.preventDefault(); if (invalid || readOnly) return; setSaving(true); await onSubmit({ title, description }); setSaving(false); }; return <form className="civitas-stack-md" onSubmit={submit} aria-describedby="planning-form-status"><label>Plan title<input ref={ref} value={title} onChange={(e) => setTitle(e.target.value)} aria-invalid={invalid} disabled={readOnly} /></label><label>Description<textarea value={description} onChange={(e) => setDescription(e.target.value)} disabled={readOnly} /></label><p id="planning-form-status" aria-live="polite">{readOnly ? "Read-only mode" : saving ? "Saving plan" : invalid ? "Title must be at least 3 characters." : "Ready to save"}</p><button className="civitas-button" disabled={readOnly || invalid || saving}>{saving ? "Saving…" : "Save plan"}</button></form>; }

export function PlanningRemoteScreen(props: Props) { const readOnly = props.readOnly || props.availability === "degraded"; const api = usePlanningApi(); const data = usePlanningData(props.organizationId, props.screen, props.planId); const isArchived = data.plan?.status === "archived"; const title = `Planning ${props.screen}`; if (props.access === "denied") return <Denied />; if (props.availability === "unavailable" || props.availability === "incompatible") return <><PageHeader eyebrow="Planning" title={title} /><Banner state={props.availability} /></>; if (data.loading) return <><PageHeader eyebrow="Planning" title={title} /><StateRegion><p role="status">Loading Planning workspace…</p></StateRegion></>;
  const save = async (input: PlanningPlanInput) => { try { if (props.screen === "create") data.setPlan((await api.createPlan(props.organizationId, input)) ?? null); else if (data.plan) data.setPlan((await api.updatePlan(props.organizationId, data.plan.id, input, data.plan.etag || data.plan.version)) ?? null); } catch (e) { data.setError(e as PlanningApiError); } };
  const replaceProfile = async (replacement: Pick<PlanningProfile, "planningMode" | "preferences">) => { if (!data.profile) return; try { data.setProfile((await api.replaceProfile(props.organizationId, replacement, data.profile.etag || data.profile.version)) ?? null); } catch (e) { data.setError(e as PlanningApiError); } };
  return <main className="civitas-stack-lg" data-module="planning" aria-labelledby="planning-title"><PageHeader eyebrow="Planning" title={<span id="planning-title">{title}</span>} description="Organization-aware Planning remote UI." actions={!readOnly && props.screen === "list" ? <a className="civitas-button" href="./create">New plan</a> : null} /><Banner state={props.availability} error={data.error} readOnly={readOnly || isArchived} />{(props.screen === "home" || props.screen === "list") && <PlanList plans={data.plans} />}{props.screen === "create" && <SectionCard><PlanForm readOnly={readOnly} onSubmit={save} /></SectionCard>}{(props.screen === "detail" || props.screen === "edit") && <PlanDetail plan={data.plan} edit={props.screen === "edit"} readOnly={readOnly || isArchived} onSubmit={save} />}{props.screen === "profile" && <ProfileForm profile={data.profile} readOnly={readOnly} onSubmit={replaceProfile} />}</main>; }
function PlanList({ plans }: { plans: PlanningPlan[] }) { if (!plans.length) return <EmptyState message="No planning records yet."><a className="civitas-button" href="./create">Create a plan</a></EmptyState>; return <SectionCard><div className="civitas-responsive-table" role="region" aria-label="Planning plans" tabIndex={0}><table><thead><tr><th>Title</th><th>Status</th><th>Updated</th></tr></thead><tbody>{plans.map((p) => <tr key={p.id}><td><a href={`./${encodeURIComponent(p.id)}`}>{p.title}</a></td><td><StatusPill status={p.status === "archived" ? "neutral" : "success"}>{p.status}</StatusPill></td><td>{p.updatedAt || "Not available"}</td></tr>)}</tbody></table></div></SectionCard>; }
function PlanDetail({ plan, edit, readOnly, onSubmit }: { plan: PlanningPlan | null; edit: boolean; readOnly?: boolean; onSubmit: (input: PlanningPlanInput) => Promise<void> }) { if (!plan) return <EmptyState message="Planning record was not found or is no longer available." />; return <SectionCard>{edit ? <PlanForm initial={plan} readOnly={readOnly} onSubmit={onSubmit} /> : <><h2>{plan.title}</h2><p>{plan.description || "No description provided."}</p><StatusPill status={plan.status === "archived" ? "neutral" : "success"}>{plan.status}</StatusPill></>}</SectionCard>; }
function Denied() { return <main className="civitas-stack-lg"><PageHeader eyebrow="Planning" title="Access denied" /><StateRegion><p role="alert">{copy.denied}</p></StateRegion></main>; }
function ProfileForm({ profile, readOnly, onSubmit }: { profile: PlanningProfile | null; readOnly: boolean; onSubmit: (value: Pick<PlanningProfile, "planningMode" | "preferences">) => Promise<void> }) { const [mode, setMode] = useState<PlanningProfile["planningMode"]>(profile?.planningMode || "standard"); const [fiscalYearStart, setFiscalYearStart] = useState(profile?.preferences.fiscalYearStart || "01-01"); if (!profile) return <EmptyState message="Planning profile was not found or is no longer available." />; return <SectionCard><h2>Planning profile</h2><form className="civitas-stack-md" onSubmit={(event) => { event.preventDefault(); void onSubmit({ planningMode: mode, preferences: { fiscalYearStart } }); }}><label>Planning mode<select value={mode} onChange={(event) => setMode(event.target.value as PlanningProfile["planningMode"])} disabled={readOnly}><option value="standard">Standard</option><option value="curriculum">Curriculum</option><option value="strategic">Strategic</option></select></label><label>Fiscal year start<input value={fiscalYearStart} pattern="[0-9]{2}-[0-9]{2}" onChange={(event) => setFiscalYearStart(event.target.value)} disabled={readOnly} /></label><button className="civitas-button" disabled={readOnly}>Replace profile</button></form></SectionCard>; }
export function PlanningBundleFailureFallback() { return <StateRegion><p role="alert">Planning could not be loaded. The host fallback kept the shell available.</p></StateRegion>; }
export default PlanningRemoteScreen;
