import { IconChevronRight } from "@tabler/icons-react";
import { PermissionGrid } from "./PermissionGrid";
import { Switch } from "./Switch";
import { UnavailableSwitch } from "./UnavailableSwitch";
export type PermissionToggleRow = { permissionId: string; label: string; description: string; checked: boolean; canChange: boolean };
export const PermissionGroupAccordion = ({ domain, rows, expanded, activeCount, totalCount, roleLabel, onExpandedChange, onTogglePermission, onToggleGroup }: { domain:string; rows:PermissionToggleRow[]; expanded:boolean; activeCount:number; totalCount:number; roleLabel:string; onExpandedChange:(value:boolean)=>void; onTogglePermission:(id:string,value:boolean)=>void; onToggleGroup:(value:boolean)=>void }) => {
  const editable=rows.filter((row)=>row.canChange); const allEditableEnabled=editable.length>0&&editable.every((row)=>row.checked); const partial=activeCount>0&&activeCount<totalCount;
  return <section className="civitas-card civitas-card-flush"><div className="civitas-card-header"><button type="button" className="civitas-button civitas-permission-group-summary" aria-expanded={expanded} onClick={()=>onExpandedChange(!expanded)}><IconChevronRight aria-hidden="true" className="civitas-nav-tree-caret-icon"/><span>{domain}</span></button><div className="civitas-cluster"><span aria-label={`${activeCount} of ${totalCount} permissions enabled`}>{activeCount} / {totalCount}</span><Switch checked={allEditableEnabled} visualState={partial?"mixed":allEditableEnabled?"on":"off"} disabled={!editable.length} label={`${allEditableEnabled?"Disable":"Enable"} editable ${domain} permissions for ${roleLabel}. ${activeCount} of ${totalCount} permissions enabled`} onCheckedChange={()=>onToggleGroup(!allEditableEnabled)}/></div></div>{expanded?<div className="civitas-list-stack"><PermissionGrid header permission="Permission" description="Description" control="Control"/>{rows.map((row)=><PermissionGrid key={row.permissionId} permission={<strong>{row.label}</strong>} description={row.description} control={row.canChange?<Switch checked={row.checked} label={`${row.label} for ${roleLabel}`} onCheckedChange={(checked)=>onTogglePermission(row.permissionId,checked)}/>:<UnavailableSwitch label={`${row.label} for ${roleLabel}`}/>}/>)}</div>:null}</section>;
};
