"use strict";

const IDENTITY_FEDERATION_CONTRACT_VERSION = "2026-07-civitas10-identity-federation-v1";
const IDENTITY_FEDERATION_READ_STATUSES = Object.freeze(["not_configured", "active", "degraded", "suspended", "credentials_expiring", "reconciliation_required"]);
const CONNECTION_STATUSES = Object.freeze(["draft", "validating", "ready", "active", "degraded", "suspended", "rotating_credentials", "decommissioning", "archived"]);
const PROTOCOLS = Object.freeze(["oidc", "saml"]);
const MAPPING_KINDS = Object.freeze(["rbac", "data_scope"]);
const RECONCILIATION_STATUSES = Object.freeze(["queued", "running", "completed", "blocked", "failed", "cancelled"]);

const contract = Object.freeze({ contractVersion: IDENTITY_FEDERATION_CONTRACT_VERSION, protocols: PROTOCOLS, connectionStatuses: CONNECTION_STATUSES, readStatuses: IDENTITY_FEDERATION_READ_STATUSES, mappingKinds: MAPPING_KINDS, reconciliationStatuses: RECONCILIATION_STATUSES });
const validateEnum = (field, value, allowed) => { if (!allowed.includes(value)) throw new Error(`${field}_invalid`); return value; };

function identityConnection(input = {}) { return Object.freeze({ id: input.id || null, logtoOrganizationId: input.logtoOrganizationId, logtoSsoConnectorId: input.logtoSsoConnectorId || null, protocol: validateEnum("protocol", input.protocol, PROTOCOLS), providerKind: input.providerKind, name: input.name, status: validateEnum("status", input.status || "draft", CONNECTION_STATUSES), issuerOrEntityId: input.issuerOrEntityId, subjectStrategy: input.subjectStrategy || "issuer_subject", groupMembershipMode: input.groupMembershipMode || "claim", claimContractVersion: Number(input.claimContractVersion || 1), mappingVersion: Number(input.mappingVersion || 1), provisioningPolicyVersion: Number(input.provisioningPolicyVersion || 1), configurationFingerprint: input.configurationFingerprint || null, secretReference: input.secretReference || null, lastValidatedAt: input.lastValidatedAt || null, lastSuccessfulLoginAt: input.lastSuccessfulLoginAt || null }); }
function normalizedExternalIdentity(input = {}) { return Object.freeze({ connectionId: input.connectionId, externalIssuer: input.externalIssuer, externalSubject: input.externalSubject, stableSubjectKey: input.stableSubjectKey || `${input.externalIssuer || "unknown"}:${input.externalSubject || "unknown"}`, email: input.email || null, displayName: input.displayName || null, groups: Object.freeze(input.groups || []), attributes: Object.freeze(input.attributes || {}), claimsComplete: input.claimsComplete === true, observedAt: input.observedAt || new Date(0).toISOString(), sourceVersion: input.sourceVersion || null }); }
function federationMapping(input = {}) { return Object.freeze({ id: input.id || null, logtoOrganizationId: input.logtoOrganizationId, connectionId: input.connectionId, kind: validateEnum("kind", input.kind, MAPPING_KINDS), externalGroupId: input.externalGroupId, logtoRoleId: input.logtoRoleId || null, canonicalRoleKey: input.canonicalRoleKey || null, scopeTemplateId: input.scopeTemplateId || null, scopeTemplateVersion: input.scopeTemplateVersion || null, targetKind: input.targetKind || null, targetRef: input.targetRef || null, mode: input.mode || "additive", approvalPolicy: input.approvalPolicy || "owner_ceiling_required", status: input.status || "draft", version: Number(input.version || 1) }); }
function provisioningPolicy(input = {}) { return Object.freeze({ logtoOrganizationId: input.logtoOrganizationId, connectionId: input.connectionId, joinMode: input.joinMode || "jit", fallbackMode: input.fallbackMode || "block", roleSyncMode: input.roleSyncMode || "managed_only", scopeSyncMode: input.scopeSyncMode || "managed_only", removeAbsentManagedAssignments: input.removeAbsentManagedAssignments === true, suspendDisabledUsers: input.suspendDisabledUsers !== false, privilegedRoleMode: input.privilegedRoleMode || "require_owner_approval", loginReconciliationEnabled: input.loginReconciliationEnabled !== false, scheduledReconciliationEnabled: input.scheduledReconciliationEnabled === true, reconciliationIntervalMinutes: input.reconciliationIntervalMinutes || null, gracePeriodMinutes: Number(input.gracePeriodMinutes || 1440), version: Number(input.version || 1) }); }
function reconciliationRun(input = {}) { return Object.freeze({ id: input.id || null, logtoOrganizationId: input.logtoOrganizationId, connectionId: input.connectionId, mode: input.mode || "dry_run", triggerSource: input.triggerSource || "manual", status: validateEnum("status", input.status || "queued", RECONCILIATION_STATUSES), startedAt: input.startedAt || null, completedAt: input.completedAt || null, mappingVersion: Number(input.mappingVersion || 1), policyVersion: Number(input.policyVersion || 1), totals: Object.freeze({ totalSubjects: Number(input.totalSubjects || 0), createdCount: Number(input.createdCount || 0), updatedCount: Number(input.updatedCount || 0), removedCount: Number(input.removedCount || 0), blockedCount: Number(input.blockedCount || 0), errorCount: Number(input.errorCount || 0) }), correlationId: input.correlationId || null }); }
module.exports = { IDENTITY_FEDERATION_CONTRACT_VERSION, IDENTITY_FEDERATION_READ_STATUSES, contract, identityConnection, normalizedExternalIdentity, federationMapping, provisioningPolicy, reconciliationRun };
