-- Tenant-scoped maker-checker review resources and immutable approval evidence.
create table if not exists planning_review_streams (logto_organization_id varchar(128) not null, plan_id varchar(180) not null, current_version integer not null default 0 check(current_version>=0), primary key(logto_organization_id,plan_id));
create table if not exists planning_review_events (event_id uuid primary key, logto_organization_id varchar(128) not null, plan_id varchar(180) not null, aggregate_version integer not null check(aggregate_version>0), event_type varchar(100) not null, payload jsonb not null, occurred_at timestamptz not null, unique(logto_organization_id,plan_id,aggregate_version), foreign key(logto_organization_id,plan_id) references planning_review_streams(logto_organization_id,plan_id));
create index if not exists planning_review_events_rebuild_idx on planning_review_events(logto_organization_id,plan_id,aggregate_version);
create table if not exists planning_collaborators (logto_organization_id varchar(128) not null, plan_id varchar(180) not null, collaborator_id varchar(128) not null, capabilities jsonb not null default '["edit"]', active boolean not null default true, created_at timestamptz not null default now(), primary key(logto_organization_id,plan_id,collaborator_id), foreign key(logto_organization_id,plan_id) references planning_review_streams(logto_organization_id,plan_id));
create table if not exists planning_maker_checker_policies (logto_organization_id varchar(128) not null, plan_id varchar(180) not null, version integer not null check(version>0), policy jsonb not null, created_by varchar(128) not null, created_at timestamptz not null default now(), primary key(logto_organization_id,plan_id,version), foreign key(logto_organization_id,plan_id) references planning_review_streams(logto_organization_id,plan_id));
create table if not exists planning_review_assignments (assignment_id uuid primary key, logto_organization_id varchar(128) not null, plan_id varchar(180) not null, assignee_id varchar(128) not null, assignment_role varchar(16) not null check(assignment_role in ('reviewer','approver')), plan_version integer not null, policy_version integer not null, assigned_by varchar(128) not null, active boolean not null default true, created_at timestamptz not null default now(), unique(logto_organization_id,assignment_id), foreign key(logto_organization_id,plan_id) references planning_review_streams(logto_organization_id,plan_id), foreign key(logto_organization_id,plan_id,policy_version) references planning_maker_checker_policies(logto_organization_id,plan_id,version));
create index if not exists planning_assignments_tenant_plan_idx on planning_review_assignments(logto_organization_id,plan_id,active);
create table if not exists planning_review_requests (review_request_id uuid primary key, logto_organization_id varchar(128) not null, plan_id varchar(180) not null, plan_version integer not null, policy_version integer not null, assignment_ids jsonb not null, status varchar(24) not null default 'open' check(status in ('open','completed','cancelled')), requested_by varchar(128) not null, created_at timestamptz not null default now(), unique(logto_organization_id,review_request_id), foreign key(logto_organization_id,plan_id) references planning_review_streams(logto_organization_id,plan_id));
create table if not exists planning_review_decisions (decision_id uuid primary key, logto_organization_id varchar(128) not null, plan_id varchar(180) not null, assignment_id uuid not null, actor_id varchar(128) not null, decision varchar(24) not null check(decision in ('approved','changes_requested')), plan_version integer not null, policy_version integer not null, rationale text, created_at timestamptz not null default now(), unique(logto_organization_id,assignment_id), foreign key(logto_organization_id,assignment_id) references planning_review_assignments(logto_organization_id,assignment_id));
create table if not exists planning_approved_snapshots (logto_organization_id varchar(128) not null, plan_id varchar(180) not null, plan_version integer not null, snapshot jsonb not null, snapshot_hash char(64) not null, provenance jsonb not null, approved_by varchar(128) not null, approved_at timestamptz not null, primary key(logto_organization_id,plan_id,plan_version), unique(logto_organization_id,plan_id,snapshot_hash));
create table if not exists planning_review_idempotency (logto_organization_id varchar(128) not null, operation varchar(100) not null, idempotency_key varchar(220) not null, request_fingerprint text not null, result_json jsonb not null, created_at timestamptz not null default now(), primary key(logto_organization_id,operation,idempotency_key));
create or replace function planning_forbid_immutable_change() returns trigger language plpgsql as $$ begin raise exception 'planning review history is immutable' using errcode='55000'; end $$;
drop trigger if exists planning_review_decisions_immutable on planning_review_decisions; create trigger planning_review_decisions_immutable before update or delete on planning_review_decisions for each row execute function planning_forbid_immutable_change();
drop trigger if exists planning_review_events_immutable on planning_review_events; create trigger planning_review_events_immutable before update or delete on planning_review_events for each row execute function planning_forbid_immutable_change();
drop trigger if exists planning_approved_snapshots_immutable on planning_approved_snapshots; create trigger planning_approved_snapshots_immutable before update or delete on planning_approved_snapshots for each row execute function planning_forbid_immutable_change();
drop trigger if exists planning_maker_checker_policies_immutable on planning_maker_checker_policies; create trigger planning_maker_checker_policies_immutable before update or delete on planning_maker_checker_policies for each row execute function planning_forbid_immutable_change();
