import { IconPencil, IconRestore } from "@tabler/icons-react";
import { Link } from "react-router";
import { EmptyState, StatusPill } from "../../../../shared/ui";
import type { GovernanceRoleNameRow, GovernanceSurface } from "../../contracts";
import { canResetRoleName, displayCount, displayNameForSurface, roleNameForSurface, usersHref } from "./roleNamesViewModel";

export const RoleNamesTable = ({ rows, surface, organizationId, onEdit, onReset }: { rows: GovernanceRoleNameRow[]; surface: GovernanceSurface; organizationId: string; onEdit: (row: GovernanceRoleNameRow, opener: HTMLButtonElement) => void; onReset: (row: GovernanceRoleNameRow, opener: HTMLButtonElement) => void }) => {
  if (!rows.length) return <EmptyState message="No roles match your search." />;
  const renderActions = (row: GovernanceRoleNameRow, displayName: string) => {
    const canEdit = surface === "owner" ? row.canEditGlobalDefault : row.canEditOrganizationAlias;
    if (!canEdit) return null;
    const canReset = canResetRoleName(row, surface);
    return <div className="flex gap-2"><button className="civitas-icon-button" type="button" aria-label={`Edit display name for ${displayName}`} title="Edit display name" onClick={(event) => onEdit(row, event.currentTarget)}><IconPencil aria-hidden="true" size={18} stroke={1.8} /></button><button className="civitas-icon-button" type="button" aria-label={canReset ? `Reset display name for ${displayName}` : "No custom display name to reset."} title={canReset ? "Reset display name" : "No custom display name to reset"} disabled={!canReset} onClick={(event) => onReset(row, event.currentTarget)}><IconRestore aria-hidden="true" size={18} stroke={1.8} /></button></div>;
  };
  return <div className="grid gap-3 md:block"><table className="hidden min-w-full text-sm md:table"><thead><tr className="border-b border-border text-left text-xs font-semibold uppercase tracking-[0.16em] text-muted"><th className="px-3 py-2">Role name</th><th className="px-3 py-2">Display name</th><th className="px-3 py-2">Users</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Actions</th></tr></thead><tbody>{rows.map((row) => { const displayName = displayNameForSurface(row, surface); return <tr key={row.logtoRoleId} className="border-b border-border"><td className="px-3 py-3">{roleNameForSurface(row, surface)}</td><td className="px-3 py-3">{displayName}</td><td className="px-3 py-3"><Link className="civitas-link" to={usersHref({ surface, organizationId, canonicalRoleKey: row.canonicalRoleKey })} aria-label={`View ${displayCount(row.directRoleUserCount)} assigned to ${displayName} in Segmentation`}>{displayCount(row.directRoleUserCount)}</Link></td><td className="px-3 py-3"><StatusPill status="success">Active</StatusPill></td><td className="px-3 py-3">{renderActions(row, displayName)}</td></tr>; })}</tbody></table>{rows.map((row) => { const displayName = displayNameForSurface(row, surface); return <article key={`card-${row.logtoRoleId}`} className="civitas-card civitas-pad-tight md:hidden"><div className="font-semibold">{roleNameForSurface(row, surface)}</div><p>{displayName}</p><Link className="civitas-link" to={usersHref({ surface, organizationId, canonicalRoleKey: row.canonicalRoleKey })} aria-label={`View ${displayCount(row.directRoleUserCount)} assigned to ${displayName} in Segmentation`}>{displayCount(row.directRoleUserCount)}</Link><div className="mt-2 flex items-center justify-between gap-3"><StatusPill status="success">Active</StatusPill>{renderActions(row, displayName)}</div></article>; })}</div>;
};
