"use strict";
const crypto=require("node:crypto");
const { organizationRoles, organizationRolePotentials } = require("../../../core/authz");
const { PostgresRoleLabelRepository } = require("./postgresRoleLabelRepository");
const { normalizeRoleLabel, duplicateKey } = require("./validation");
const { resolveEffectiveRoleLabel, resolveEffectiveRoleLabels } = require("./effectiveRoleLabelResolver");
function canonicalRoles(){return organizationRoles.map((key)=>{const role=organizationRolePotentials.find((r)=>r.roleKey===key)||{}; const label=role.presentation?.defaultLabel||role.displayName; if(!label) throw new Error(`canonical_role_baseline_label_missing:${key}`); return {canonicalRoleKey:key,canonicalBaselineLabel:label,displayName:role.displayName,presentation:{defaultLabel:label}};});}
function assertRole(key){if(!organizationRoles.includes(key)){const e=new Error("Unknown canonical organization role.");e.status=404;e.code="canonical_role_unknown";throw e;} return canonicalRoles().find((r)=>r.canonicalRoleKey===key);} function conflict(message,code,meta={}){const e=new Error(message);e.status=409;e.code=code;Object.assign(e,meta);return e;}
function roleId(role={}){return role.id||role.organizationRoleId||role.roleId||null;} function roleName(role={}){return role.name||role.nameCache||role.key||roleId(role);} function canonicalRoleKey(name=""){const raw=String(name||"").trim(); if(raw.startsWith("organization_"))return raw; return `organization_${raw.replace(/-org$/i,"").replace(/[^a-z0-9]+/gi,"_").replace(/^_+|_+$/g,"").toLowerCase()}`;}
class RoleLabelService{constructor({repository=new PostgresRoleLabelRepository(),logtoRolesProvider=null}={}){this.repository=repository;this.logtoRolesProvider=logtoRolesProvider;} async buildReadModel({organizationId,roles=[],members=[],memberRolesByUserId=new Map(),surface="owner"}){const canonical=canonicalRoles(); const resolved=await resolveEffectiveRoleLabels({organizationId,canonicalRoles:canonical,repository:this.repository}); const byKey=new Map(resolved.map((r)=>[r.canonicalRoleKey,r])); const diagnostics=[]; const counts=new Map(); const assigned=new Map(); const logtoRows=[]; for(const role of roles){const name=roleName(role), key=canonicalRoleKey(name), id=roleId(role); if(!organizationRoles.includes(key)){diagnostics.push({code:"logto_role_catalog_mapping_drift",severity:"warning",message:`Logto role ${id||"unknown"} could not be mapped to a Civitas organization role key.`}); continue;} counts.set(key,(counts.get(key)||0)+1); logtoRows.push({id,name,key});}
for(const [key,count] of counts) if(count>1) diagnostics.push({code:"logto_role_duplicate_canonical_key",severity:"warning",message:`Multiple Logto roles resolve to ${key}.`}); for(const key of organizationRoles) if(!counts.has(key)) diagnostics.push({code:"logto_role_missing_canonical_key",severity:"warning",message:`Canonical role ${key} is missing from the Logto organization template.`});
for(const user of members){const userId=user.id||user.userId||user.logtoUserId; if(!userId) continue; for(const role of memberRolesByUserId.get(userId)||[]){const key=canonicalRoleKey(roleName(role)); if(!assigned.has(key)) assigned.set(key,new Set()); assigned.get(key).add(userId);}}
const [globalVersion,organizationVersion,aliases]=await Promise.all([this.repository.getGlobalVersion(),this.repository.getOrganizationVersion(organizationId),this.repository.listOrganizationAliases(organizationId)]); for(const alias of aliases) if(!organizationRoles.includes(alias.canonicalRoleKey)) diagnostics.push({code:"stored_alias_unknown_canonical_role",severity:"warning",message:`Stored alias references unknown role ${alias.canonicalRoleKey}.`});
const byLogtoKey=new Map(logtoRows.map((r)=>[r.key,r])); const rows=organizationRoles.map((key)=>{const resolved=byKey.get(key); const logto=byLogtoKey.get(key)||{id:key,name:key,key}; return {logtoRoleId:logto.id,logtoRoleName:logto.name,canonicalRoleKey:key,canonicalBaselineLabel:resolved.canonicalBaselineLabel,civitasDefaultLabel:resolved.civitasDefaultLabel,organizationAlias:resolved.organizationAlias,effectiveLabel:resolved.effectiveLabel,source:resolved.source,assignedMemberCount:assigned.get(key)?.size||0,directRoleUserCount:assigned.get(key)?.size||0,canEditGlobalDefault:surface==="owner",canEditOrganizationAlias:surface==="tenant",globalVersion,organizationVersion,updatedAt:null,updatedBy:null};}); return {globalVersion,organizationVersion,organizationId,rows,diagnostics}; }
async updateGlobalLabel({canonicalRoleKey,displayName,expectedVersion,actorLogtoUserId,reason}){const role=assertRole(canonicalRoleKey), correlationId=crypto.randomUUID(); return this.repository.transaction(async(repo)=>{const current=await repo.getGlobalVersion({lock:true}); if(String(expectedVersion)!==String(current)) throw conflict("This role name was changed by another administrator.","role_label_version_stale",{currentVersion:current}); const normalized=normalizeRoleLabel(displayName,{allowNull:true}); const before=await repo.getGlobalOverride(canonicalRoleKey); const globals=await repo.getGlobalOverrides(); if(normalized){const dupe=globals.find((r)=>r.canonicalRoleKey!==canonicalRoleKey&&duplicateKey(r.displayName)===duplicateKey(normalized)); if(dupe) throw conflict("A Civitas default label already uses that name.","role_label_duplicate",{conflictingCanonicalRoleKey:dupe.canonicalRoleKey});}
const nextVersion=String(Number(current)+1); if(!normalized||duplicateKey(normalized)===duplicateKey(role.canonicalBaselineLabel)) await repo.deleteGlobalOverride(canonicalRoleKey); else await repo.upsertGlobalOverride({canonicalRoleKey,displayName:normalized,actorLogtoUserId,reason,version:nextVersion}); const committed=await repo.incrementGlobalVersion(); const audit=await repo.audit({eventType:(!normalized||duplicateKey(normalized)===duplicateKey(role.canonicalBaselineLabel))?"governance.civitas_role_label.reset":"governance.civitas_role_label.updated",scope:"global",canonicalRoleKey,actorLogtoUserId,reason,correlationId,metadata:{previousVisibleValue:before?.displayName||role.canonicalBaselineLabel,newVisibleValue:normalized||role.canonicalBaselineLabel,globalVersion:committed}}); const row=resolveEffectiveRoleLabel({canonicalRoleKey,canonicalBaselineLabel:role.canonicalBaselineLabel,globalOverrides:normalized?[{canonicalRoleKey,displayName:normalized}]:[],organizationAliases:[]}); return {version:committed,row,auditEventRef:audit,correlationId};});}
async updateOrganizationAlias({organizationId,canonicalRoleKey,logtoRoleIdSnapshot,displayName,expectedVersion,actorLogtoUserId,reason}){const role=assertRole(canonicalRoleKey), correlationId=crypto.randomUUID(); return this.repository.transaction(async(repo)=>{const [orgVersion,globals,aliases]=await Promise.all([repo.getOrganizationVersion(organizationId,{lock:true}),repo.getGlobalOverrides(),repo.listOrganizationAliases(organizationId)]); if(String(expectedVersion)!==String(orgVersion)) throw conflict("This role name was changed by another administrator.","role_label_version_stale",{currentVersion:orgVersion}); const normalized=normalizeRoleLabel(displayName,{allowNull:true}); const inherited=resolveEffectiveRoleLabel({canonicalRoleKey,canonicalBaselineLabel:role.canonicalBaselineLabel,globalOverrides:globals,organizationAliases:[]}).effectiveLabel; if(normalized){const dupe=aliases.find((r)=>r.canonicalRoleKey!==canonicalRoleKey&&duplicateKey(r.displayName)===duplicateKey(normalized)); if(dupe) throw conflict("An organization role alias already uses that name.","role_label_duplicate",{conflictingCanonicalRoleKey:dupe.canonicalRoleKey});}
const before=await repo.getOrganizationAlias(organizationId,canonicalRoleKey); if(!normalized||duplicateKey(normalized)===duplicateKey(inherited)) await repo.deleteOrganizationAlias(organizationId,canonicalRoleKey); else await repo.upsertOrganizationAlias({organizationId,canonicalRoleKey,logtoRoleIdSnapshot,displayName:normalized,actorLogtoUserId,reason,version:String(Number(orgVersion)+1)}); const committed=await repo.incrementOrganizationVersion(organizationId); const audit=await repo.audit({eventType:(!normalized||duplicateKey(normalized)===duplicateKey(inherited))?"governance.organization_role_alias.reset":"governance.organization_role_alias.updated",scope:"organization",organizationId,canonicalRoleKey,actorLogtoUserId,reason,correlationId,metadata:{logtoRoleIdSnapshot,previousVisibleValue:before?.displayName||inherited,newVisibleValue:normalized||inherited,organizationVersion:committed}}); const row=resolveEffectiveRoleLabel({organizationId,canonicalRoleKey,canonicalBaselineLabel:role.canonicalBaselineLabel,globalOverrides:globals,organizationAliases:normalized?[{canonicalRoleKey,displayName:normalized}]:[]}); return {version:committed,row,auditEventRef:audit,correlationId};});}}
module.exports={RoleLabelService,canonicalRoles,canonicalRoleKey,roleId,roleName};
