"use strict";
const { randomUUID } = require("node:crypto");
const { structureError, ORGANIZATION_STRUCTURE_REASON_CODES: C } = require("./organizationStructureReasonCodes");
const cols = `id,logto_organization_id as "logtoOrganizationId",hierarchy_key as "hierarchyKey",unit_type as "unitType",stable_key as "stableKey",display_name as "displayName",description,parent_unit_id as "parentUnitId",dimension_value_id as "dimensionValueId",management_level as "managementLevel",status,sort_order as "sortOrder",metadata,created_by_logto_user_id as "createdByLogtoUserId",updated_by_logto_user_id as "updatedByLogtoUserId",created_at as "createdAt",updated_at as "updatedAt"`;
function createPostgresUnitRepository({ pool, client }={}) {
 const db=client||pool;if(!db?.query)throw new Error("postgres_pool_required"); const repo={
 async transaction(fn){if(client)return fn(repo);const tx=await pool.connect();try{await tx.query("begin");const result=await fn(createPostgresUnitRepository({pool,client:tx}));await tx.query("commit");return result}catch(error){await tx.query("rollback");throw error}finally{tx.release()}},
 async getVersions(org){const r=await db.query(`select logto_organization_id as "logtoOrganizationId",unit_graph_version::bigint as "unitGraphVersion",membership_version::bigint as "membershipVersion",audience_version::bigint as "audienceVersion" from organization_structure_versions where logto_organization_id=$1`,[org]);return r.rows[0]||{logtoOrganizationId:org,unitGraphVersion:0,membershipVersion:0,audienceVersion:0}},
 async saveVersions(v){const r=await db.query(`insert into organization_structure_versions(logto_organization_id,unit_graph_version,membership_version,audience_version,updated_by_logto_user_id,reason) values($1,$2,$3,$4,$5,$6) on conflict(logto_organization_id) do update set unit_graph_version=excluded.unit_graph_version,membership_version=excluded.membership_version,audience_version=excluded.audience_version,updated_by_logto_user_id=excluded.updated_by_logto_user_id,reason=excluded.reason,updated_at=now() where organization_structure_versions.unit_graph_version=excluded.unit_graph_version-1 returning logto_organization_id as "logtoOrganizationId",unit_graph_version::bigint as "unitGraphVersion",membership_version::bigint as "membershipVersion",audience_version::bigint as "audienceVersion"`,[v.logtoOrganizationId,v.unitGraphVersion,v.membershipVersion,v.audienceVersion,v.updatedByLogtoUserId||null,v.reason||null]);if(!r.rows[0])throw structureError(C.STRUCTURE_VERSION_CONFLICT);return r.rows[0]},
 async insertUnit(x){const r=await db.query(`insert into organization_units(logto_organization_id,hierarchy_key,unit_type,stable_key,display_name,description,parent_unit_id,dimension_value_id,management_level,status,sort_order,metadata,created_by_logto_user_id,updated_by_logto_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning ${cols}`,[x.logtoOrganizationId,x.hierarchyKey,x.unitType,x.stableKey,x.displayName,x.description||null,x.parentUnitId||null,x.dimensionValueId||null,x.managementLevel,x.status||"draft",x.sortOrder||0,x.metadata||{},x.createdByLogtoUserId,x.updatedByLogtoUserId]);return r.rows[0]},
 async updateUnit(id,patch){const map={displayName:"display_name",description:"description",parentUnitId:"parent_unit_id",managementLevel:"management_level",status:"status",sortOrder:"sort_order",metadata:"metadata",updatedByLogtoUserId:"updated_by_logto_user_id"};const es=Object.entries(patch).filter(([k])=>map[k]);if(!es.length)return repo.getUnit(id);const r=await db.query(`update organization_units set ${es.map(([k],i)=>`${map[k]}=$${i+2}`).join(",")},updated_at=now() where id=$1 returning ${cols}`,[id,...es.map(([,v])=>v)]);return r.rows[0]||null},
 async getUnit(id){const r=await db.query(`select ${cols} from organization_units where id=$1`,[id]);return r.rows[0]||null},
 async findUnitByStableKey({organizationId,stableKey}){const r=await db.query(`select ${cols} from organization_units where logto_organization_id=$1 and stable_key=$2`,[organizationId,stableKey]);return r.rows[0]||null},
 async listUnits({organizationId,status}={}){const r=await db.query(`select ${cols} from organization_units where ($1::text is null or logto_organization_id=$1) and ($2::text is null or status=$2) order by sort_order,display_name`,[organizationId||null,status||null]);return r.rows},
 async childrenOf(id){const r=await db.query(`select ${cols} from organization_units where parent_unit_id=$1`,[id]);return r.rows},
 async ancestorsOf(id){const r=await db.query(`with recursive a as(select p.* from organization_units u join organization_units p on p.id=u.parent_unit_id where u.id=$1 union all select p.* from organization_units p join a on p.id=a.parent_unit_id) select ${cols} from a`,[id]);return r.rows},
 async listMemberships({organizationId,unitId}={}){const r=await db.query(`select status from organization_unit_memberships where ($1::text is null or logto_organization_id=$1) and ($2::uuid is null or unit_id=$2)`,[organizationId||null,unitId||null]);return r.rows},
 async recordOutbox(e){const id=randomUUID();await db.query(`insert into authorization_outbox_events(id,event_type,aggregate_type,aggregate_id,event_version,logto_organization_id,subject_logto_user_id,payload) values($1,$2,'organization_unit',$3,$4,$5,$6,$7)`,[id,e.eventType,e.unitId||e.organizationId,String(e.structureVersions?.unitGraphVersion||0),e.organizationId,e.actorLogtoUserId||null,e]);return {...e,id}},
 async audit(e){const r=await db.query(`insert into organization_structure_audit_events(logto_organization_id,actor_logto_user_id,action,unit_id,structure_version,details) values($1,$2,$3,$4,$5,$6) returning id`,[e.organizationId,e.actorLogtoUserId||null,e.action,e.unitId||null,e.structureVersions?.unitGraphVersion||null,e]);return {...e,id:r.rows[0].id}}
 };return repo;
}
module.exports={createPostgresUnitRepository};
