"use strict";
const crypto=require("node:crypto");
const {relationshipRegistry}=require("../../core/organization-mapping/registries.cjs");
function canonicalize(value){if(Array.isArray(value))return value.map(canonicalize);if(value&&typeof value==="object")return Object.fromEntries(Object.keys(value).sort().map((key)=>[key,canonicalize(value[key])]));return value;}
function fail(code,details={}){const error=new Error(code);error.code=code;error.status=422;error.details=details;throw error;}
function projectionHash(value){return crypto.createHash("sha256").update(JSON.stringify(canonicalize(value)??null)).digest("hex");}
function buildOrganizationGraph(model={},options={}){
 const nodes=[...(model.nodes||[])].map((node)=>({id:String(node.id),organizationId:node.organizationId||model.organizationId||null,kind:String(node.kind||"node"),status:node.status||"active",structureBehavior:node.structureBehavior||null,canonicalBinding:canonicalize(node.canonicalBinding||null),label:String(node.label||node.id),facets:canonicalize(node.facets||{}),provenance:canonicalize(node.provenance||{})})).sort((a,b)=>a.id.localeCompare(b.id));
 if(new Set(nodes.map((node)=>node.id)).size!==nodes.length)fail("mapping_structure_duplicate_node");if(options.forPublication&&nodes.some((node)=>node.status!=="active"))fail("mapping_structure_inactive_target");const byId=new Map(nodes.map((node)=>[node.id,node]));
 const edges=[...(model.edges||[])].map((edge)=>({from:String(edge.from),to:String(edge.to),relationship:String(edge.relationship),organizationId:edge.organizationId||model.organizationId||null,facets:canonicalize(edge.facets||{}),provenance:canonicalize(edge.provenance||{})})).sort((a,b)=>`${a.from}:${a.to}:${a.relationship}`.localeCompare(`${b.from}:${b.to}:${b.relationship}`));
 for(const edge of edges){if(!relationshipRegistry.get(edge.relationship))fail("mapping_structure_relationship_unknown",{relationship:edge.relationship});if(!byId.has(edge.from)||!byId.has(edge.to))fail("mapping_structure_orphan_edge",{from:edge.from,to:edge.to});if(edge.from===edge.to)fail("mapping_structure_cycle",{nodeId:edge.from});const organizations=[model.organizationId,edge.organizationId,byId.get(edge.from).organizationId,byId.get(edge.to).organizationId].filter(Boolean);if(organizations.some((id)=>id!==organizations[0]))fail("mapping_structure_cross_tenant_reference");}
 const core={modelVersion:model.modelVersion||null,nodes,edges};return Object.freeze({...core,hash:projectionHash(core)});
}
function buildPrimaryScopeTree(model={},options={}){
 const graph=buildOrganizationGraph(model,options),hierarchy=graph.edges.filter((edge)=>relationshipRegistry.get(edge.relationship)?.hierarchy),participantIds=new Set(hierarchy.flatMap((edge)=>[edge.from,edge.to]));for(const node of graph.nodes)if(node.structureBehavior==="hierarchy_axis"||node.kind==="organization")participantIds.add(node.id);if(!participantIds.size&&graph.nodes.length===1)participantIds.add(graph.nodes[0].id);
 const hierarchyNodes=graph.nodes.filter((node)=>participantIds.has(node.id)),children=new Map(hierarchyNodes.map((node)=>[node.id,[]])),targets=new Set();for(const edge of hierarchy){children.get(edge.from).push(edge.to);targets.add(edge.to);}const roots=hierarchyNodes.filter((node)=>!targets.has(node.id));if(hierarchyNodes.length&&roots.length!==1)fail("mapping_structure_root_count_invalid",{rootCount:roots.length});
 const visiting=new Set(),visited=new Set();function visit(id){if(visiting.has(id))fail("mapping_structure_cycle",{nodeId:id});visiting.add(id);const result={id,children:(children.get(id)||[]).sort().map(visit)};visiting.delete(id);visited.add(id);return result;}const root=roots[0]?visit(roots[0].id):null;if(visited.size!==hierarchyNodes.length)fail("mapping_structure_orphan_node");const overlays=graph.nodes.filter((node)=>!participantIds.has(node.id)).map((node)=>node.id).sort(),paths=[];function collectPaths(node,path=[]){if(!node)return;const next=[...path,node.id];paths.push({nodeId:node.id,path:next});for(const child of node.children)collectPaths(child,next);}collectPaths(root);const outsideHierarchy=graph.edges.filter(edge=>!relationshipRegistry.get(edge.relationship)?.hierarchy).map(edge=>({from:edge.from,to:edge.to,relationship:edge.relationship}));const tree={modelVersion:model.modelVersion||null,root,overlayNodeIds:overlays,paths,outsideHierarchy};return Object.freeze({...tree,hash:projectionHash(tree)});
}
function buildReusableFacets(model={}){return Object.freeze([...(model.facets||[])].map(canonicalize).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))));}
function buildReconciliationWorkItems({organizationId,publicationId,previousGraph,newGraph,previousModel={},newModel={}}){if(!previousGraph)return Object.freeze([]);const priorNodes=new Map((previousGraph.nodes||[]).map((node)=>[node.id,node])),nextNodes=new Map((newGraph.nodes||[]).map((node)=>[node.id,node])),priorEdges=new Map((previousGraph.edges||[]).map((edge)=>[`${edge.from}:${edge.to}:${edge.relationship}`,edge])),nextEdges=new Map((newGraph.edges||[]).map((edge)=>[`${edge.from}:${edge.to}:${edge.relationship}`,edge])),items=[];const add=(targetType,targetId,impactClassification,reason)=>items.push({targetType,targetId,impactClassification,reason});for(const [id,oldNode]of priorNodes){const next=nextNodes.get(id);if(!next)add("organization_model_node",id,"revalidation_required","archived_value");else if(projectionHash(oldNode.canonicalBinding)!==projectionHash(next.canonicalBinding))add("organization_model_node",id,"assignment_invalid","changed_canonical_binding");else if(projectionHash(oldNode.provenance)!==projectionHash(next.provenance))add("organization_model_node",id,"source_relationship_stale","invalidated_source_provenance");else if(oldNode.status!==next.status)add("organization_model_node",id,next.status==="active"?"broadening_possible":"narrowing_possible","status_changed");}for(const [key,oldEdge]of priorEdges){const next=nextEdges.get(key);if(!next)add("organization_model_relationship",key,"source_relationship_stale","removed_relationship");else if(projectionHash(oldEdge.provenance)!==projectionHash(next.provenance))add("organization_model_relationship",key,"source_relationship_stale","relationship_provenance_changed");}if(projectionHash(previousModel.dimensionConfigurations||[])!==projectionHash(newModel.dimensionConfigurations||[]))add("dimension_configuration","all","manual_review_required","dimension_configuration_changed");return Object.freeze(items.map((item)=>Object.freeze({organizationId,publicationId,...item,status:"pending",grantsAccess:false})).sort((a,b)=>`${a.targetType}:${a.targetId}:${a.reason}`.localeCompare(`${b.targetType}:${b.targetId}:${b.reason}`)));}
module.exports={canonicalize,projectionHash,buildOrganizationGraph,buildPrimaryScopeTree,buildReusableFacets,buildReconciliationWorkItems};
