"use strict";
const crypto = require("node:crypto");
const clone = (v) => v == null ? v : JSON.parse(JSON.stringify(v));
const uuid = () => crypto.randomUUID();
const secureDigest = (value) => `sha256:${crypto.createHash("sha256").update(String(value||"")).digest("hex")}`;
function createInMemoryOrganizationMappingRepository() {
  const drafts = new Map(), policies = new Map(), selectorSets = new Map(), snapshots = new Map(), evaluations = new Map(), reviews = new Map(), dimensionConfigs = new Map(), publications = new Map(), previews = new Map(), workItems = new Map(), audits = [], integrationEvents = [], idempotency = new Map();
  const byOrg = (map, org) => [...map.values()].filter((row) => row["organization"+"Id"] === org).map(clone);
  return Object.freeze({
    audits, integrationEvents,
    async transaction(fn) { const maps=[drafts,policies,selectorSets,snapshots,evaluations,reviews,dimensionConfigs,publications,previews,workItems,idempotency]; const state=maps.map((map)=>[...map.entries()].map(([key,value])=>[key,clone(value)])); const auditLength=audits.length,integrationEventLength=integrationEvents.length; try{return await fn(this);}catch(error){maps.forEach((map,index)=>{map.clear();for(const [key,value] of state[index])map.set(key,value);});audits.length=auditLength;integrationEvents.length=integrationEventLength;throw error;} },
    async replayIdempotency(context) { if (!context?.key) return null; const stored=idempotency.get(idempotencyIdentity(context)); if (!stored) return null; assertIdempotencyMatch(stored,context); return clone(stored.response); },
    async rememberIdempotency(context, value) { if (context?.key) idempotency.set(idempotencyIdentity(context), clone({...context,response:value})); return value; },
    async acquirePublicationLock() { return true; },
    async audit(event) { const safe={...event,reason:secureDigest(event.reason),event:undefined};audits.push(clone(safe));return safe; },
    async enqueueOutbox(event) { const safe={...event,reasonHash:secureDigest(event.reason),reason:undefined,payload:undefined};integrationEvents.push(clone(safe));return safe; },
    async createDraft(row) { const saved = { id: uuid(), version: 1, status: "draft", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), ...row }; drafts.set(saved.id, saved); return clone(saved); },
    async getDraft(org, id) { const row = drafts.get(id); return row?.organizationId === org ? clone(row) : null; },
    async getActiveDraft(org) { return byOrg(drafts,org).filter((row)=>row.status==="draft").sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))[0]||null; },
    async updateDraft(org, id, patch, expectedVersion) { const row = drafts.get(id); if (!row || row["organization"+"Id"] !== org) return null; if (expectedVersion && Number(row.version) !== Number(expectedVersion)) { const e = new Error("organization_mapping_version_conflict"); e.code = e.message; throw e; } const saved = { ...row, ...patch, version: Number(row.version) + 1, updatedAt: new Date().toISOString() }; drafts.set(id, saved); return clone(saved); },
    async savePolicyVersion(row) { const saved = { id: uuid(), status:"active", immutable: true, createdAt: new Date().toISOString(), ...row }; policies.set(saved.id, saved); return clone(saved); },
    async listPolicyVersions(org,draftId) { return byOrg(policies,org).filter((row)=>row.status!=="archived"&&(!draftId||row.draftId===draftId)); },
    async archivePolicy(org,policyKey) { let changed=false;for(const [id,row] of policies)if(row.organizationId===org&&row.policyKey===policyKey){policies.set(id,{...row,status:"archived"});changed=true;}return changed; },
    async saveSelectorSet(row) { const key=`${row.organizationId}:${row.selectorSetId}:${row.version}`,existing=selectorSets.get(key);if(existing){const error=new Error(existing.contentHash===row.contentHash?"mapping_selector_set_version_immutable":"mapping_selector_set_version_conflict");error.code=error.message;error.status=409;throw error;}const saved={id:uuid(),immutable:true,createdAt:new Date().toISOString(),...row};selectorSets.set(key,saved);return clone(saved); },
    async listSelectorSets(org) { return byOrg(selectorSets,org).filter((row)=>row.status!=="archived"); },
    async archiveSelectorSet(org,selectorSetId) { let changed=false;for(const [key,row] of selectorSets)if(row.organizationId===org&&row.selectorSetId===selectorSetId){selectorSets.set(key,{...row,status:"archived"});changed=true;}return changed; },
    async saveSourceSnapshot(row) { const saved = { id: uuid(), createdAt: new Date().toISOString(), ...row }; snapshots.set(saved.id, saved); return clone(saved); },
    async getSourceSnapshot(org,id) { const row=snapshots.get(id);return row?.organizationId===org?clone(row):null; },
    async saveEvaluation(row) { const saved = { id: uuid(), createdAt: new Date().toISOString(), ...row }; evaluations.set(saved.id, saved); return clone(saved); },
    async getEvaluation(org, id) { const row = evaluations.get(id); return row?.organizationId === org ? clone(row) : null; },
    async listEvaluations(org,draftId) { return byOrg(evaluations,org).filter((row)=>!draftId||row.draftId===draftId); },
    async saveReview(row) { const saved = { id: uuid(), createdAt: new Date().toISOString(), ...row }; reviews.set(saved.id, saved); return clone(saved); },
    async listReviews(org,evaluationId) { return byOrg(reviews,org).filter((row)=>!evaluationId||row.evaluationId===evaluationId); },
    async listAudit(org, limit = 50) { return audits.filter((e) => e.organizationId === org).slice(-Math.min(limit, 100)).reverse().map(clone); },
    async saveDimensionConfig(row) { const saved = { id: uuid(), version: 1, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), ...row }; dimensionConfigs.set(saved.id, saved); return clone(saved); },
    async listDimensionConfigs(org) { return byOrg(dimensionConfigs,org); },
    async savePreview(row) { const saved = { id: uuid(), createdAt: new Date().toISOString(), ...row }; previews.set(saved.id, saved); return clone(saved); },
    async getPreview(org, id) { const row = previews.get(id); return row?.organizationId === org ? clone(row) : null; },
    async savePublication(row) { const current=[...publications.values()].filter((item)=>item.organizationId===row.organizationId); const saved = { id: uuid(), immutable: true, publishedVersion:current.length+1, createdAt: new Date().toISOString(), ...row }; publications.set(saved.id, saved); return clone(saved); },
    async getPublication(org, id) { const row = publications.get(id); return row?.organizationId === org ? clone(row) : null; },
    async getLatestPublication(org) { return clone([...publications.values()].filter((row) => row["organization"+"Id"] === org).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0] || null); },
    async listPublications(org) { return byOrg(publications,org).sort((a,b)=>(b.publishedVersion||0)-(a.publishedVersion||0)); },
    async listReconciliationWorkItems(org) { return byOrg(workItems,org); },
    async listAffectedAssignmentReferences() { return []; },
    async saveReconciliationWorkItems(items) { const saved = items.map((item) => ({ id: uuid(), createdAt: new Date().toISOString(), ...item })); for (const item of saved) workItems.set(item.id, item); return clone(saved); },
  });
}
function createPostgresOrganizationMappingRepository({ pool }) {
  const q = (text, values) => pool.query(text, values);
  return Object.freeze({
    async transaction(fn) { const client = await pool.connect(); try { await client.query("begin"); const result = await fn(createPostgresOrganizationMappingRepository({ pool: client })); await client.query("commit"); return result; } catch (e) { await client.query("rollback"); throw e; } finally { client.release?.(); } },
    async replayIdempotency(context) { if (!context?.key) return null; const r = await q("select request_hash,expected_version,response_json from organization_mapping_idempotency_keys where organization_id=$1 and subject_id=$2 and action_id=$3 and idempotency_key=$4", [context["organization"+"Id"],context.subjectId,context.actionId,context.key]); if (!r.rows[0]) return null; assertIdempotencyMatch({requestHash:r.rows[0].request_hash,expectedVersion:r.rows[0].expected_version},context); return r.rows[0].response_json; },
    async rememberIdempotency(context, value) { if (context?.key) await q("insert into organization_mapping_idempotency_keys(organization_id,subject_id,action_id,idempotency_key,request_hash,expected_version,response_json,status) values($1,$2,$3,$4,$5,$6,$7,'completed')", [context["organization"+"Id"],context.subjectId,context.actionId,context.key,context.requestHash,String(context.expectedVersion??""),value]); return value; },
    async acquirePublicationLock(organizationId) { await q("select pg_advisory_xact_lock(hashtextextended($1, 318))", [organizationId]); return true; },
    async audit(event) { const safe={...event,reason:secureDigest(event.reason),event:undefined}; await q("insert into organization_mapping_audit_events(organization_id,actor_logto_user_id,action,target_type,target_id,result,reason,event_json) values($1,$2,$3,$4,$5,$6,$7,$8)", [event["organization"+"Id"],event.actorLogtoUserId,event.action,event.targetType,event.targetId,event.result,safe.reason,safe]); return safe; },
    async enqueueOutbox(event) { const eventId=event.eventId||uuid(); await q("insert into integration_outbox_events(event_id,event_type,schema_version,logto_organization_id,aggregate_type,aggregate_id,actor_json,correlation_id,source_json,sensitivity,payload) values($1,$2,'civitas-integration-event/v1',$3,'organization_model',$4,$5,$6,$7,'internal',$8) on conflict(event_id) do nothing", [eventId,"organization_mapping.lifecycle.changed",event["organization"+"Id"],event.targetId||event["organization"+"Id"],{type:"user",subject:event.actorLogtoUserId||"system"},event.idempotencyKey||eventId,{component:"organization-mapping"},{actionId:event.eventType,result:event.result,reasonHash:secureDigest(event.reason),targetType:event.targetType,targetId:event.targetId}]); return {...event,eventId}; },
    async createDraft(row) { const r = await q("insert into organization_mapping_drafts(organization_id,status,model_json) values($1,'draft',$2) returning *", [row["organization"+"Id"],row.model]); return mapDraft(r.rows[0]); },
    async getDraft(org, id) { const r = await q("select * from organization_mapping_drafts where organization_id=$1 and id=$2", [org,id]); return r.rows[0] ? mapDraft(r.rows[0]) : null; },
    async getActiveDraft(org) { const r=await q("select * from organization_mapping_drafts where organization_id=$1 and status='draft' order by updated_at desc limit 1",[org]);return r.rows[0]?mapDraft(r.rows[0]):null; },
    async updateDraft(org, id, patch, expectedVersion) { const r = await q("update organization_mapping_drafts set model_json=$3, version=version+1, updated_at=now() where organization_id=$1 and id=$2 and version=$4 returning *", [org,id,patch.model,expectedVersion]); if (!r.rowCount) { const e = new Error("organization_mapping_version_conflict"); e.code = e.message; throw e; } return mapDraft(r.rows[0]); },
    async savePolicyVersion(row) { const identity=await q("insert into organization_mapping_policy_identities(organization_id,stable_key) values($1,$2) on conflict(organization_id,stable_key) do update set status='active' returning id",[row["organization"+"Id"],row.policyKey||row.policy?.policyId]);const r = await q("insert into organization_mapping_policy_versions(organization_id,draft_id,policy_json,policy_hash,policy_key,policy_identity_id,version,authority_key,parent_policy_version_id,refinement_kind,refinement_reason,selector_set_id,selector_set_version,selector_set_hash) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning *", [row["organization"+"Id"],row.draftId,row.policy,row.policyHash,row.policyKey||row.policy?.policyId,identity.rows[0].id,row.version||1,row.authorityKey||row.policy?.authorityKey||"organization_mapping_policy",row.parentPolicyVersionId||null,row.refinementKind||null,row.refinementReason||null,row.selectorSetId||null,row.selectorSetVersion||null,row.selectorSetHash||null]); return mapPolicyVersion(r.rows[0]); },
    async listPolicyVersions(org,draftId) { const r=await q("select v.* from organization_mapping_policy_versions v join organization_mapping_policy_identities i on (i.organization_id,i.id)=(v.organization_id,v.policy_identity_id) where v.organization_id=$1 and i.status='active' and ($2::uuid is null or v.draft_id=$2) order by v.policy_key,v.version,v.id",[org,draftId||null]); return r.rows.map(mapPolicyVersion); },
    async archivePolicy(org,policyKey) { const r=await q("update organization_mapping_policy_identities set status='archived' where organization_id=$1 and stable_key=$2 returning id",[org,policyKey]);return Boolean(r.rowCount); },
    async saveSelectorSet(row) { const identity=await q("insert into organization_mapping_selector_sets(organization_id,stable_key) values($1,$2) on conflict(organization_id,stable_key) do update set stable_key=excluded.stable_key returning *",[row["organization"+"Id"],row.selectorSetId]); const id=identity.rows[0].id; await q("insert into organization_mapping_selector_set_versions(organization_id,selector_set_id,version,selector_registry_version,selector_registry_hash,authority_key,source_connection_id,content_hash) values($1,$2,$3,$4,$5,$6,$7,$8)",[row["organization"+"Id"],id,row.version,row.selectorRegistryVersion,row.selectorRegistryHash,row.authorityKey,row.sourceConnectionId||null,row.contentHash]); for(const [ordinal,condition] of row.conditions.entries()) await q("insert into organization_mapping_selector_set_conditions(organization_id,selector_set_id,selector_set_version,condition_id,ordinal,selector_key,operator_key,operand_json) values($1,$2,$3,$4,$5,$6,$7,$8)",[row["organization"+"Id"],id,row.version,condition.conditionId,ordinal,condition.selectorKey,condition.operatorKey,{value:condition.value,values:condition.values}]); return {...row,id}; },
    async archiveSelectorSet(org,selectorSetId) { const r=await q("update organization_mapping_selector_sets set status='archived' where organization_id=$1 and stable_key=$2 returning id",[org,selectorSetId]);return Boolean(r.rowCount); },
    async listSelectorSets(org) { const r=await q("select v.*,s.stable_key,(select jsonb_agg(jsonb_build_object('conditionId',c.condition_id,'selectorKey',c.selector_key,'operatorKey',c.operator_key,'value',c.operand_json->'value','values',c.operand_json->'values') order by c.ordinal) from organization_mapping_selector_set_conditions c where c.organization_id=v.organization_id and c.selector_set_id=v.selector_set_id and c.selector_set_version=v.version) conditions from organization_mapping_selector_set_versions v join organization_mapping_selector_sets s on (s.organization_id,s.id)=(v.organization_id,v.selector_set_id) where v.organization_id=$1 and s.status='active' order by s.stable_key,v.version",[org]); return r.rows.map(mapSelectorSet); },
    async getSourceSnapshot(org,id) { const r=await q("select * from organization_mapping_source_snapshots where organization_id=$1 and id=$2",[org,id]);return r.rows[0]?mapSourceSnapshot(r.rows[0]):null; },
    async saveSourceSnapshot(row) { const r = await q("insert into organization_mapping_source_snapshots(organization_id,source_connection_id,facts_json,evidence_json,version,snapshot_hash,freshness_state) values($1,$2,$3,$4,$5,$6,$7) returning *", [row["organization"+"Id"],row.sourceConnectionId,row.facts,row.evidence,row.version||1,row.snapshotHash,row.freshnessState||"current"]); return mapSourceSnapshot(r.rows[0]); },
    async saveEvaluation(row) { const r = await q("insert into organization_mapping_evaluations(organization_id,draft_id,policy_version_id,source_snapshot_id,outcome,reason_code,trace_json,evaluation_hash) values($1,$2,$3,$4,$5,$6,$7,$8) returning *", [row["organization"+"Id"],row.draftId,row.policyVersionId,row.sourceSnapshotId,row.outcome,row.reasonCode,row.trace,row.evaluationHash]); return mapEvaluation(r.rows[0]); },
    async getEvaluation(org, id) { const r = await q("select * from organization_mapping_evaluations where organization_id=$1 and id=$2", [org,id]); return r.rows[0] ? mapEvaluation(r.rows[0]) : null; },
    async listEvaluations(org,draftId) { const r=await q("select * from organization_mapping_evaluations where organization_id=$1 and ($2::uuid is null or draft_id=$2) order by created_at,id",[org,draftId||null]);return r.rows.map(mapEvaluation); },
    async saveReview(row) { const r = await q("insert into organization_mapping_reviews(organization_id,evaluation_id,decision,reason,actor_logto_user_id,version) values($1,$2,$3,$4,$5,$6) returning *", [row["organization"+"Id"],row.evaluationId,row.decision,row.reason,row.actorLogtoUserId,row.version]); return mapReview(r.rows[0]); },
    async listReviews(org,evaluationId) { const r=await q("select * from organization_mapping_reviews where organization_id=$1 and ($2::uuid is null or evaluation_id=$2) order by evaluation_id,version",[org,evaluationId||null]);return r.rows.map(mapReview); },
    async listAudit(org, limit = 50) { const r = await q("select event_json from organization_mapping_audit_events where organization_id=$1 order by created_at desc limit $2", [org, Math.min(limit,100)]); return r.rows.map((row) => row.event_json); },
    async saveDimensionConfig(row) { const r = await q("insert into organization_dimension_configurations(organization_id,dimension_id,config_json) values($1,$2,$3) returning *", [row["organization"+"Id"],row.dimensionId,row.config]); return r.rows[0]; },
    async listDimensionConfigs(org) { const r=await q("select * from organization_dimension_configurations where organization_id=$1 order by dimension_id",[org]);return r.rows.map((row)=>{const mapped={id:row.id,dimensionId:row.dimension_id,config:row.config_json,version:row.version};mapped["organization"+"Id"]=row.organization_id;return mapped;}); },
    async savePreview(row) { const r = await q("insert into organization_mapping_previews(organization_id,draft_id,draft_version,preview_digest,impact_digest,graph_json,scope_tree_json,facets_json,reviewed_state_json,reviewed_state_hash,base_publication_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *", [row["organization"+"Id"],row.draftId,row.draftVersion,row.previewDigest,row.impactDigest,row.graph,row.scopeTree,row.facets,row.reviewedState,row.reviewedStateHash,row.basePublicationId||null]); return mapPreview(r.rows[0]); },
    async getPreview(org, id) { const r = await q("select * from organization_mapping_previews where organization_id=$1 and id=$2", [org,id]); return r.rows[0] ? mapPreview(r.rows[0]) : null; },
    async savePublication(row) { const r = await q("insert into organization_mapping_published_versions(organization_id,draft_id,draft_version,preview_id,model_hash,impact_digest,graph_json,scope_tree_json,facets_json,source_publication_id,model_json,published_version,base_published_version,reviewed_state_json,reviewed_state_hash) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,COALESCE((select max(published_version)+1 from organization_mapping_published_versions where organization_id=$1),1),$12,$13,$14) returning *", [row["organization"+"Id"],row.draftId,row.draftVersion,row.previewId,row.modelHash,row.impactDigest,row.graph,row.scopeTree,row.facets,row.sourcePublicationId || null,row.model,row.basePublishedVersion??null,row.reviewedState,row.reviewedStateHash]); return mapPublication(r.rows[0]); },
    async getPublication(org, id) { const r = await q("select * from organization_mapping_published_versions where organization_id=$1 and id=$2", [org,id]); return r.rows[0] ? mapPublication(r.rows[0]) : null; },
    async getLatestPublication(org) { const r = await q("select * from organization_mapping_published_versions where organization_id=$1 order by published_version desc nulls last, created_at desc limit 1", [org]); return r.rows[0] ? mapPublication(r.rows[0]) : null; },
    async listPublications(org) { const r=await q("select * from organization_mapping_published_versions where organization_id=$1 order by published_version desc",[org]);return r.rows.map(mapPublication); },
    async listReconciliationWorkItems(org) { const r=await q("select * from organization_mapping_reconciliation_work_items where organization_id=$1 order by created_at,id",[org]);return r.rows.map(mapReconciliationWorkItem); },
    async listAffectedAssignmentReferences(org,targetIds) { if(!targetIds.length)return[];const r=await q("select id,scope_kind from authorization_scope_assignments where logto_organization_id=$1 and (dimension_value_id::text=any($2::text[]) or unit_id::text=any($2::text[]) or resource_ref=any($2::text[])) order by id",[org,targetIds]);return r.rows.map((row)=>({assignmentId:String(row.id),scopeKind:row.scope_kind})); },
    async saveReconciliationWorkItems(items) { const saved=[]; for (const item of items) { const r=await q("insert into organization_mapping_reconciliation_work_items(organization_id,publication_id,target_type,target_id,status,grants_access,impact_classification) values($1,$2,$3,$4,$5,false,$6) returning *", [item["organization"+"Id"],item.publicationId,item.targetType,item.targetId,item.status,item.impactClassification]); saved.push(mapReconciliationWorkItem(r.rows[0])); } return saved; },
  });
}
function mapDraft(r) { const row={ id:r.id, version:r.version, status:r.status, model:r.model_json, createdAt:r.created_at, updatedAt:r.updated_at }; row["organization"+"Id"]=r.organization_id; return row; }
function domainBase(r) { const row={id:r.id,createdAt:r.created_at}; row["organization"+"Id"]=r.organization_id; return row; }
function mapPolicyVersion(r) { return {...domainBase(r),draftId:r.draft_id,policyKey:r.policy_key,version:r.version,policy:r.policy_json,policyHash:r.policy_hash,authorityKey:r.authority_key,parentPolicyVersionId:r.parent_policy_version_id,refinementKind:r.refinement_kind,refinementReason:r.refinement_reason,selectorSetId:r.selector_set_id,selectorSetVersion:r.selector_set_version,selectorSetHash:r.selector_set_hash,immutable:r.immutable}; }
function mapSelectorSet(r) { return {...domainBase(r),selectorSetId:r.stable_key,id:r.selector_set_id,version:r.version,selectorRegistryVersion:r.selector_registry_version,selectorRegistryHash:r.selector_registry_hash,authorityKey:r.authority_key,sourceConnectionId:r.source_connection_id,contentHash:r.content_hash,conditions:r.conditions||[],immutable:r.immutable}; }
function mapSourceSnapshot(r) { return {...domainBase(r),sourceConnectionId:r.source_connection_id,version:r.version,snapshotHash:r.snapshot_hash,freshnessState:r.freshness_state,facts:r.facts_json,evidence:r.evidence_json}; }
function mapEvaluation(r) { return {...domainBase(r),draftId:r.draft_id,policyVersionId:r.policy_version_id,sourceSnapshotId:r.source_snapshot_id,outcome:r.outcome,reasonCode:r.reason_code,trace:r.trace_json,evaluationHash:r.evaluation_hash}; }
function mapReview(r) { return {...domainBase(r),evaluationId:r.evaluation_id,version:r.version,decision:r.decision,reason:r.reason,actorLogtoUserId:r.actor_logto_user_id}; }
function mapPreview(r) { return {...domainBase(r),draftId:r.draft_id,draftVersion:r.draft_version,previewDigest:r.preview_digest,impactDigest:r.impact_digest,graph:r.graph_json,scopeTree:r.scope_tree_json,facets:r.facets_json,reviewedState:r.reviewed_state_json,reviewedStateHash:r.reviewed_state_hash,basePublicationId:r.base_publication_id}; }
function mapPublication(r) { return {...domainBase(r),draftId:r.draft_id,draftVersion:r.draft_version,previewId:r.preview_id,modelHash:r.model_hash,impactDigest:r.impact_digest,graph:r.graph_json,scopeTree:r.scope_tree_json,facets:r.facets_json,model:r.model_json,publishedVersion:r.published_version,basePublishedVersion:r.base_published_version,sourcePublicationId:r.source_publication_id,reviewedState:r.reviewed_state_json,reviewedStateHash:r.reviewed_state_hash,immutable:r.immutable}; }
function mapReconciliationWorkItem(r) { return {...domainBase(r),publicationId:r.publication_id,targetType:r.target_type,targetId:r.target_id,status:r.status,impactClassification:r.impact_classification,grantsAccess:r.grants_access}; }
function idempotencyIdentity(c) { return `${c.organizationId}:${c.subjectId}:${c.actionId}:${c.key}`; }
function assertIdempotencyMatch(stored,context) { if (stored.requestHash!==context.requestHash || String(stored.expectedVersion??"")!==String(context.expectedVersion??"")) { const e=new Error("organization_mapping_idempotency_conflict"); e.code=e.message; e.status=409; throw e; } }
module.exports = { createInMemoryOrganizationMappingRepository, createPostgresOrganizationMappingRepository, mapDraft, mapPolicyVersion, mapSelectorSet, mapSourceSnapshot, mapEvaluation, mapReview, mapPreview, mapPublication, mapReconciliationWorkItem };
