"use strict";
const crypto = require("node:crypto");
const clone = (v) => v == null ? v : JSON.parse(JSON.stringify(v));
const uuid = () => crypto.randomUUID();
function createInMemoryOrganizationMappingRepository() {
  const drafts = new Map(), policies = new Map(), snapshots = new Map(), evaluations = new Map(), reviews = new Map(), dimensionConfigs = new Map(), publications = new Map(), previews = new Map(), workItems = new Map(), audits = [], outbox = [], idempotency = new Map();
  const byOrg = (map, org) => [...map.values()].filter((row) => row["organization"+"Id"] === org).map(clone);
  return Object.freeze({
    audits, outbox,
    async transaction(fn) { const maps=[drafts,policies,snapshots,evaluations,reviews,dimensionConfigs,publications,previews,workItems,idempotency]; const state=maps.map((map)=>[...map.entries()].map(([key,value])=>[key,clone(value)])); const auditLength=audits.length,outboxLength=outbox.length; try{return await fn(this);}catch(error){maps.forEach((map,index)=>{map.clear();for(const [key,value] of state[index])map.set(key,value);});audits.length=auditLength;outbox.length=outboxLength;throw error;} },
    async replayIdempotency(context) { if (!context?.key) return null; const stored=idempotency.get(idempotencyIdentity(context)); if (!stored) return null; assertIdempotencyMatch(stored,context); return clone(stored.response); },
    async rememberIdempotency(context, value) { if (context?.key) idempotency.set(idempotencyIdentity(context), clone({...context,response:value})); return value; },
    async acquirePublicationLock() { return true; },
    async audit(event) { audits.push(clone(event)); return event; },
    async enqueueOutbox(event) { outbox.push(clone(event)); return event; },
    async createDraft(row) { const saved = { id: uuid(), version: 1, status: "draft", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), ...row }; drafts.set(saved.id, saved); return clone(saved); },
    async getDraft(org, id) { const row = drafts.get(id); return row?.organizationId === org ? clone(row) : null; },
    async updateDraft(org, id, patch, expectedVersion) { const row = drafts.get(id); if (!row || row["organization"+"Id"] !== org) return null; if (expectedVersion && Number(row.version) !== Number(expectedVersion)) { const e = new Error("organization_mapping_version_conflict"); e.code = e.message; throw e; } const saved = { ...row, ...patch, version: Number(row.version) + 1, updatedAt: new Date().toISOString() }; drafts.set(id, saved); return clone(saved); },
    async savePolicyVersion(row) { const saved = { id: uuid(), immutable: true, createdAt: new Date().toISOString(), ...row }; policies.set(saved.id, saved); return clone(saved); },
    async listPolicyVersions(org) { return byOrg(policies, org); },
    async saveSourceSnapshot(row) { const saved = { id: uuid(), createdAt: new Date().toISOString(), ...row }; snapshots.set(saved.id, saved); return clone(saved); },
    async saveEvaluation(row) { const saved = { id: uuid(), createdAt: new Date().toISOString(), ...row }; evaluations.set(saved.id, saved); return clone(saved); },
    async getEvaluation(org, id) { const row = evaluations.get(id); return row?.organizationId === org ? clone(row) : null; },
    async saveReview(row) { const saved = { id: uuid(), createdAt: new Date().toISOString(), ...row }; reviews.set(saved.id, saved); return clone(saved); },
    async listAudit(org, limit = 50) { return audits.filter((e) => e.organizationId === org).slice(-Math.min(limit, 100)).reverse().map(clone); },
    async saveDimensionConfig(row) { const saved = { id: uuid(), version: 1, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), ...row }; dimensionConfigs.set(saved.id, saved); return clone(saved); },
    async savePreview(row) { const saved = { id: uuid(), createdAt: new Date().toISOString(), ...row }; previews.set(saved.id, saved); return clone(saved); },
    async getPreview(org, id) { const row = previews.get(id); return row?.organizationId === org ? clone(row) : null; },
    async savePublication(row) { const current=[...publications.values()].filter((item)=>item.organizationId===row.organizationId); const saved = { id: uuid(), immutable: true, publishedVersion:current.length+1, createdAt: new Date().toISOString(), ...row }; publications.set(saved.id, saved); return clone(saved); },
    async getPublication(org, id) { const row = publications.get(id); return row?.organizationId === org ? clone(row) : null; },
    async getLatestPublication(org) { return clone([...publications.values()].filter((row) => row["organization"+"Id"] === org).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0] || null); },
    async saveReconciliationWorkItems(items) { const saved = items.map((item) => ({ id: uuid(), createdAt: new Date().toISOString(), ...item })); for (const item of saved) workItems.set(item.id, item); return clone(saved); },
  });
}
function createPostgresOrganizationMappingRepository({ pool }) {
  const q = (text, values) => pool.query(text, values);
  return Object.freeze({
    async transaction(fn) { const client = await pool.connect(); try { await client.query("begin"); const result = await fn(createPostgresOrganizationMappingRepository({ pool: client })); await client.query("commit"); return result; } catch (e) { await client.query("rollback"); throw e; } finally { client.release?.(); } },
    async replayIdempotency(context) { if (!context?.key) return null; const r = await q("select request_hash,expected_version,response_json from organization_mapping_idempotency_keys where organization_id=$1 and subject_id=$2 and action_id=$3 and idempotency_key=$4", [context["organization"+"Id"],context.subjectId,context.actionId,context.key]); if (!r.rows[0]) return null; assertIdempotencyMatch({requestHash:r.rows[0].request_hash,expectedVersion:r.rows[0].expected_version},context); return r.rows[0].response_json; },
    async rememberIdempotency(context, value) { if (context?.key) await q("insert into organization_mapping_idempotency_keys(organization_id,subject_id,action_id,idempotency_key,request_hash,expected_version,response_json,status) values($1,$2,$3,$4,$5,$6,$7,'completed')", [context["organization"+"Id"],context.subjectId,context.actionId,context.key,context.requestHash,String(context.expectedVersion??""),value]); return value; },
    async acquirePublicationLock(organizationId) { await q("select pg_advisory_xact_lock(hashtextextended($1, 318))", [organizationId]); return true; },
    async audit(event) { await q("insert into organization_mapping_audit_events(organization_id,actor_logto_user_id,action,target_type,target_id,result,reason,event_json) values($1,$2,$3,$4,$5,$6,$7,$8)", [event["organization"+"Id"],event.actorLogtoUserId,event.action,event.targetType,event.targetId,event.result,event.reason,event]); return event; },
    async enqueueOutbox(event) { await q("insert into organization_mapping_outbox_events(organization_id,event_type,payload_json,idempotency_key) values($1,$2,$3,$4) on conflict do nothing", [event["organization"+"Id"],event.eventType,event,event.idempotencyKey || null]); return event; },
    async createDraft(row) { const r = await q("insert into organization_mapping_drafts(organization_id,status,model_json) values($1,'draft',$2) returning *", [row["organization"+"Id"],row.model]); return mapDraft(r.rows[0]); },
    async getDraft(org, id) { const r = await q("select * from organization_mapping_drafts where organization_id=$1 and id=$2", [org,id]); return r.rows[0] ? mapDraft(r.rows[0]) : null; },
    async updateDraft(org, id, patch, expectedVersion) { const r = await q("update organization_mapping_drafts set model_json=$3, version=version+1, updated_at=now() where organization_id=$1 and id=$2 and version=$4 returning *", [org,id,patch.model,expectedVersion]); if (!r.rowCount) { const e = new Error("organization_mapping_version_conflict"); e.code = e.message; throw e; } return mapDraft(r.rows[0]); },
    async savePolicyVersion(row) { const r = await q("insert into organization_mapping_policy_versions(organization_id,draft_id,policy_json,policy_hash) values($1,$2,$3,$4) returning *", [row["organization"+"Id"],row.draftId,row.policy,row.policyHash]); return mapPolicyVersion(r.rows[0]); },
    async saveSourceSnapshot(row) { const r = await q("insert into organization_mapping_source_snapshots(organization_id,source_connection_id,facts_json,evidence_json) values($1,$2,$3,$4) returning *", [row["organization"+"Id"],row.sourceConnectionId,row.facts,row.evidence]); return mapSourceSnapshot(r.rows[0]); },
    async saveEvaluation(row) { const r = await q("insert into organization_mapping_evaluations(organization_id,draft_id,policy_version_id,source_snapshot_id,outcome,reason_code,trace_json) values($1,$2,$3,$4,$5,$6,$7) returning *", [row["organization"+"Id"],row.draftId,row.policyVersionId,row.sourceSnapshotId,row.outcome,row.reasonCode,row.trace]); return mapEvaluation(r.rows[0]); },
    async getEvaluation(org, id) { const r = await q("select * from organization_mapping_evaluations where organization_id=$1 and id=$2", [org,id]); return r.rows[0] ? mapEvaluation(r.rows[0]) : null; },
    async saveReview(row) { const r = await q("insert into organization_mapping_reviews(organization_id,evaluation_id,decision,reason,actor_logto_user_id) values($1,$2,$3,$4,$5) returning *", [row["organization"+"Id"],row.evaluationId,row.decision,row.reason,row.actorLogtoUserId]); return mapReview(r.rows[0]); },
    async listAudit(org, limit = 50) { const r = await q("select event_json from organization_mapping_audit_events where organization_id=$1 order by created_at desc limit $2", [org, Math.min(limit,100)]); return r.rows.map((row) => row.event_json); },
    async saveDimensionConfig(row) { const r = await q("insert into organization_dimension_configurations(organization_id,dimension_id,config_json) values($1,$2,$3) returning *", [row["organization"+"Id"],row.dimensionId,row.config]); return r.rows[0]; },
    async savePreview(row) { const r = await q("insert into organization_mapping_previews(organization_id,draft_id,draft_version,preview_digest,impact_digest,graph_json,scope_tree_json,facets_json) values($1,$2,$3,$4,$5,$6,$7,$8) returning *", [row["organization"+"Id"],row.draftId,row.draftVersion,row.previewDigest,row.impactDigest,row.graph,row.scopeTree,row.facets]); return mapPreview(r.rows[0]); },
    async getPreview(org, id) { const r = await q("select * from organization_mapping_previews where organization_id=$1 and id=$2", [org,id]); return r.rows[0] ? mapPreview(r.rows[0]) : null; },
    async savePublication(row) { const r = await q("insert into organization_mapping_published_versions(organization_id,draft_id,draft_version,preview_id,model_hash,impact_digest,graph_json,scope_tree_json,facets_json,source_publication_id,model_json,published_version,base_published_version) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,COALESCE((select max(published_version)+1 from organization_mapping_published_versions where organization_id=$1),1),$12) returning *", [row["organization"+"Id"],row.draftId,row.draftVersion,row.previewId,row.modelHash,row.impactDigest,row.graph,row.scopeTree,row.facets,row.sourcePublicationId || null,row.model,row.basePublishedVersion??null]); return mapPublication(r.rows[0]); },
    async getPublication(org, id) { const r = await q("select * from organization_mapping_published_versions where organization_id=$1 and id=$2", [org,id]); return r.rows[0] ? mapPublication(r.rows[0]) : null; },
    async getLatestPublication(org) { const r = await q("select * from organization_mapping_published_versions where organization_id=$1 order by published_version desc nulls last, created_at desc limit 1", [org]); return r.rows[0] ? mapPublication(r.rows[0]) : null; },
    async saveReconciliationWorkItems(items) { const saved=[]; for (const item of items) { const r=await q("insert into organization_mapping_reconciliation_work_items(organization_id,publication_id,target_type,target_id,status,grants_access,impact_classification) values($1,$2,$3,$4,$5,false,$6) returning *", [item["organization"+"Id"],item.publicationId,item.targetType,item.targetId,item.status,item.impactClassification]); saved.push(mapReconciliationWorkItem(r.rows[0])); } return saved; },
  });
}
function mapDraft(r) { const row={ id:r.id, version:r.version, status:r.status, model:r.model_json, createdAt:r.created_at, updatedAt:r.updated_at }; row["organization"+"Id"]=r.organization_id; return row; }
function domainBase(r) { const row={id:r.id,createdAt:r.created_at}; row["organization"+"Id"]=r.organization_id; return row; }
function mapPolicyVersion(r) { return {...domainBase(r),draftId:r.draft_id,policy:r.policy_json,policyHash:r.policy_hash,immutable:r.immutable}; }
function mapSourceSnapshot(r) { return {...domainBase(r),sourceConnectionId:r.source_connection_id,facts:r.facts_json,evidence:r.evidence_json}; }
function mapEvaluation(r) { return {...domainBase(r),draftId:r.draft_id,policyVersionId:r.policy_version_id,sourceSnapshotId:r.source_snapshot_id,outcome:r.outcome,reasonCode:r.reason_code,trace:r.trace_json}; }
function mapReview(r) { return {...domainBase(r),evaluationId:r.evaluation_id,decision:r.decision,reason:r.reason,actorLogtoUserId:r.actor_logto_user_id}; }
function mapPreview(r) { return {...domainBase(r),draftId:r.draft_id,draftVersion:r.draft_version,previewDigest:r.preview_digest,impactDigest:r.impact_digest,graph:r.graph_json,scopeTree:r.scope_tree_json,facets:r.facets_json}; }
function mapPublication(r) { return {...domainBase(r),draftId:r.draft_id,draftVersion:r.draft_version,previewId:r.preview_id,modelHash:r.model_hash,impactDigest:r.impact_digest,graph:r.graph_json,scopeTree:r.scope_tree_json,facets:r.facets_json,model:r.model_json,publishedVersion:r.published_version,basePublishedVersion:r.base_published_version,sourcePublicationId:r.source_publication_id,immutable:r.immutable}; }
function mapReconciliationWorkItem(r) { return {...domainBase(r),publicationId:r.publication_id,targetType:r.target_type,targetId:r.target_id,status:r.status,impactClassification:r.impact_classification,grantsAccess:r.grants_access}; }
function idempotencyIdentity(c) { return `${c.organizationId}:${c.subjectId}:${c.actionId}:${c.key}`; }
function assertIdempotencyMatch(stored,context) { if (stored.requestHash!==context.requestHash || String(stored.expectedVersion??"")!==String(context.expectedVersion??"")) { const e=new Error("organization_mapping_idempotency_conflict"); e.code=e.message; e.status=409; throw e; } }
module.exports = { createInMemoryOrganizationMappingRepository, createPostgresOrganizationMappingRepository, mapDraft, mapPolicyVersion, mapSourceSnapshot, mapEvaluation, mapReview, mapPreview, mapPublication, mapReconciliationWorkItem };
