"use strict";
const express = require("express");
const { organizationMappingLifecycleActions } = require("../../core/organization-mapping/index.cjs");
const organizationMappingContracts = require("../../core/organization-mapping/index.cjs");
const { createAuthorizationUiDecision } = require("./authorization-ui-decision");
const { actor } = require("./service");
const permissionFor = Object.freeze(Object.fromEntries(organizationMappingLifecycleActions.map((a) => [a.actionId, a.requiredPermission])));
function requireDeclaredAction(actionId) {
  const requiredPermission = permissionFor[actionId];
  return (req, res, next) => {
    if (!requiredPermission) return res.status(500).json({ error: "action_unregistered", code: "action_unregistered" });
    req.organizationMappingAction = { actionId, requiredPermission };
    return next();
  };
}
function publicAuthorizationDecision(decision){return {...decision,evaluatedStages:[]};}
function sendError(res, error) { return res.status(error.status || 500).json({ error: error.code || "organization_mapping_error", code: error.code || "organization_mapping_error" }); }
function createOrganizationMappingRouter({ service, authorizeAction }) {
  if(typeof authorizeAction!=="function") throw new Error("organization_mapping_authorization_pipeline_required");
  const router = express.Router({ mergeParams: true }); router.use(express.json({ limit: "128kb" }));
  const guard=(actionId)=>[requireDeclaredAction(actionId),...authorizeAction(actionId,permissionFor[actionId])];
  router.get("/o/:organizationId/organization-model/contracts", ...guard("organizationModel.readPublished"), (_req,res)=>res.json({ lifecycleActions:organizationMappingContracts.organizationMappingLifecycleActions, selectorRegistry:{version:organizationMappingContracts.SELECTOR_REGISTRY_VERSION,hash:organizationMappingContracts.selectorRegistryHash,entries:organizationMappingContracts.externalFactSelectors}, operatorRegistry:organizationMappingContracts.operatorRegistry.safeContract(), outcomes:organizationMappingContracts.outcomeRegistry.safeContract(), reasonCodes:organizationMappingContracts.mappingReasonCodeRegistry.safeContract(), evidenceClassifications:organizationMappingContracts.evidenceClassificationRegistry.safeContract(), relationshipRegistry:organizationMappingContracts.relationshipRegistry.safeContract() }));
  router.get("/o/:organizationId/organization-model/authorization-decisions/:actionId", async(req,res)=>{const actionId=req.params.actionId, permission=permissionFor[actionId];if(!permission)return res.status(404).json({error:"organization_mapping_action_not_found",code:"organization_mapping_action_not_found"});req.organizationMappingAction={actionId,requiredPermission:permission};const subjectId=actor(req);const denialResponder=(_response,{status,code,decisionId})=>res.status(status).json(publicAuthorizationDecision(createAuthorizationUiDecision({decision:{allowed:false,reasonCode:code,decisionId,authorizationSnapshotVersion:req.auth?.authorizationSnapshotVersion||req.user?.authorizationSnapshotVersion},subjectId,organizationId:req.params.organizationId,actionId})));const middleware=authorizeAction(actionId,permission,{decisionEnvelope:true,denialResponder,onDecision:(_request,decision)=>{req.authorizationDecision=decision;}});let index=0;const next=async(error)=>{if(error)return res.status(500).json({error:"AuthorizationPolicyError",code:"policy_evaluation_failed"});const fn=middleware[index++];if(fn)return fn(req,res,next);const envelope=publicAuthorizationDecision(createAuthorizationUiDecision({decision:req.authorizationDecision,subjectId,organizationId:req.params.organizationId,actionId}));await service.recordAuthorizationDecision({organizationId:req.params.organizationId,subjectId,decision:envelope});return res.json(envelope);};return next();});
  router.get("/o/:organizationId/organization-model/authorization-explanations/recent", ...guard("organizationModel.inspectAuditHistory"), async(req,res)=>{try{res.json(await service.listAuthorizationDecisions({organizationId:req.params.organizationId,subjectId:actor(req),limit:req.query.limit}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/authorization-explanations/:actionId", ...guard("organizationModel.inspectAuditHistory"), async(req,res)=>{const actionId=req.params.actionId,permission=permissionFor[actionId];if(!permission)return res.status(404).json({error:"resource_not_found_or_not_accessible",code:"resource_not_found_or_not_accessible"});const subjectId=actor(req),requestedDecisionId=String(req.query.decisionId||""),safeReference=(value)=>/^[A-Za-z0-9._:-]{1,128}$/.test(String(value||""))?String(value):undefined,reference={modelVersion:safeReference(req.query.modelVersion),policyVersion:safeReference(req.query.policyVersion),resource:safeReference(req.query.resource)};const envelope=(decision)=>{const value=createAuthorizationUiDecision({decision,subjectId,organizationId:req.params.organizationId,actionId});return {...value,diagnosticsAuthorized:true,requestedDecisionId:requestedDecisionId||undefined,referenceStatus:requestedDecisionId&&requestedDecisionId!==value.decisionId?"superseded":"current",reference};},denialResponder=(_response,{status,code,decisionId})=>res.status(status).json(envelope({allowed:false,reasonCode:code,decisionId,authorizationSnapshotVersion:req.auth?.authorizationSnapshotVersion||req.user?.authorizationSnapshotVersion})),middleware=authorizeAction(actionId,permission,{decisionEnvelope:true,denialResponder,onDecision:(_request,decision)=>{req.authorizationDecision=decision;}});let index=0;const next=async(error)=>{if(error)return res.status(500).json({error:"AuthorizationPolicyError",code:"policy_evaluation_failed"});const fn=middleware[index++];if(fn)return fn(req,res,next);const body=envelope(req.authorizationDecision);await service.recordAuthorizationDecision({organizationId:req.params.organizationId,subjectId,decision:body});return res.json(body);};return next();});
  router.post("/o/:organizationId/organization-model/drafts", ...guard("organizationModel.editDraft"), async (req,res)=>{ try { if(!req.get("Idempotency-Key"))return res.status(400).json({error:"organization_mapping_idempotency_key_required",code:"organization_mapping_idempotency_key_required"});res.status(201).json(await service.createDraft({ organizationId:req.params.organizationId, model:req.body?.model || {}, reason:req.body?.reason, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.put("/o/:organizationId/organization-model/drafts/:draftId", ...guard("organizationModel.editDraft"), async (req,res)=>{ try { res.json(await service.updateDraft({ organizationId:req.params.organizationId, draftId:req.params.draftId, model:req.body?.model || {}, expectedVersion:req.get("If-Match") || req.body?.expectedVersion, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.post("/o/:organizationId/organization-model/evaluations", ...guard("organizationModel.evaluateMappingPolicies"), async (req,res)=>{ try { res.status(201).json(await service.evaluate({ organizationId:req.params.organizationId, draftId:req.body?.draftId, policy:req.body?.policy || { rules: [] }, sourceFacts:req.body?.sourceFacts || {}, sourceConnectionId:req.body?.sourceConnectionId, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.post("/o/:organizationId/organization-model/drafts/:draftId/preview", ...guard("organizationModel.evaluateMappingPolicies"), async (req,res)=>{ try { res.status(201).json(await service.preview({ organizationId:req.params.organizationId, draftId:req.params.draftId, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.post("/o/:organizationId/organization-model/drafts/:draftId/publish", ...guard("organizationModel.publishVersion"), async (req,res)=>{ try { res.status(201).json(await service.publish({ organizationId:req.params.organizationId, draftId:req.params.draftId, expectedDraftVersion:req.body?.expectedDraftVersion, expectedPublishedVersion:req.body?.expectedPublishedVersion, previewId:req.body?.previewId, expectedImpactDigest:req.body?.expectedImpactDigest, reason:req.body?.reason, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.post("/o/:organizationId/organization-model/publications/:publicationId/rollback-draft", ...guard("organizationModel.createRollbackDraft"), async (req,res)=>{ try { res.status(201).json(await service.createRollbackDraft({ organizationId:req.params.organizationId, publicationId:req.params.publicationId, reason:req.body?.reason, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.post("/o/:organizationId/organization-model/evaluations/:evaluationId/reviews", ...guard("organizationModel.approveMapping"), async (req,res)=>{ try { res.status(201).json(await service.review({ organizationId:req.params.organizationId, evaluationId:req.params.evaluationId, decision:req.body?.decision, reason:req.body?.reason, expectedReviewVersion:req.body?.expectedReviewVersion, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.get("/o/:organizationId/organization-model/audit", ...guard("organizationModel.inspectAuditHistory"), async (req,res)=>{ try { res.json(await service.listAudit({ organizationId:req.params.organizationId, limit:req.query.limit })); } catch(e) { sendError(res,e); } });
  router.get("/o/:organizationId/organization-model/published", ...guard("organizationModel.readPublished"), async(req,res)=>{try{res.json(await service.getPublished({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/publications", ...guard("organizationModel.readPublished"), async(req,res)=>{try{res.json(await service.listPublications({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/publications/:publicationId", ...guard("organizationModel.readPublished"), async(req,res)=>{try{res.json(await service.getPublished({organizationId:req.params.organizationId,publicationId:req.params.publicationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/publications/:publicationId/graph", ...guard("organizationModel.readPublished"), async(req,res)=>{try{const body=await service.getPublished({organizationId:req.params.organizationId,publicationId:req.params.publicationId});res.json({contractVersion:body.contractVersion,modelVersion:body.publication.publishedVersion,graph:body.publication.graph});}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/publications/:publicationId/scope-tree", ...guard("organizationModel.readPublished"), async(req,res)=>{try{const body=await service.getPublished({organizationId:req.params.organizationId,publicationId:req.params.publicationId});res.json({contractVersion:body.contractVersion,modelVersion:body.publication.publishedVersion,scopeTree:body.publication.scopeTree});}catch(e){sendError(res,e);}});
  router.put("/o/:organizationId/organization-model/drafts/:draftId/structure", ...guard("organizationModel.editDraft"), async(req,res)=>{try{res.json(await service.updateStructureDraft({organizationId:req.params.organizationId,draftId:req.params.draftId,model:req.body?.model||{},expectedVersion:req.get("If-Match")||req.body?.expectedVersion,reason:req.body?.reason,actorLogtoUserId:actor(req),idempotencyKey:req.get("Idempotency-Key")}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/drafts/active", ...guard("organizationModel.readDraft"), async(req,res)=>{try{res.json(await service.getActiveDraft({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/structure-workspace", ...guard("organizationModel.readDraft"), async(req,res)=>{try{res.json(await service.getStructureWorkspace({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/workspace-summary", ...guard("organizationModel.readDraft"), async(req,res)=>{try{res.json(await service.getWorkspaceSummary({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/data-scopes-workspace", ...guard("organizationModel.readDraft"), async(req,res)=>{try{res.json(await service.getDataScopesWorkspace({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/drafts/:draftId/policies", ...guard("organizationModel.readDraft"), async(req,res)=>{try{res.json(await service.listPolicies({organizationId:req.params.organizationId,draftId:req.params.draftId}));}catch(e){sendError(res,e);}});
  router.post("/o/:organizationId/organization-model/drafts/:draftId/policies", ...guard("organizationModel.editDraft"), async(req,res)=>{try{res.status(201).json(await service.savePolicy({organizationId:req.params.organizationId,draftId:req.params.draftId,policy:req.body?.policy,actorLogtoUserId:actor(req)}));}catch(e){sendError(res,e);}});
  router.delete("/o/:organizationId/organization-model/drafts/:draftId/policies/:policyId", ...guard("organizationModel.editDraft"), async(req,res)=>{try{res.json(await service.archivePolicy({organizationId:req.params.organizationId,policyId:req.params.policyId,reason:req.body?.reason}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/selector-sets", ...guard("organizationModel.readDraft"), async(req,res)=>{try{res.json(await service.listSelectorSets({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  router.post("/o/:organizationId/organization-model/selector-sets", ...guard("organizationModel.editDraft"), async(req,res)=>{try{if(!req.body?.selectorSet?.changeReason||!req.get("Idempotency-Key"))return res.status(400).json({error:"organization_mapping_reason_required",code:"organization_mapping_reason_required"});res.status(201).json(await service.saveSelectorSet({organizationId:req.params.organizationId,selectorSet:req.body?.selectorSet,actorLogtoUserId:actor(req),idempotencyKey:req.get("Idempotency-Key")}));}catch(e){sendError(res,e);}});
  router.delete("/o/:organizationId/organization-model/selector-sets/:selectorSetId", ...guard("organizationModel.editDraft"), async(req,res)=>{try{res.json(await service.archiveSelectorSet({organizationId:req.params.organizationId,selectorSetId:req.params.selectorSetId,reason:req.body?.reason}));}catch(e){sendError(res,e);}});
  router.post("/o/:organizationId/organization-model/evaluations/from-snapshot", ...guard("organizationModel.evaluateMappingPolicies"), async(req,res)=>{try{res.status(201).json(await service.evaluateSnapshot({organizationId:req.params.organizationId,draftId:req.body?.draftId,policyVersionId:req.body?.policyVersionId,sourceSnapshotId:req.body?.sourceSnapshotId,actorLogtoUserId:actor(req),idempotencyKey:req.get("Idempotency-Key")}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/evaluations/:evaluationId/trace", ...guard("organizationModel.evaluateMappingPolicies"), async(req,res)=>{try{res.json(await service.getTrace({organizationId:req.params.organizationId,evaluationId:req.params.evaluationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/evaluations/:evaluationId/evidence", ...guard("organizationModel.readSensitiveMappingEvidence"), async(req,res)=>{try{const permissions=[...(req.auth?.scopes||req.user?.scopes||[])];res.json(await service.getEvidence({organizationId:req.params.organizationId,evaluationId:req.params.evaluationId,permissions,reason:req.get("X-Access-Reason"),actorLogtoUserId:actor(req)}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/reviews", ...guard("organizationModel.approveMapping"), async(req,res)=>{try{res.json(await service.listReviewQueue({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  router.put("/o/:organizationId/organization-model/dimensions/:dimensionId", ...guard("organizationModel.editDraft"), async(req,res)=>{try{res.json(await service.saveDimensionConfiguration({organizationId:req.params.organizationId,dimensionId:req.params.dimensionId,config:req.body?.config,reason:req.body?.reason,actorLogtoUserId:actor(req),idempotencyKey:req.get("Idempotency-Key")}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/reconciliation", ...guard("organizationModel.reconcileUpstream"), async(req,res)=>{try{res.json(await service.listReconciliation({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  return router;
}
module.exports = { createOrganizationMappingRouter, requireDeclaredAction };
