"use strict";
const express = require("express");
const { organizationMappingLifecycleActions } = require("../../core/organization-mapping/index.cjs");
const { actor } = require("./service");
const permissionFor = Object.freeze(Object.fromEntries(organizationMappingLifecycleActions.map((a) => [a.actionId, a.requiredPermission])));
function requireDeclaredAction(actionId) {
  const requiredPermission = permissionFor[actionId];
  return (req, res, next) => {
    if (!requiredPermission) return res.status(500).json({ error: "action_unregistered", code: "action_unregistered" });
    req.organizationMappingAction = { actionId, requiredPermission };
    return next();
  };
}
function sendError(res, error) { return res.status(error.status || 500).json({ error: error.code || "organization_mapping_error", code: error.code || "organization_mapping_error" }); }
function createOrganizationMappingRouter({ service, authorizeAction }) {
  if(typeof authorizeAction!=="function") throw new Error("organization_mapping_authorization_pipeline_required");
  const router = express.Router({ mergeParams: true }); router.use(express.json({ limit: "128kb" }));
  const guard=(actionId)=>[requireDeclaredAction(actionId),...authorizeAction(actionId,permissionFor[actionId])];
  router.post("/o/:organizationId/organization-model/drafts", ...guard("organizationModel.editDraft"), async (req,res)=>{ try { res.status(201).json(await service.createDraft({ organizationId:req.params.organizationId, model:req.body?.model || {}, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.put("/o/:organizationId/organization-model/drafts/:draftId", ...guard("organizationModel.editDraft"), async (req,res)=>{ try { res.json(await service.updateDraft({ organizationId:req.params.organizationId, draftId:req.params.draftId, model:req.body?.model || {}, expectedVersion:req.get("If-Match") || req.body?.expectedVersion, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.post("/o/:organizationId/organization-model/evaluations", ...guard("organizationModel.evaluateMappingPolicies"), async (req,res)=>{ try { res.status(201).json(await service.evaluate({ organizationId:req.params.organizationId, draftId:req.body?.draftId, policy:req.body?.policy || { rules: [] }, sourceFacts:req.body?.sourceFacts || {}, sourceConnectionId:req.body?.sourceConnectionId, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.post("/o/:organizationId/organization-model/drafts/:draftId/preview", ...guard("organizationModel.evaluateMappingPolicies"), async (req,res)=>{ try { res.status(201).json(await service.preview({ organizationId:req.params.organizationId, draftId:req.params.draftId, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.post("/o/:organizationId/organization-model/drafts/:draftId/publish", ...guard("organizationModel.publishVersion"), async (req,res)=>{ try { res.status(201).json(await service.publish({ organizationId:req.params.organizationId, draftId:req.params.draftId, expectedDraftVersion:req.body?.expectedDraftVersion, expectedPublishedVersion:req.body?.expectedPublishedVersion, previewId:req.body?.previewId, expectedImpactDigest:req.body?.expectedImpactDigest, reason:req.body?.reason, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.post("/o/:organizationId/organization-model/publications/:publicationId/rollback-draft", ...guard("organizationModel.createRollbackDraft"), async (req,res)=>{ try { res.status(201).json(await service.createRollbackDraft({ organizationId:req.params.organizationId, publicationId:req.params.publicationId, reason:req.body?.reason, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.post("/o/:organizationId/organization-model/evaluations/:evaluationId/reviews", ...guard("organizationModel.approveMapping"), async (req,res)=>{ try { res.status(201).json(await service.review({ organizationId:req.params.organizationId, evaluationId:req.params.evaluationId, decision:req.body?.decision, reason:req.body?.reason, expectedReviewVersion:req.body?.expectedReviewVersion, actorLogtoUserId:actor(req), idempotencyKey:req.get("Idempotency-Key") })); } catch(e) { sendError(res,e); } });
  router.get("/o/:organizationId/organization-model/audit", ...guard("organizationModel.inspectAuditHistory"), async (req,res)=>{ try { res.json(await service.listAudit({ organizationId:req.params.organizationId, limit:req.query.limit })); } catch(e) { sendError(res,e); } });
  router.get("/o/:organizationId/organization-model/published", ...guard("organizationModel.readPublished"), async(req,res)=>{try{res.json(await service.getPublished({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/publications", ...guard("organizationModel.readPublished"), async(req,res)=>{try{res.json(await service.listPublications({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/publications/:publicationId", ...guard("organizationModel.readPublished"), async(req,res)=>{try{res.json(await service.getPublished({organizationId:req.params.organizationId,publicationId:req.params.publicationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/publications/:publicationId/graph", ...guard("organizationModel.readPublished"), async(req,res)=>{try{const body=await service.getPublished({organizationId:req.params.organizationId,publicationId:req.params.publicationId});res.json({contractVersion:body.contractVersion,modelVersion:body.publication.publishedVersion,graph:body.publication.graph});}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/publications/:publicationId/scope-tree", ...guard("organizationModel.readPublished"), async(req,res)=>{try{const body=await service.getPublished({organizationId:req.params.organizationId,publicationId:req.params.publicationId});res.json({contractVersion:body.contractVersion,modelVersion:body.publication.publishedVersion,scopeTree:body.publication.scopeTree});}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/drafts/active", ...guard("organizationModel.readDraft"), async(req,res)=>{try{res.json(await service.getActiveDraft({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/drafts/:draftId/policies", ...guard("organizationModel.readDraft"), async(req,res)=>{try{res.json(await service.listPolicies({organizationId:req.params.organizationId,draftId:req.params.draftId}));}catch(e){sendError(res,e);}});
  router.post("/o/:organizationId/organization-model/drafts/:draftId/policies", ...guard("organizationModel.editDraft"), async(req,res)=>{try{res.status(201).json(await service.savePolicy({organizationId:req.params.organizationId,draftId:req.params.draftId,policy:req.body?.policy,actorLogtoUserId:actor(req)}));}catch(e){sendError(res,e);}});
  router.delete("/o/:organizationId/organization-model/drafts/:draftId/policies/:policyId", ...guard("organizationModel.editDraft"), async(req,res)=>{try{res.json(await service.archivePolicy({organizationId:req.params.organizationId,policyId:req.params.policyId,reason:req.body?.reason}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/selector-sets", ...guard("organizationModel.readDraft"), async(req,res)=>{try{res.json(await service.listSelectorSets({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  router.post("/o/:organizationId/organization-model/selector-sets", ...guard("organizationModel.editDraft"), async(req,res)=>{try{res.status(201).json(await service.saveSelectorSet({organizationId:req.params.organizationId,selectorSet:req.body?.selectorSet,actorLogtoUserId:actor(req),idempotencyKey:req.get("Idempotency-Key")}));}catch(e){sendError(res,e);}});
  router.delete("/o/:organizationId/organization-model/selector-sets/:selectorSetId", ...guard("organizationModel.editDraft"), async(req,res)=>{try{res.json(await service.archiveSelectorSet({organizationId:req.params.organizationId,selectorSetId:req.params.selectorSetId,reason:req.body?.reason}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/evaluations/:evaluationId/trace", ...guard("organizationModel.evaluateMappingPolicies"), async(req,res)=>{try{res.json(await service.getTrace({organizationId:req.params.organizationId,evaluationId:req.params.evaluationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/evaluations/:evaluationId/evidence", ...guard("organizationModel.readSensitiveMappingEvidence"), async(req,res)=>{try{const permissions=[...(req.auth?.scopes||req.user?.scopes||[])];res.json(await service.getEvidence({organizationId:req.params.organizationId,evaluationId:req.params.evaluationId,permissions,reason:req.get("X-Access-Reason"),actorLogtoUserId:actor(req)}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/reviews", ...guard("organizationModel.approveMapping"), async(req,res)=>{try{res.json(await service.listReviewQueue({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  router.get("/o/:organizationId/organization-model/reconciliation", ...guard("organizationModel.reconcileUpstream"), async(req,res)=>{try{res.json(await service.listReconciliation({organizationId:req.params.organizationId}));}catch(e){sendError(res,e);}});
  return router;
}
module.exports = { createOrganizationMappingRouter, requireDeclaredAction };
