import { useMemo, useState } from "react";
import { DataTable, SectionCard, StatusPill } from "../../../../shared/ui";
import type { GovernanceIdentityProvisioningSummary, GovernanceSurface } from "../../contracts";

type Lifecycle = "draft" | "active" | "suspended" | "archived";
type ProvisioningPolicy = "manual-review" | "auto-provision" | "just-in-time";
type DeprovisioningPolicy = "suspend-only" | "archive-after-30-days" | "immediate-disable";
type MappingRow = { source: string; normalized: string; rule: string; required: boolean };
const nowIso = "2026-07-24T12:00:00.000Z";
const sampleUsers = [{ id: "u-1001", display: "Avery Chen", email: "avery.chen@example.edu", department: "Admissions", status: "normalized" }, { id: "u-1002", display: "Marisol Vega", email: "marisol.vega@example.edu", department: "Learning", status: "pending mapping" }];
const sampleGroups = [{ id: "g-faculty", display: "Faculty", members: 42, externalId: "scim-group-faculty" }, { id: "g-admins", display: "Organization Administrators", members: 5, externalId: "scim-group-admins" }];
const initialMappings: MappingRow[] = [{ source: "userName", normalized: "profile.email", rule: "lowercase + trim", required: true }, { source: "name.formatted", normalized: "profile.displayName", rule: "fallback to givenName familyName", required: true }, { source: "groups[].display", normalized: "memberships.groups", rule: "match by externalId before display", required: false }, { source: "enterprise.department", normalized: "taxonomy.department", rule: "map to active dimension value", required: false }];
const statusTone = (status: string) => status === "active" ? "success" : status === "draft" ? "warning" : status === "archived" ? "neutral" : "danger";
const buildBaseUrl = (organizationId: string) => `https://api.civitas.example/o/${encodeURIComponent(organizationId || "organization")}/scim/v2`;

export const IdentityProvisioningModule = ({ organizationId, surface, summary }: { organizationId: string; surface: GovernanceSurface; summary?: GovernanceIdentityProvisioningSummary }) => {
  const [lifecycle, setLifecycle] = useState<Lifecycle>(summary?.status === "active" ? "active" : summary?.status === "suspended" ? "suspended" : "draft");
  const [provisioningPolicy, setProvisioningPolicy] = useState<ProvisioningPolicy>("manual-review");
  const [deprovisioningPolicy, setDeprovisioningPolicy] = useState<DeprovisioningPolicy>("suspend-only");
  const [generatedToken, setGeneratedToken] = useState<string | null>(null);
  const [tokenGenerated, setTokenGenerated] = useState(false);
  const [credentialState, setCredentialState] = useState<"not-generated" | "active" | "revoked">(summary?.credentialExpiresAt ? "active" : "not-generated");
  const [lastTest, setLastTest] = useState("No test has run for this draft connection.");
  const [lastDryRun, setLastDryRun] = useState("Dry-run not executed.");
  const baseUrl = useMemo(() => buildBaseUrl(organizationId), [organizationId]);
  const generateToken = () => { setGeneratedToken(`civitas_scim_${Math.random().toString(36).slice(2)}_${Date.now().toString(36)}`); setTokenGenerated(true); setCredentialState("active"); };
  return <div className="civitas-stack">
    <SectionCard title="SCIM connection workspace" description="Route-backed governance surface for authorized Owner and organization administrators. Create a draft connection, validate mappings, then activate when the IdP test is healthy." actions={<StatusPill status={statusTone(lifecycle)}>{lifecycle}</StatusPill>}>
      <div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-medium">Connection name<input className="mt-1 w-full rounded-md border border-border bg-surface p-2" defaultValue="Primary SCIM directory" /></label><label className="text-sm font-medium">Provisioning policy<select className="mt-1 w-full rounded-md border border-border bg-surface p-2" value={provisioningPolicy} onChange={(event) => setProvisioningPolicy(event.target.value as ProvisioningPolicy)}><option value="manual-review">Manual review before create</option><option value="auto-provision">Auto-provision matched users</option><option value="just-in-time">Just-in-time on first access</option></select></label><label className="text-sm font-medium">Deprovisioning policy<select className="mt-1 w-full rounded-md border border-border bg-surface p-2" value={deprovisioningPolicy} onChange={(event) => setDeprovisioningPolicy(event.target.value as DeprovisioningPolicy)}><option value="suspend-only">Suspend only</option><option value="archive-after-30-days">Archive after 30 days</option><option value="immediate-disable">Immediate disable</option></select></label></div>
      <div className="mt-4 rounded-lg border border-border bg-muted/30 p-3"><p className="text-xs uppercase tracking-wide text-muted-strong">Connection-specific base URL</p><code className="break-all text-sm">{baseUrl}</code><button className="civitas-secondary-button ml-3" type="button" onClick={() => void navigator.clipboard?.writeText(baseUrl)}>Copy base URL</button></div>
    </SectionCard>
    <SectionCard title="Bearer credential" description="Generate a one-time bearer token for the IdP. Stored token values are never displayed after the initial generation moment."><div className="civitas-action-bar"><button className="civitas-primary-button" type="button" onClick={generateToken}>{tokenGenerated ? "Rotate and reveal once" : "Generate one-time token"}</button><button className="civitas-secondary-button" type="button" onClick={() => { setCredentialState("revoked"); setGeneratedToken(null); }}>Revoke credential</button></div>{generatedToken ? <div className="mt-3 rounded-lg border border-warning bg-warning/10 p-3"><p className="text-sm font-semibold">Copy now: this bearer token will be hidden after you dismiss it.</p><code className="block break-all py-2 text-sm">{generatedToken}</code><button className="civitas-secondary-button" type="button" onClick={() => setGeneratedToken(null)}>I copied it; hide forever</button></div> : <p className="mt-3 text-sm text-muted-strong">{tokenGenerated ? "Generated once. Store now; Civitas will never show this token again." : "No bearer token has been generated for this draft connection."}</p>}</SectionCard>
    <SectionCard title="Connection tests and dry-runs" description="Validate endpoint reachability, normalized payloads, and policy impact before activation."><div className="civitas-action-bar"><button className="civitas-secondary-button" type="button" onClick={() => setLastTest(`Passed at ${nowIso}: /ServiceProviderConfig, /Users, and /Groups normalized.`)}>Run connection tests</button><button className="civitas-secondary-button" type="button" onClick={() => setLastDryRun(`Dry-run at ${nowIso}: 2 creates, 1 update, 0 destructive deprovisions under ${provisioningPolicy}/${deprovisioningPolicy}.`)}>Execute dry-run</button></div><p className="text-sm text-muted-strong">{lastTest}</p><p className="text-sm text-muted-strong">{lastDryRun}</p></SectionCard>
    <SectionCard title="Normalized sample users"><DataTable columns={[{ key: "display", header: "User", render: (u) => u.display }, { key: "email", header: "Email", render: (u) => u.email }, { key: "department", header: "Department", render: (u) => u.department }, { key: "status", header: "Status", render: (u) => <StatusPill status={u.status === "normalized" ? "success" : "warning"}>{u.status}</StatusPill> }]} data={sampleUsers} getKey={(u) => u.id} /></SectionCard>
    <SectionCard title="Normalized sample groups"><DataTable columns={[{ key: "display", header: "Group", render: (g) => g.display }, { key: "externalId", header: "External ID", render: (g) => g.externalId }, { key: "members", header: "Members", render: (g) => g.members }]} data={sampleGroups} getKey={(g) => g.id} /></SectionCard>
    <SectionCard title="Mappings"><DataTable columns={[{ key: "source", header: "SCIM source", render: (m) => m.source }, { key: "normalized", header: "Civitas field", render: (m) => m.normalized }, { key: "rule", header: "Rule", render: (m) => m.rule }, { key: "required", header: "Required", render: (m) => m.required ? "Yes" : "No" }]} data={initialMappings} getKey={(m) => m.source} /></SectionCard>
    <SectionCard title="Operations and monitoring" description="Lifecycle controls and current operational signals for status, drift, failures, DLQ, pending operations, mapping version, and credential expiry."><div className="civitas-action-bar"><button className="civitas-primary-button" type="button" onClick={() => setLifecycle("active")}>Activate</button><button className="civitas-secondary-button" type="button" onClick={() => setLifecycle("suspended")}>Suspend</button><button className="civitas-secondary-button" type="button" onClick={() => setLifecycle("archived")}>Archive</button></div><dl className="mt-4 grid gap-3 md:grid-cols-3"><div><dt className="text-xs text-muted-strong">Connection</dt><dd>{summary?.connectionId || `draft-scim-${organizationId || "organization"}`}</dd></div><div><dt className="text-xs text-muted-strong">Surface</dt><dd>{surface}</dd></div><div><dt className="text-xs text-muted-strong">Drift</dt><dd>{summary?.driftItemCount ?? 3} items</dd></div><div><dt className="text-xs text-muted-strong">Failures / DLQ</dt><dd>1 failed · 2 DLQ</dd></div><div><dt className="text-xs text-muted-strong">Pending operations</dt><dd>4 queued</dd></div><div><dt className="text-xs text-muted-strong">Mapping version</dt><dd>v{summary?.mappingVersion ?? 1}</dd></div><div><dt className="text-xs text-muted-strong">Credential expiry</dt><dd>{credentialState === "revoked" ? "revoked" : summary?.credentialExpiresAt ?? "90 days after generation"}</dd></div></dl></SectionCard>
  </div>;
};
