'use strict'

const ACTIONS = Object.freeze({
  CREATE_USER: 'CREATE_USER',
  LINK_USER: 'LINK_USER',
  ACTIVATE_USER: 'ACTIVATE_USER',
  SUSPEND_USER: 'SUSPEND_USER',
  ADD_ORGANIZATION_MEMBERSHIP: 'ADD_ORGANIZATION_MEMBERSHIP',
  REMOVE_ORGANIZATION_MEMBERSHIP: 'REMOVE_ORGANIZATION_MEMBERSHIP',
  ADD_MANAGED_ROLE: 'ADD_MANAGED_ROLE',
  REMOVE_MANAGED_ROLE: 'REMOVE_MANAGED_ROLE',
  BLOCK_BY_CEILING: 'BLOCK_BY_CEILING',
  REQUIRE_APPROVAL: 'REQUIRE_APPROVAL',
  NOOP: 'NOOP',
})

const MUTATING_ACTIONS = new Set([
  ACTIONS.CREATE_USER,
  ACTIONS.LINK_USER,
  ACTIONS.ACTIVATE_USER,
  ACTIONS.SUSPEND_USER,
  ACTIONS.ADD_ORGANIZATION_MEMBERSHIP,
  ACTIONS.REMOVE_ORGANIZATION_MEMBERSHIP,
  ACTIONS.ADD_MANAGED_ROLE,
  ACTIONS.REMOVE_MANAGED_ROLE,
])

module.exports = { ACTIONS, MUTATING_ACTIONS }
